alias nixhome="home-manager switch"
alias nixgc="nix-collect-garbage -d"
alias nixq="nix-env --description -qaP"
alias nixup="nix-env -u"
alias nixupgrade="nix-channel --update && nix-env -iA nixpkgs.nix"
# alias nixupgrade="sudo -i sh -c 'nix-channel --update && nix-env -iA nixpkgs.nix && launchctl remove org.nixos.nix-daemon && launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist'"
alias nixcfg="e ~/.config/nixpkgs/home.nix"
