#! /bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="clarson@kergoth.com"
export FULLNAME="Chris Larson"
export DEBEMAIL=$EMAIL
export DEBFULLNAME=$FULLNAME

export CVS_RSH=ssh
export CVSREAD=yes
export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
export CCACHE_DIR=~/.ccache
export INPUTRC=~/.inputrc
export GTK_IM_MODULE=xim

export LC_MESSAGES=C
export LC_ALL=

# Only allow items in these variables which aren't already there
typeset -U PATH path MANPATH manpath CDPATH cdpath

# Pair up some scalars with arrays
export -TU LD_LIBRARY_PATH ldlibpath
export -TU PKG_CONFIG_PATH pkgconfigpath
export -TU PYTHONPATH pythonpath
export -TU PERL5LIB perl5path

# Local paths
path=(~/bin ~/.root/bin ~code/go/bin $path ~/.root/sbin /usr/local/sbin /usr/sbin /sbin)
manpath=(~/.root/man ~/.root/share/man $manpath /usr/local/share/man /usr/local/man /usr/share/man /usr/man)
ldlibpath=(~/.root/lib /usr/local/lib $ldlibpath)
pkgconfigpath=(~/.root/lib/pkgconfig /usr/local/lib/pkgconfig $pkgconfigpath)
pythonpath=(~/.root/lib/python2.5 /usr/local/lib/python2.5 $pythonpath)
perl5path=(~/.root/lib/perl{,5}/5.*(N/) /usr/local/lib/perl{,5}/5.*(N/) $perl5path)

# Ruby gems
path=($path ~/.gem/ruby/*/bin(N/))

# Crazy non-standard paths. Bad developers, bad, no cookie for you.
path=($path /usr/lib/kde*/bin(N/) /var/lib/gems/*/bin(N/))

# Blah, /opt.
path=($path /opt/*/bin(N/))

export GIT_EXEC_PATH=${${$(whence -p git):h}:h}/libexec/git-core
if [[ $? -ne 0 ]]; then
    unset GIT_EXEC_PATH
fi

# less options
export LESS=FRSX
export PAGER=less

# grep options
export GREP_OPTIONS=--color=auto

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
export CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"

case $TERM in
    putty-256color)
        TERM=xterm-256color
        ;;
esac

if [[ $terminfo[colors] -ge 8 ]]; then
    if [[ -f ~/.dir_colors ]]; then
        eval `dircolors -b ~/.dir_colors`
    else
        eval `dircolors -b`
    fi
    ZLS_COLORS=$LS_COLORS
fi
