#! /bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export EMAIL="kergoth@gmail.com"
export FULLNAME="Christopher Larson"
export DEBEMAIL=$EMAIL
export DEBFULLNAME=$FULLNAME

export CVS_RSH=ssh
export CVSREAD=yes
export MANWIDTH=80
export EDITOR=vim
export VISUAL=vim
export INPUTRC=~/.inputrc
export GTK_IM_MODULE=xim

export LC_MESSAGES=C
export LC_ALL=

# Only allow items in these variables which aren't already there
typeset -U PATH path MANPATH manpath CDPATH cdpath

# Pair up some scalars with arrays
export -TU LD_LIBRARY_PATH ldlibpath
export -TU PKG_CONFIG_PATH pkgconfigpath
export -TU PYTHONPATH pythonpath
export -TU PERL5LIB perl5path

# Local paths
path=(~/bin ~/.local/bin $path ~/.local/sbin /usr/local/sbin /usr/sbin /sbin)
manpath=(~/.local/man ~/.local/share/man $manpath /usr/local/share/man /usr/local/man /usr/share/man /usr/man)
ldlibpath=(~/.local/lib /usr/local/lib $ldlibpath)
pkgconfigpath=(~/.local/lib/pkgconfig /usr/local/lib/pkgconfig $pkgconfigpath)
pythonpath=(~/.local/lib/python2.*(N/) /usr/local/lib/python2.*(N/) $pythonpath)
perl5path=(~/.local/lib/perl{,5}/5.*(N/) /usr/local/lib/perl{,5}/5.*(N/) $perl5path)

# Ruby gems
path=($path ~/.gem/ruby/*/bin(N/))

# Crazy non-standard paths. Bad developers, bad, no cookie for you.
path=($path /usr/lib/kde*/bin(N/) /var/lib/gems/*/bin(N/))

# Blah, /opt.
path=($path /opt/*/bin(N/))

# less options
export LESS=FRX
export PAGER=less

# grep options
export GREP_OPTIONS=--color=auto

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
export CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"

case $TERM in
    putty-256color)
        TERM=xterm-256color
        ;;
esac

if which dircolors >/dev/null 2>&1; then
    if [[ $terminfo[colors] -ge 8 ]]; then
        if [[ -f ~/.dir_colors ]]; then
            eval `dircolors -b ~/.dir_colors`
        else
            eval `dircolors -b`
        fi
        ZLS_COLORS=$LS_COLORS
    fi
fi

if [[ -e /etc/debian_chroot ]]; then
    export debian_chroot=$(cat /etc/debian_chroot)
    HOSTNAME=$HOSTNAME.$debian_chroot
fi

export PYTHONSTARTUP=~/.pythonrc.py
export ACKRC=.ackrc
