#!/bin/zsh

autoload zmv
alias mmv='noglob zmv -W'

alias j=jobs
alias d=dirs
alias pu=pushd
alias po=popd
alias ct=cleartool
alias cpe=clearprojexp
alias hd="od -t x1"
alias mt=monotone
alias bb=bitbake
alias rem=remind
alias se=sudoedit
alias more=less
alias rgrep="grep -rI"
alias gvim="vim -g"
alias vi=vim
alias bc='bc -ql'
alias t='t.py --task-dir ~/Documents --list tasks.txt'
alias e='eval $EDITOR'

if have ack-grep; then
    alias ack=ack-grep
fi

function diff() {
    typeset diffcmd="diff"
    if have colordiff && [[ -t 1 ]]; then
        diffcmd=colordiff
    fi
    command $diffcmd -uNd "$@"
}

function difftree() {
    diff -r -X ~/.zsh/dontdiff "$@"
}
alias dt=difftree

function svndiff() {
    svn diff "$@" | colordiff | least
}
alias svnd=svndiff

if [[ $terminfo[colors] -ge 8 ]]; then
    if [[ $(uname -s) = Darwin ]]; then
        lscolorarg='-G'
    else
        lscolorarg='--color=always'
    fi
else
    lscolorarg='-F'
fi

lsfe () {
    command ls -CABhq $lscolorarg "$@"
}

alias mr='mr -p'

# List only directories and symbolic
# links that point to directories
alias lsd='lsfe -ld *(-/DN)'
# List only file beginning with "."
alias lsa='lsfe -ld .*'
# List with recent files first
alias lsr='lsfe -tp'
alias lr='lsfe -ltp'
alias ls='lsfe -p'

if [[ $(uname -s) != Darwin ]]; then
    alias ps='ps -o user,group,pid,stat,cmd --forest'
fi

alias pcal-portrait="pcal -F 1 -m -J -p"
alias pcal-landscape="pcal -F 1 -m -J -l"

# Break old habits
ps() {
    if [[ $4 = "-ef" || $4 = "aux" ]]; then
        echo >&2 "ps: error: given our aliases, you don't want to use those arguments."
        echo >&2 "ps: perhaps you meant 'ps -e' or 'psgrep' or 'ppsgrep'?"
        return 1
    fi
    command ps "$@"
}

function bgexec () {
    "$@" &>/dev/null &
    disown 2>/dev/null
}

function wg () {
    wiggle --replace $1 $1.rej
}
