#!/usr/bin/env bash

set -euo pipefail

if [ -d ~/bin ] && ! [ -e ~/bin/.git ]; then
    (
        cd ~/bin || exit 1
        if ! command -v git &>/dev/null; then
            echo >&2 "Error: git not found, exiting"
            exit 1
        fi
        git init
        git remote add origin https://github.com/kergoth/scripts
        git fetch --depth=1 origin main
        git checkout --force -b main origin/main
    ) || {
        rm -rf ~/bin/.git
        exit 1
    }
fi
