#include "nsISupports.idl"

interface nsIArray;

[scriptable, uuid(98929A9C-8B12-11DB-9339-3CA956D89593)]
interface nsIYBundle: nsISupports {
  attribute wstring 	name;
  attribute nsIArray 	tags;
 	attribute wstring 	order;
};
