#include "nsISupports.idl"

interface nsIArray;

[scriptable, uuid(FF975662-87E6-4480-B3DF-CA65FFB3CE42)]
interface nsIYBookmark: nsISupports {
  attribute wstring id;
  attribute wstring name;
  attribute wstring url;
  attribute wstring type;
  attribute wstring description;
  attribute wstring shortcut;
  attribute wstring postData;
  attribute wstring charset;
  attribute unsigned long long last_visited;
  attribute unsigned long long last_modified;
  attribute unsigned long long added_date;
  attribute short visit_count;
  attribute nsIArray tags;
  attribute wstring icon;
  attribute wstring shared;
  attribute boolean isWebPanel; // open the bookmark in a side bar, rather than in main window
  attribute wstring localOnly;  
};
