#!/bin/sh
# Run the specified commands in separate panes

adaptable_args="-p 50 -l main-vertical"

usage() {
    echo >&2 "${0##*/} [options] CMD [CMD..]"
    echo >&2
    echo >&2 Options:
    echo >&2 "  -k   Kill the first (default) pane. Useful for new sessions."
    echo >&2 "  -t SESSION    Specify the session to interact with."
    echo >&2 "  -a ADAPTABLE_ARGS   Specify args to pass to tmux-resize-adaptable. Default: $adaptable_args"
    exit 2
}

kill_first=0
session=
while getopts kt:a:h opt; do
    case "$opt" in
        k)
            kill_first=1
            ;;
        t)
            session="$OPTARG"
            ;;
        a)
            adaptable_args="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
    for cmd; do
        tmux split-window -f ${session:+-t "$session"} "$cmd; printf >&2 '%s ended with %d. Press a key.\\n' \"$cmd\" \"$?\"; read"
    done
    if [ $kill_first -eq 1 ]; then
        tmux kill-pane -t "${session:+$session:}1.1"
        tmux select-pane -t "${session:+$session:}1.1"
    fi
fi
# shellcheck disable=SC2086
tmux-resize-adaptable ${session:+-t "$session"} $adaptable_args
