#!/usr/bin/env bash

set -euo pipefail

export ASDF_DATA_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}"
export ASDF_DIR="$ASDF_DATA_DIR"

scriptdir="$(dirname "$0")"
PATH="$scriptdir:$PATH"

usage() {
    cat >&2 <<END
    ${0##*/} [options] PLUGIN [VERSION]

    Options:

    -g    Set to the default global version
    -l    Set to the default local version
    -f    Force reinstallation if necessary
END
    exit 2
}

global=0
local=0
force=0
while getopts glfh opt; do
    case "$opt" in
    g)
        global=1
        ;;
    l)
        local=1
        ;;
    f)
        force=1
        ;;
    \? | h)
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
    asdf install
fi

plugin=$1
shift

asdf update >/dev/null 2>&1

if [ ! -e "$ASDF_DATA_DIR/plugins/$plugin" ]; then
    asdf plugin-add "$plugin"
else
    asdf plugin-update "$plugin" >/dev/null 2>&1
fi

version=${1:-latest}
case "$version" in
latest)
    version="$(asdf latest "$plugin")"
    if dot_version="$(asdf latest "$plugin" "$version." 2>/dev/null)"; then
        version="$dot_version"
    fi
    ;;
latest:*)
    version="$(asdf latest "$plugin" "${version#latest:}")"
    if dot_version="$(asdf latest "$plugin" "$version.") 2>/dev/null"; then
        version="$dot_version"
    fi
    ;;
esac

if [ -e "$scriptdir/$plugin-build-env.sh" ]; then
    echo >&2 "Using '$scriptdir/$plugin-build-env.sh'"
    eval "$(echo "$plugin" | tr '[:lower:]' '[:upper:]')_VERSION=$version"
    # shellcheck disable=SC1090
    . "$scriptdir/$plugin-build-env.sh"
fi

echo >&2 "asdf-install: installing version $version of $plugin"

if [ "$force" -eq 1 ]; then
    rm -rf "$ASDF_DIR/installs/$plugin/$version"
fi
(
    case "${OSTYPE:-}" in
    darwin*) ;;

    *)
        if command -v brew >/dev/null 2>&1; then
            BREW_PREFIX="$(brew --prefix)"
            # Remove linuxbrew from the path
            PATH="$(echo "$PATH" | tr : '\n' | grep -vx "$BREW_PREFIX/bin" | paste -s -d:)"
        fi
        ;;
    esac
    asdf install "$plugin" "$version"
)

if [ "$global" -eq 1 ]; then
    asdf global "$plugin" "$version"
fi
if [ "$local" -eq 1 ]; then
    asdf local "$plugin" "$version"
fi
