#!/usr/bin/env bash

set -euo pipefail

remove_multiple_blank_lines() {
    sed -e '/\S/,/^\s*$/!d;'
}

remove_trailing_blank_lines() {
    sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'
}

remove_heading_trailing_punctuation() {
    sed -e 's/^\(#.*\):/\1/'
}

nest_headings() {
    sed -e 's/^\(##*\)/#\1/'
}

correct_bare_url() {
    sed -e 's/^\(View this issue on Jira: \)\(.*\)/\1<\2>/'
}

adjust_headers() {
    sed -e 's/--* \(.*\) --*.*/### \1/'
}

tmpfile=$(mktemp -t "${0##*/}.XXXXXX")
trap 'rm -f "$tmpfile"' EXIT INT TERM

jira issue view --plain --comments 999 "$@" |
    strip-color-codes |
    sed -e 's/^  //; s/  *$//;' >"$tmpfile"

if [ -s "$tmpfile" ]; then
    grep '^# ' "$tmpfile"
    echo
    echo '## JIRA Issue'
    echo
    grep -v '^# ' "$tmpfile" |
        nest_headings |
        adjust_headers |
        remove_multiple_blank_lines |
        remove_trailing_blank_lines |
        remove_heading_trailing_punctuation |
        correct_bare_url
fi
