#!/bin/sh

default_threshold=2
TAB="$(printf '\t')"

usage() {
    cat <<END >&2
${0##*/} [options..] URL_FILTER

Options:
  -t THRESHOLD  Set threshold of # of entries before we mark it as behind. Default: $default_threshold
  -h   Show usage
END
    exit 2
}

threshold="$default_threshold"
while getopts t:h opt; do
    case "$opt" in
        t)
            threshold="$OPTARG"
            ;;
        n)
            dry_run="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage
fi

filter="$1"
shift
if [ -z "$filter" ]; then
    echo >&2 "Error: must specify a url filter"
    exit 1
fi

urls="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$urls"' EXIT INT TERM

printf >&2 'Processing %s\n' "$filter"

pocket-search -s unread -o oldest "$filter" \
    | cut -d"$TAB" -f1,2 >>"$urls"

# shellcheck disable=SC2046
if [ $(wc -l <"$urls") -gt "$threshold" ]; then
    keep_id="$(head -n 1 "$urls" | cut -d"$TAB" -f1)"
    archive_ids="$(tail -n +2 "$urls" | cut -d"$TAB" -f1 | xargs)"
    if [ -z "$archive_ids" ]; then
        echo >&2 "Error: no chapter ids to archive?"
        exit 1
    fi

    echo >&2 "Keep id $keep_id"
    pocket-add-tag 'fiction - behind' "$keep_id"
    pocket-remove-tag fiction "$keep_id"

    echo >&2 "Archive ids $archive_ids"
    echo "$archive_ids" | xargs pocket-archive
fi
