#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..]

Options:
  -t THRESHOLD Threshold # of books to consider behind.
  -h   Show usage
END
    exit 2
}

threshold=1
while getopts t:h opt; do
    case "$opt" in
        t)
            threshold="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

TAB="$(printf '\t')"

urls="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
chapters="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$urls" "$chapters"' EXIT INT TERM
cat \
    | cut -d"$TAB" -f1,2 \
    | grep -E '/fiction/[0-9].*/chapter/' >>"$urls"

# 5 is fiction id, 6 is fiction name, 8 is chapter id
cut -d/ -f5 "$urls" \
    | sort -un \
    | while read -r fiction_id; do
        grep "/fiction/$fiction_id/" "$urls" \
            | cut -d"$TAB" -f2 \
            | sort -t/ -n \
            >"$chapters"
        # shellcheck disable=SC2046
        if [ $(wc -l <"$chapters") -gt "$threshold" ]; then
            fiction_name="$(head -n 1 "$chapters" | cut -d/ -f6)"
            printf >&2 'Processing %s\n' "$fiction_name"
            keep_id="$(head -n 1 "$chapters" | cut -d/ -f8)"
            archive_ids="$(tail -n +2 "$chapters" | cut -d/ -f8 | xargs)"
            if [ -z "$archive_ids" ]; then
                echo >&2 "Error: no chapter ids to archive?"
                exit 1
            fi

            echo >&2 "Keep chapter id $keep_id"
            keep_pocket_id="$(grep "/chapter/$keep_id/" "$urls" | cut -d"$TAB" -f1)"
            if [ -z "$keep_pocket_id" ]; then
                echo >&2 "Error: failed to determine pocket id for chapter $keep_id"
                exit 1
            fi
            pocket-add-tag 'fiction - behind' "$keep_pocket_id"
            pocket-remove-tag fiction "$keep_pocket_id"

            echo >&2 "Archive chapter ids $archive_ids"
            echo "$archive_ids" \
                | tr ' ' '\n' \
                | xargs -I"{}" grep "/chapter/{}/" "$urls" \
                | cut -d"$TAB" -f1 \
                | xargs pocket-archive
        fi
    done
