#!/usr/bin/env python3

import click
import errno
import os
import subprocess
from configparser import ConfigParser
from pocket import Pocket


def load_pocket_config():
    config = ConfigParser()
    with open(os.path.expanduser('~/.pocket-config')) as f:
        config.readfp(f)
    return config['pocket']


def init_pocket(config):
    key = config.get('consumer_key')
    token = config.get('access_token')
    pocket = Pocket(key, token)
    return pocket


@click.command()
@click.argument('id', nargs=-1)
def archive(id):
    try:
        pocket_config = load_pocket_config()
    except OSError:
        subprocess.check_call(['pocket-cli', 'fetch'])
        pocket_config = load_pocket_config()

    pocket = init_pocket(pocket_config)
    for article_id in id:
        article_id = int(article_id)
        print('Archiving %r' % article_id)
        pocket.archive(article_id)
    pocket.commit()


if __name__ == '__main__':
    archive()
