#!/bin/sh

TAB="$(printf '\t')"
tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM
pocket-search -s unread -t fiction royalroad.com | sort -t"$TAB" -k2 >>"$tmpfile"
cat "$tmpfile" \
    | grep /chapter/ \
    | while IFS="$TAB" read -r id url _; do
        fiction="$(echo "$url" | sed -e 's#/chapter/.*##')"
        latest="$(grab-links "$fiction" | grep "$fiction/chapter/" | tail -n 1)"
        echo >&2 "Checking chapter: $url"
        echo >&2 "Latest chapter: $latest"
        if [ "$url" != "$latest" ]; then
            echo >&2 "$fiction is behind"
            pocket-add-tag "fiction - behind" "$id"
            pocket-remove-tag fiction "$id"
        fi
    done
