#!/usr/bin/env python3

import os
import sys
from configparser import ConfigParser
from pocket import Pocket

config = ConfigParser()
with open(os.path.expanduser('~/.pocket-config')) as f:
    config.readfp(f)

key = config.get('pocket', 'consumer_key')
token = config.get('pocket', 'access_token')

tag = sys.argv[1]
pocket = Pocket(key, token)
for id_str in sys.argv[2:]:
    try:
        id = int(id_str)
    except ValueError:
        continue
    pocket.tags_remove(id, [tag])
pocket.commit()
