#!/bin/sh

if which parallel >/dev/null 2>&1; then
    alias xargs=parallel
fi

pocket-cli search -s unread -o oldest '' | \
    pocket-cli-join-entries | \
    while IFS="$(printf '\t')" read -r id url _; do
        echo >&2 "Checking '$url'"
        http -hFI --check-status "$url" >/dev/null 2>&1
        case "$?" in
            [45])
                echo "$id"
                ;;
        esac
    done | tee log | nlxargs -t -n 1 pocket-cli archive
