-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["subs"] = {
            [1] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS<4>",
                ["split_tree"] = {
                    ["tls"] = 1227,
                    ["tl"] = {
                        ["tls"] = 1035,
                        ["tl"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["flags"] = 0,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<5>",
                                ["subs"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 8388612,
                                        ["switchto"] = true,
                                        ["checkcode"] = 1,
                                    },
                                    [2] = {
                                        ["checkcode"] = 2,
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 8388716,
                                    },
                                },
                                ["frame_style"] = "frame-tiled-ionws",
                            },
                        },
                        ["dir"] = "vertical",
                        ["brs"] = 15,
                        ["br"] = {
                            ["type"] = "WSplitST",
                        },
                        ["type"] = "WSplitSplit",
                    },
                    ["dir"] = "horizontal",
                    ["brs"] = 453,
                    ["br"] = {
                        ["tls"] = 525,
                        ["tl"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["flags"] = 0,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame",
                                ["subs"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 6291613,
                                        ["switchto"] = true,
                                        ["checkcode"] = 3,
                                    },
                                },
                                ["frame_style"] = "frame-tiled-ionws",
                            },
                        },
                        ["dir"] = "vertical",
                        ["brs"] = 525,
                        ["br"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["flags"] = 0,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<1>",
                                ["subs"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 7056542,
                                        ["switchto"] = true,
                                        ["checkcode"] = 4,
                                    },
                                },
                                ["frame_style"] = "frame-tiled-ionws",
                            },
                        },
                        ["type"] = "WSplitSplit",
                    },
                    ["type"] = "WSplitSplit",
                },
            },
            [2] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS",
                ["switchto"] = true,
                ["split_tree"] = {
                    ["tls"] = 1035,
                    ["tl"] = {
                        ["type"] = "WSplitRegion",
                        ["regparams"] = {
                            ["flags"] = 0,
                            ["type"] = "WFrame",
                            ["name"] = "WFrame<2>",
                            ["subs"] = {
                                [1] = {
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 8388779,
                                    ["switchto"] = true,
                                    ["checkcode"] = 5,
                                },
                            },
                            ["frame_style"] = "frame-tiled-ionws",
                        },
                    },
                    ["dir"] = "vertical",
                    ["brs"] = 15,
                    ["br"] = {
                        ["type"] = "WSplitST",
                    },
                    ["type"] = "WSplitSplit",
                },
            },
            [3] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS<1>",
                ["split_tree"] = {
                    ["tls"] = 840,
                    ["tl"] = {
                        ["tls"] = 1035,
                        ["tl"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["flags"] = 0,
                                ["type"] = "WFrame",
                                ["name"] = "WFrame<3>",
                                ["subs"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 8388667,
                                        ["switchto"] = true,
                                        ["checkcode"] = 6,
                                    },
                                    [2] = {
                                        ["checkcode"] = 7,
                                        ["type"] = "WClientWin",
                                        ["windowid"] = 8388749,
                                    },
                                },
                                ["frame_style"] = "frame-tiled-ionws",
                            },
                        },
                        ["dir"] = "vertical",
                        ["brs"] = 15,
                        ["br"] = {
                            ["type"] = "WSplitST",
                        },
                        ["type"] = "WSplitSplit",
                    },
                    ["dir"] = "horizontal",
                    ["brs"] = 840,
                    ["br"] = {
                        ["type"] = "WSplitRegion",
                        ["regparams"] = {
                            ["flags"] = 0,
                            ["type"] = "WFrame",
                            ["name"] = "WFrame<4>",
                            ["subs"] = {
                                [1] = {
                                    ["checkcode"] = 8,
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 8388652,
                                },
                                [2] = {
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 14680067,
                                    ["switchto"] = true,
                                    ["checkcode"] = 9,
                                },
                                [3] = {
                                    ["checkcode"] = 10,
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 18874464,
                                },
                            },
                            ["frame_style"] = "frame-tiled-ionws",
                        },
                    },
                    ["type"] = "WSplitSplit",
                },
            },
            [4] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS<2>",
                ["split_tree"] = {
                    ["tls"] = 1035,
                    ["tl"] = {
                        ["type"] = "WSplitRegion",
                        ["regparams"] = {
                            ["flags"] = 0,
                            ["type"] = "WFrame",
                            ["name"] = "WFrame<6>",
                            ["subs"] = {
                                [1] = {
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 18917851,
                                    ["switchto"] = true,
                                    ["checkcode"] = 11,
                                },
                                [2] = {
                                    ["checkcode"] = 12,
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 19266863,
                                },
                            },
                            ["frame_style"] = "frame-tiled-ionws",
                        },
                    },
                    ["dir"] = "vertical",
                    ["brs"] = 15,
                    ["br"] = {
                        ["type"] = "WSplitST",
                    },
                    ["type"] = "WSplitSplit",
                },
            },
            [5] = {
                ["type"] = "WScratchpad",
                ["frame_style"] = "frame-scratchpad",
                ["layer"] = 2,
                ["hidden"] = true,
                ["flags"] = 0,
                ["passive"] = false,
                ["name"] = "WScratchpad",
                ["subs"] = {
                },
                ["geom"] = {
                    ["y"] = 285,
                    ["h"] = 480,
                    ["w"] = 640,
                    ["x"] = 520,
                },
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen",
    },
}

