#!/bin/sh

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

if [ -t 1 ]; then
    color=1
else
    color=0
fi

format_issues () {
    if [ $color -eq 1 ]; then
        sed -e 's/		/	 	/g' | \
            while IFS="$(printf '\t')" read -r key assignee summary; do
                printf "${RED}%-8s ${BRIGHT}${BLUE}%-10s ${NORMAL}%s %s\n" "$key" "$assignee" "$summary"
            done
    else
        cat
    fi
}

jira-cli view --format "%key	%assignee	%summary	%link" "$@" | format_issues
