# This tmux statusbar config was created by tmuxline.vim
# on Wed, 02 Sep 2026

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=#000000,bg=#ebebeb"
set -g status-right-style "none"
set -g pane-active-border-style "fg=#b4d8fd"
set -g status-style "none,bg=#b4d8fd"
set -g message-style "fg=#000000,bg=#ebebeb"
set -g pane-border-style "fg=#ebebeb"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=#000000,bg=#b4d8fd"
set -g status-left "#[fg=#000000,bg=#b4d8fd] #S #[fg=#b4d8fd,bg=#b4d8fd,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#b4d8fd,bg=#b4d8fd,nobold,nounderscore,noitalics]#[fg=#000000,bg=#b4d8fd] %Y-%m-%d | %H:%M #[fg=#b4d8fd,bg=#b4d8fd,nobold,nounderscore,noitalics]#[fg=#000000,bg=#b4d8fd] #h "
setw -g window-status-format "#[fg=#000000,bg=#b4d8fd] #I |#[fg=#000000,bg=#b4d8fd] #W "
setw -g window-status-current-format "#[fg=#b4d8fd,bg=#ebebeb,nobold,nounderscore,noitalics]#[fg=#000000,bg=#ebebeb] #I |#[fg=#000000,bg=#ebebeb] #W #[fg=#ebebeb,bg=#b4d8fd,nobold,nounderscore,noitalics]"
