#!/usr/bin/env bash
# Given a Brewfile, diff it against the current configuration.

# Usage: ./brewfile-diff-dump Brewfile [Brewfile..]

scriptdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# shellcheck source=../common.sh
. "$scriptdir/../common.sh"

set -e

usage() {
    echo >&2 "${0##*/} [options] Brewfile [Brewfile..]"
    exit 2
}

if [ $# -eq 0 ]; then
    usage
fi

if ! command -v brew &>/dev/null; then
    echo "Homebrew is not installed."
    exit 1
fi

export HOMEBREW_NO_AUTO_UPDATE=1

diff_highlight() {
    if [ -t 1 ]; then
        if command -v delta &>/dev/null; then
            delta --file-style=omit --hunk-header-style=omit
        elif command -v diff-highlight >/dev/null 2>&1 && command -v perl >/dev/null 2>&1; then
            diff-highlight
        else
            cat
        fi
    else
        cat
    fi
}

brewfiles_dump() {
    echo 'cask_args appdir: "~/Applications"'
    echo

    for brewfile; do
        if [ -d "$brewfile" ]; then
            find "$brewfile" -type f -not -name .DS_Store -print0 |
                while read -r -d '' brewfile; do
                    brewfile_cat "$brewfile"
                done
        else
            brewfile_cat "$brewfile"
        fi
    done |
        grep -v '^cask_args' |
        grep -v '^#' |
        grep -v '^ *$' |
        sort -uf
}

bundle_dump() {
    echo 'cask_args appdir: "~/Applications"'
    echo
    brew bundle dump --file=- |
        grep -v '^vscode' |
        sed -e 's#, args: { appdir: "~/Applications" }##' |
        grep -v '^ *$' |
        sort -uf
}

# Compare Brewfile to current configuration
diff -ud <(brewfiles_dump "$@") <(bundle_dump) | diff_highlight
