#!/bin/sh

set -e

if [ $# -eq 0 ]; then
    usage
fi
dir="$1"
shift

if [ -n "$HOMEBREW_PREFIX" ]; then
    HOMEBREW_PREFIX="$(echo "$HOMEBREW_PREFIX" | sed -e "s#~#$HOME#")"
    PATH="$HOMEBREW_PREFIX/bin:$PATH"
fi

cd "$dir" || exit 1
command "$@"
