#!/bin/sh

dotfiles="$1"
if [ -z "$dotfiles" ]; then
    dotfiles=~/.dotfiles
fi

if [ ! -e "$dotfiles" ]; then
    git clone --recursive git://github.com/kergoth/dotfiles "$dotfiles"
fi
$dotfiles/install "$2"
