#!/bin/sh

set -e

dotfiles=$1
if [ -z "$dotfiles" ]; then
    dotfiles=~/.dotfiles
fi

if [ ! -e $dotfiles ]; then
    git clone --recursive git://github.com/kergoth/homefiles $dotfiles
fi
cd $dotfiles

while read dest url; do
    if [ ! -e $dotfiles/$dest ]; then
        hg clone $url $dotfiles/$dest
    fi
done<<END
hgext/crecord https://bitbucket.org/edgimar/crecord
hgext/histedit https://bitbucket.org/durin42/histedit
hgext/pbranch https://bitbucket.org/parren/hg-pbranch
hgext/prompt https://bitbucket.org/sjl/hg-prompt
hgext/shelve https://bitbucket.org/astiob/hgshelve
END

$dotfiles/bin/dotfiles-install

mkdir -p $HOME/.local/share/fasd
