#!/bin/sh

set -e

dotfiles=$1
if [ -z "$dotfiles" ]; then
    dotfiles=~/.dotfiles
fi

git clone --recursive https://github.com/kergoth/homefiles $dotfiles
while read dest url; do
    hg clone $url $dotfiles/$dest
done<<END
hgext/crecord https://bitbucket.org/edgimar/crecord
hgext/histedit https://bitbucket.org/durin42/histedit
hgext/pbranch https://bitbucket.org/parren/hg-pbranch
hgext/prompt https://bitbucket.org/sjl/hg-prompt
hgext/shelve https://bitbucket.org/tksoh/hgshelve
END

~/.dotfiles/bin/dotfiles-install
