#!/bin/bash

set -u

: ${XDG_CONFIG_HOME:=~/.config}
: ${XDG_DATA_HOME:=~/.local/share}
case "$OSTYPE" in
    darwin*)
        : ${XDG_CACHE_HOME:=~/Library/Caches}
        ;;
    *)
        : ${XDG_CACHE_HOME:=~/.cache}
        ;;
esac

osname="$(uname -s)"
HOSTNAME=$(hostname -s)
prefixes="%include %include%${osname} %include%${HOSTNAME}"
force=0
exclude="sublime-text-2"
include=

set_launchd () {
    var="$1"
    value="$2"

    case "$OSTYPE" in
        darwin*)
            ;;
        *)
            return
            ;;
    esac

    plist_set () {
        plist_key="$(printf "%s" "$1" | sed "s/'/\\\\'/g")"
        plist_val="$(printf "%s" "$2" | sed "s/'/\\\\'/g")"
        if /usr/libexec/PlistBuddy -c "Print '$plist_key'" "$3" >/dev/null 2>&1; then
            /usr/libexec/PlistBuddy -c "Set '$plist_key' '$plist_val'" "$3"
        else
            /usr/libexec/PlistBuddy -c "Add '$plist_key' "${4:-string}" '$plist_val'" "$3"
        fi
    }

    mkdir -p ~/.MacOSX
    plist_set "$var" "$value" ~/.MacOSX/environment.plist

    if which launchctl &>/dev/null; then
        launchctl setenv "$var" "$value"
    fi

    if [ ! -e ~/Library/PreferencePanes/EnvPane.prefPane ]; then
        printf >&2 "Warning: EnvPane is not installed, set of env var %s to %s will not persist\n" "$var" "$value"
    fi
}

should_replace () {
    if ! [ -e "$1" ] && ! [ -L "$1" ]; then
        return 0
    fi

    if [ $force -eq 0 ]; then
        while true; do
            read -n 1 -p "Replace existing $1? [Y|n] " will_continue
            printf "\n"
            case "$will_continue" in
                [yY]|"")
                    return 0
                    ;;
                [nN])
                    return 1
                    ;;
                *)
                    echo >&2 "Invalid input '$will_continue'"
                    ;;
            esac
        done
    else
        return 1
    fi
}

link () {
    # Link a file to a destination using a relative path, with particular
    # convenience handling for dotfiles. ex.:
    #
    # link zsh/.zshenv.redir ~/.zshenv.redir
    # link zshrc       # links to ~/.zshrc (relatively)
    # link config/curl # links to ~/.config/curl (relatively)
    dotfile="${1#$PWD/}"
    if [ $# -gt 1 ]; then
        dotfile_dest="$(abspath "$2")"
    else
        case "$dotfile" in
            .*)
                dotfile_dest="$HOME/$dotfile"
                ;;
            *)
                dotfile_dest="$HOME/.$dotfile"
                ;;
        esac
    fi
    destdir="${dotfile_dest%/*}"
    if [ "$destdir" != "$dotfile_dest" ]; then
        mkdir -p "$destdir"
    fi
    dotfile_relpath="$(relpath "$PWD/$dotfile" "$destdir")"

    # Sanity check
    dotfile_resolved="$(normalize_path "${dotfile_dest%/*}/$dotfile_relpath")"
    if [ ! -e "$dotfile_resolved" ]; then
        echo >&2 "Error: $dotfile_resolved does not exist"
        return 1
    fi

    if [ -L "$dotfile_dest" ] || [ -e "$dotfile_dest" ]; then
        if [ $force -eq 0 ] && [ "$(readlink "$dotfile_dest")" != "$dotfile_relpath" ]; then
            echo >&2 "Warning: $dotfile_dest already exists and does not link to $dotfile_relpath"
            read -n 1 -p "Replace $dotfile_dest? [Y|n] " will_continue
            printf "\n"
            case "$will_continue" in
                [yY]|"")
                    rm -rf "$dotfile_dest.old"
                    mv "$dotfile_dest" "$dotfile_dest.old"
                    echo >&2 "Removed $dotfile_dest (backed up as $dotfile_dest.old)"
                    ;;
                [nN])
                    rm -rf "$dotfile_dest.new"
                    ln -s "$dotfile_relpath" "$dotfile_dest.new"
                    echo >&2 "Linked $dotfile_dest.new"
                    return 1
                    ;;
                *)
                    echo >&2 "Invalid input '$will_continue', not replacing"
                    rm -rf "$dotfile_dest.new"
                    ln -s "$dotfile_relpath" "$dotfile_dest.new"
                    echo >&2 "Linked $dotfile_dest.new"
                    return 1
                    ;;
            esac
        else
            rm -f "$dotfile_dest"
        fi
    fi
    ln -s "$dotfile_relpath" "$dotfile_dest"
    echo >&2 "Linked $dotfile_dest"
}

abspath () {
    # Return an absolute path for the specified argument
    _path="$1"
    if [ -n "${_path##/*}" ]; then
        _path="$PWD/$1"
    fi
    echo "$_path"
}

normalize_path()
{
    # Attempt to normalize the specified path, removing . and ..

    # Remove all /./ sequences.
    local path="${1//\/.\//\/}"

    # Remove dir/.. sequences.
    while [[ $path =~ ([^/][^/]*/\.\./) ]]
    do
        path="${path/${BASH_REMATCH[0]}/}"
    done
    echo "$path"
}

install_templated () {
    # Extremely basic template file generation, currently only implements
    # %include, which does what you would expect
    dotfile_dest="$2"
    destdir="${dotfile_dest%/*}"
    if [ "$destdir" != "$dotfile_dest" ]; then
        mkdir -p "$destdir"
    fi

    cat "$1" | while IFS='|' read line; do
        files=
        for prefix in $prefixes; do
            case "$line" in
                $prefix\ *)
                    files="${line#$prefix }"
                    ;;
            esac
        done

        if [ -z "$files" ]; then
            case "$line" in
                %include%*)
                    ;;
                *)
                    printf "%s\n" "$line"
                    ;;
            esac
            continue
        fi

        for file in $(echo $files); do
            cat "$file"
        done
    done >"$dotfile_dest"
    echo >&2 "Wrote $(abspath "$dotfile_dest")"
}

merge_to () {
    # Convenience wrapper for merging multiple files into one dotfile
    dotfile_dest="$1"
    destdir="${dotfile_dest%/*}"
    if [ "$destdir" != "$dotfile_dest" ]; then
        mkdir -p "$destdir"
    fi
    shift
    cat "$@" >$dotfile_dest
    echo >&2 "Wrote $(abspath "$dotfile_dest")"
}

usage () {
    printf "Usage: $0 [-f] [-x EXCLUDE_DIRS] [DOTFILE_HOME]\n"
    printf "\n"
    printf "DOTFILE_HOME defaults to \$HOME\n"
    printf "Options:\n"
    printf "  -f                Force install, overwriting any existing files\n"
    printf "  -x EXCLUDE_DIRS   Dotfile directories to exclude from the install\n"
    printf "  -i INCLUDE_DIRS   Additional dotfile directories to install\n"
    exit 1
}

while (( $# )); do
    case "$1" in
        -f)
            force=1
            ;;
        -x)
            shift || usage >&2
            exclude="$1"
            ;;
        -i)
            shift || usage >&2
            include="$1"
            ;;
        -*)
            usage >&2
            ;;
        *)
            break
            ;;
    esac
    shift
done


if [ $# -gt 0 ]; then
    DOTFILE_HOME="$(abspath "$1")"
else
    DOTFILE_HOME="${DOTFILE_HOME:-${HOME}}"
fi

dotfilesdir="$(abspath "${0%/*}")"
PATH="$dotfilesdir/scripts:$PATH"

do_install () {
    installscript="$1"
    cd "${installscript%/*}"
    . "./${installscript##*/}"
    cd - >/dev/null
}


if [ -n "$exclude" ]; then
    echo >&2 "Excluded directories: $exclude"
fi

if [ -n "$include" ]; then
    echo >&2 "Additional directories to install: $include"
fi

HOME="$DOTFILE_HOME"
for installscript in "$dotfilesdir/"*/install; do
    installdir="${installscript%/*}"
    if echo "$exclude" | grep -qw "${installdir##*/}"; then
        continue
    fi

    do_install "$installscript"
done

for includepath in $include; do
    do_install $include/install
done

exit 0

# vim: set sw=4 sts=4 ts=8 et:
