#!/bin/sh

set -eu

topdir="$(cd "$(dirname "$0")" && pwd -P)"
tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX")"
trap 'rm -rf "$tmpdir"' EXIT INT TERM

cd "$topdir"
./peru reup -f || :

cd "$tmpdir"
git clone https://github.com/petdance/ack2
cd ack2
cpanm --local-lib "$PWD/perl5" local::lib && eval $(perl -I "$PWD/perl5/lib/perl5" -Mlocal::lib) && cpanm File::Next && perl Makefile.PL && make ack-standalone
#perl Makefile.PL && make ack-standalone
mv ack-standalone "$topdir/scripts/ack"
