#!/bin/sh

untracked="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$untracked"' EXIT INT TERM

git mstash
ret="$?"

git ls-files -o | sort -u >"$untracked"
"$(dirname "$0")/scripts/dotfiles-external-update" "$@"
dtret="$?"
git ls-files -o | sort -u >"$untracked.new"

comm -13 "$untracked" "$untracked.new" | tr '\n' '\0' | xargs -0 git add
git add -u
if [ $dtret -ne 0 ]; then
    git drop
else
    git commit -n -s -m "Update externals" && \
        git log --stat -1
fi

if [ "$ret" -eq 0 ]; then
    git stash apply
fi
exit "$dtret"
