#!/bin/sh

set -eu

# Very light wrapper around cargo-update for convenience
export CARGO_INSTALL_ROOT=${CARGO_INSTALL_ROOT:-${XDG_DATA_HOME:-~/.local/share}/..}

if cargo install-update -l >/dev/null 2>&1; then
    can_update=1
else
    can_update=0
fi

if ! [ -e "$CARGO_INSTALL_ROOT/bin/cargo-install-update" ]; then
    cargo install --force "$@" cargo-update
elif [ $can_update -eq 0 ]; then
    cargo install --force cargo-update
else
    cargo install-update -i cargo-update
fi

if [ $can_update -eq 0 ]; then
    cargo install "$@"
else
    cargo install-update -ig "$@"
fi
