#!/bin/sh

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
CARGO_ENV_HOME="${CARGO_ENV_HOME:-$XDG_DATA_HOME/cargo-roots}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} ENV_NAME [PIP_ARGS..]"
    echo >&2
    echo >&2 "Existing environments:"
    for dir in "$CARGO_ENV_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

root="$1"
shift
case "$root" in
    -*)
        echo >&2 "Error: ENV_NAME starts with -: $root"
        exit 1
        ;;
esac

root_dir="$CARGO_ENV_HOME/$root"

if [ $# -eq 0 ]; then
    set -- "$root"
fi
cargo install --force --root "$root_dir" "$@" || exit 4

mkdir -p "$XDG_DATA_HOME/../bin"
for script in "$root_dir/bin/"*; do
    filename="${script##*/}"
    link_name="$XDG_DATA_HOME/../bin/$filename"
    printf >&2 '’%s’ -> ’%s’\n' "$link_name" "$script"
    rm -f "$link_name"
    ln -sf "$root_dir/bin/$filename" "$link_name"
done

for man in "$root_dir/share/man/"man*/*; do
    if [ -e "$man" ]; then
        mandest="$XDG_DATA_HOME/man/${man#$root_dir/share/man/}"
        mkdir -p "${mandest%/*}"
        ln -sfv "$man" "$mandest"
    fi
done
