#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] [--] [KAK_ARGS..]

Options:
  -n SERVER_NAME
  -h   Show usage
END
    exit 2
}

while getopts n:h opt; do
    case "$opt" in
        n)
            server_name="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "$server_name" ]; then
    server_name=$(pwd -P | sed 's#^/##' | tr / _)
fi

socket_file=$(kak -l | grep -x "$server_name")

if [ -z "$socket_file" ]; then
    if command -v setsid >/dev/null 2>&1; then
        setsid=setsid
    else
        setsid=
    fi
    $setsid kak -d -s "$server_name" >/dev/null 2>&1 &
fi

kak -c "$server_name" "$@"
