source $VIMRUNTIME/scripts.vim

if did_filetype()
  finish
endif

if expand("<amatch>") !~ g:ft_ignore_pat
\  && (getline(1) =~ '^# Generated by iptables-save' ||
\  getline(1) =~ '^# Firewall configuration written by')
  setfiletype iptables
  set commentstring=#%s
endif
