#!/usr/bin/env bash
# shellcheck disable=SC2002

set -euo pipefail

usage() {
    cat <<END >&2
${0##*/} [options..] URL [URL..]"

Options:
  -t TAGS         Add specified tags
  -r              Add recommended tags
  -d DESCRIPTION  Manually specify description
  -T TITLE        Manually specify title
  -h              Show usage
END
    exit 2
}

tags=
title=
description=
add_recommended_tags=0
while getopts t:T:d:rh opt; do
    case "$opt" in
        t)
            tags="$OPTARG"
            ;;
        T)
            title="$OPTARG"
            ;;
        d)
            description="$OPTARG"
            ;;
        r)
            add_recommended_tags=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi


tmpfile=$(mktemp -t "${0##*/}.XXXX")
trap 'rm -f "$tmpfile"' EXIT INT TERM

ret=0
for url; do
    http --check-status --ignore-stdin --timeout=2.5 --follow "$url" >"$tmpfile" || :

    url_title="$title"
    url_description="$description"
    if [ -s "$tmpfile" ]; then
        if [ -z "$url_title" ]; then
            url_title="$(cat "$tmpfile" | pup title 'text{}' | tr -d '\n')"
            if [ -z "$url_title" ]; then
                url_title="$url"
            fi
        fi

        if [ -z "$url_description" ]; then
            url_description="$(cat "$tmpfile" | pup 'meta[name="description"]' 'attr{content}')"
            if [ -z "$url_description" ]; then
                url_description="$(cat "$tmpfile" | pup 'meta[property="og:description"]' 'attr{content}')"
            fi
        fi
    elif [ -z "$url_title" ]; then
        url_title="$url"
    fi

    url_tags="$tags"
    if [ $add_recommended_tags -eq 1 ]; then
        recommended_tags="$(pin-cushion --format json posts/suggest --url "$url" | jq -r '.[0].recommended')" || :
        if [ "$recommended_tags" != null ]; then
            if [ -n "$url_tags" ]; then
                url_tags="$url_tags $recommended_tags"
            else
                url_tags="$recommended_tags"
            fi
        fi
    fi

    echo >&2 pin-cushion posts/add --url "$url" --replace no --tags "$url_tags" --description "$url_title" --extended "$url_description"
    pin-cushion posts/add --url "$url" --replace no --tags "$url_tags" --description "$url_title" --extended "$url_description" || ret=$?
done
exit $ret
