#!/usr/bin/env bash

PATH="$HOME/.local/bin:$HOME/bin:$PATH"

set -- \
    --archive \
    --human-readable \
    --hard-links \
    --compress \
    --exclude=.DS_Store \
    --exclude="._*" \
    --exclude=.Trash-1000 \
    --exclude=lost+found \
    --exclude="bgrm.*" \
    --delete \
    --delete-excluded

if [ -t 1 ]; then
    set -- --info=progress2 "$@"
fi

# Full local backup of the home directory, with a single copy, for device restoration
ret=0
echo >&2 "Backing up home directory to the SD card"
rsync "$@" --exclude-from="$HOME"/.config/rsync/exclude.txt --exclude=/.local/share/Steam/steamapps/ "$HOME"/ /run/media/deck/SD/Backup/home/ || ret=$?
echo >&2 "Backing up installed Steam Games to the SD card"
rsync "$@" --exclude-from="$HOME"/.config/rsync/exclude.txt "$HOME"/.local/share/Steam/steamapps/ /run/media/deck/SD/Backup/home/.local/share/Steam/steamapps/ || ret=$?
exit $ret
