Set Shell "zsh"
Set FontFamily "MesloLGS NF"
Set Padding 20
Set WindowBar Colorful
Set Theme { "name": "Vim Alabaster", "black": "#000000", "red": "#aa3731", "green": "#448c37", "yellow": "#cb9000", "blue": "#325cc0", "magenta": "#7a3e9d", "cyan": "#0083b2", "white": "#bbbbbb", "brightBlack": "#777777", "brightRed": "#f05050", "brightGreen": "#60cb00", "brightYellow": "#ffbc5d", "brightBlue": "#007acc", "brightMagenta": "#e64ce6", "brightCyan": "#00aacb", "brightWhite": "#ffffff", "background": "#fafafa", "foreground": "#000000", "selection": "#bfdbfe", "cursor": "#007acc" }
Env CLITHEME "light"
Env LANG "en_US.UTF-8"
