Set Shell "zsh"
Set FontFamily "MesloLGS NF"
Set WindowBar ""
Set Padding 0
Set Margin 0
Set MarginFill ""
Set BorderRadius 0
Set Theme { "name": "Dotfiles Vim Dracula 256", "black": "#21222c", "red": "#ff5555", "green": "#50fa7b", "yellow": "#f1fa8c", "blue": "#bd93f9", "magenta": "#ff79c6", "cyan": "#8be9fd", "white": "#f8f8f2", "brightBlack": "#6272a4", "brightRed": "#ff6e6e", "brightGreen": "#69ff94", "brightYellow": "#ffffa5", "brightBlue": "#d6acff", "brightMagenta": "#ff92df", "brightCyan": "#a4ffff", "brightWhite": "#ffffff", "background": "#303030", "foreground": "#f8f8f2", "selection": "#44475a", "cursor": "#f8f8f2" }
Set Width 800
Env CLITHEME "dark"
Env LANG "en_US.UTF-8"
