#!/bin/sh

set -eu

if [ $# -eq 0 ]; then
    asdf plugin-add
    exit $?
fi

plugin=$1
if [ $# -gt 1 ]; then
    asdf plugin-add "$@"
else
    plugin_line="$(asdf plugin-list-all \
        | grep "^$plugin " \
        | sed -e 's/^\*//')"
    if [ -z "$plugin_line" ]; then
        echo >&2 "Error determining url for $plugin, please specify"
        asdf plugin-add
    fi
    # shellcheck disable=SC2086
    asdf plugin-add $plugin_line
fi
