#!/bin/sh

set -eu

export ASDF_DATA_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}"
export ASDF_DIR="$ASDF_DATA_DIR"

PATH="$(dirname "$0"):$PATH"

usage() {
    cat >&2 <<END
    ${0##*/} [options] PLUGIN [VERSION]

    Options:

    -g    Set to the default global version
END
exit 2
}

global=
while getopts gh opt; do
    case "$opt" in
        g)
            global=1
            ;;
        \? | h)
            usage
            ;; esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

if [ $# -eq 0 ]; then
    asdf install
fi

plugin=$1

asdf update >/dev/null 2>&1

if [ ! -e "$ASDF_DATA_DIR/plugins/$plugin" ]; then
    asdf-plugin-add "$plugin"
else
    asdf plugin-update "$plugin" >/dev/null 2>&1
fi

if [ $# -lt 2 ]; then
    asdf-install-latest ${global:+-g} "$plugin"
else
    asdf install "$plugin" "$2"
fi
