#!/bin/sh

version_sort() {
    python3 -c 'import distutils.version,sys; versions=sys.stdin.readlines(); sversions=sorted(distutils.version.LooseVersion(v.rstrip()) for v in versions); print("\n".join(str(v) for v in sversions))'
}

version="$(asdf list-all "$1" | grep -E '^[0-9]*(\.[0-9]*(.[0-9]*)?)?$' | version_sort | tail -n 1)"
if [ -z "$version" ]; then
    echo >&2 "Error locating latest version for $1"
    exit 1
fi

echo >&2 "asdf-install-latest: installing version $version of $1"
exec asdf install "$1" "$version"
