#!/bin/sh

version_sort() {
    python3 -c 'import distutils.version,sys; versions=sys.stdin.readlines(); sversions=sorted(distutils.version.LooseVersion(v.rstrip()) for v in versions); print("\n".join(str(v) for v in sversions))'
}

usage() {
    cat >&2 <<END
    ${0##*/} [options] PLUGIN [VERSION]

    Options:

    -g    Set to the default global version
END
exit 2
}

global=0
while getopts gh opt; do
    case "$opt" in
        g)
            global=1
            ;;
        \? | h)
            usage
            ;; esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

version="$(asdf list-all "$1" | grep -E '^[0-9]*(\.[0-9]*(.[0-9]*)?)?$' | version_sort | tail -n 1)"
if [ -z "$version" ]; then
    echo >&2 "Error locating latest version for $1"
    exit 1
fi

echo >&2 "asdf-install-latest: installing version $version of $1"
asdf install "$1" "$version"

if [ $global -eq 1 ]; then
    asdf global "$1" "$version"
fi
