#!/bin/sh

set -e

# shellcheck source=./install-asdf
. "$(dirname "$0")/install-asdf"

if [ ! -e "$ASDF_DATA_DIR/plugins/nodejs" ]; then
    asdf-plugin-add "nodejs"
else
    asdf plugin-update "nodejs" >/dev/null 2>&1
fi

bash "$ASDF_DIR/plugins/nodejs/bin/import-release-team-keyring"
asdf-install -g nodejs
