#!/bin/sh

set -e

. $(dirname "$0")/install-erlang

ELIXIR_VERSION="${ELIXIR_VERSION:-$(asdf list-all elixir | grep -v rc | sort -nr | head -n 1)}" || exit $?

if [ ! -e $ASDF_DIR/installs/elixir/$ELIXIR_VERSION ]; then
    unset CFLAGS LDFLAGS

    if [ -e $ASDF_DIR/plugins/elixir ]; then
        asdf plugin-update elixir
    else
        asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
    fi
    asdf install elixir $ELIXIR_VERSION
fi
asdf global elixir $ELIXIR_VERSION
