#!/bin/sh
# ShellCheck is the only haskell tool I use, so cheat and avoid installing
# ghc.

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
mkdir -p "$XDG_DATA_HOME"

case "$(uname -s)" in
    Linux)
        curl -fsSL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz | tar -C "$XDG_DATA_HOME" -Jxf -
        ;;
    Darwin)
        curl -fsSL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz | tar -C "$XDG_DATA_HOME" -Jxf -
        ;;
    *)
        echo >&2 "ERROR: unhandled $(uname -s) OS for shellcheck installation"
        ;;
esac

if [ -e "$XDG_DATA_HOME/shellcheck-stable/shellcheck" ]; then
    mkdir -p "$XDG_DATA_HOME/../bin"
    rm -f "$XDG_DATA_HOME/../bin/shellcheck"
    ln -sf "$XDG_DATA_HOME/shellcheck-stable/shellcheck" "$XDG_DATA_HOME/../bin/shellcheck"
fi
