#!/bin/sh

XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
ULUA_HOME="${ULUA_HOME:-${XDG_DATA_HOME}/ulua}"
mkdir -p "$ULUA_HOME"

tempdir="$(mktemp -d -t "${0##*/}.XXXXXX")" || exit 1
curl -fsSL -o "$tempdir/ulua-latest.zip" "http://ulua.io/download/ulua~latest.zip"
unzip -d "$tempdir" "$tempdir/ulua-latest.zip"
cp -a "$tempdir/ulua/." "$ULUA_HOME/"

BIT="$(test "$(uname -m)" = "x86_64" && echo "64" || echo "32")"
for p in "$ULUA_HOME/lua"* "$ULUA_HOME/bin/"*; do
    dest="$XDG_DATA_HOME/../bin/$(basename "$p")"
    rm -f "$dest"
    cat >"$dest" <<END
#!/bin/sh
export BIT=$BIT
exec "$p" "\$@"
END
    chmod +x "$dest"
    if [ "$BIT" = 64 ]; then
        rm -f "${dest}32"
        cat >"${dest}32" <<END
#!/bin/sh
export BIT=32
exec "$p" "\$@"
END
        chmod +x "${dest}32"
    fi
done
