#!/bin/sh

pythonuserdir="$(python -c 'import site; print(site.getuserbase())')" || exit 1
PATH="$pythonuserdir/bin:$(dirname "$0"):$HOME/.local/bin:$PATH"

pipv () {
    kpipsi upgrade "$@" || kpipsi install "$@" || { echo >&2 Error installing $@; return 1; }
}

pipv3 () {
    kpipsi -3 upgrade "$@" || kpipsi -3 install "$@" || { echo >&2 Error installing $@; return 1; }
}

pip_install () {
    command pip install --user --disable-pip-version-check -U "$@" || { echo >&2 Error installing $@; return 1; }
}

pip3_install () {
    command pip3 install --user --disable-pip-version-check -U "$@" || { echo >&2 Error installing $@; return 1; }
}

setup_pip () {
    if ! which pip >/dev/null 2>&1; then
        python -m ensurepip --user
        python -m pip install --user --upgrade pip
        python -m pip install --user --upgrade virtualenv
    fi
    if which python3 >/dev/null 2>&1 && ! which pip3 >/dev/null 2>&1; then
        python3 -m ensurepip --user
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user --upgrade virtualenv
    fi
}

if which pyenv >/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

setup_pip

## Pipsi
install-pipsi

## Interactive mode python tools
pip_install see
pip3_install see

## General Tools & Utilities
brew install the_silver_searcher
brew install gnu-sed
brew install jq
go get -u github.com/junegunn/fzf/... # or brew install fzf
cargov fd-find
cargov ripgrep
cargov bat
cargov tldr
go get -u github.com/edi9999/path-extractor/path-extractor

pipv mercurial gitifyhg hg-git hg-evolve

pipv pythonpy
pipv3 httpie
go get -u github.com/EricChiang/pup # or brew install pup
pip_install hg-git
pipv git-remote-dropbox

# Very handy for screencasts
pipv3 asciinema

## For dotfiles
pipv3 peru
pipv3 pygments pygments_base16

## Handy
go get -u github.com/direnv/direnv

## Script dependencies
pip_install SOAPpy # lmwsaction
pip_install dropbox # git-remote-dropbox
pip_install titlecase # variety of scripts, and zsh alias
pip_install toml # toml-set/toml-get, used by the game scripts
pip3_install toml # toml-set/toml-get, used by the game scripts
pip_install sh # various scripts
pip_install hungarian # git-tbdiff
pipv json2yaml # pcposts zsh function
pip_install gitpython # buildhistory-diff

## Pinboard client
#npmv pin-cushion

## Development Tools
go get -u github.com/github/hub
if which brew >/dev/null 2>&1; then
    : ${HOMEBREW_PREFIX:=/opt/homebrew}
    $HOMEBREW_PREFIX/bin/brew install openssl
    OPENSSL_DIR=$HOMEBREW_PREFIX/opt/openssl cargov git-series
else
    cargov git-series
fi
# pprintpp + pp-ez?
# twine?
# wheel?
#pip_install ptpython
pip_install pathlib2
pip_install click
pip_install e
pip3_install e
pip_install better-exceptions-hook
pip3_install better-exceptions-hook

## Documentation
gemv ronn
#npmv doctoc

## Linting / Static Analysis
cabalv shellcheck
pipv flake8 flake8 pep8-naming flake8-docstrings
#pipv prospector
#pipv vim-vint
#luav luacheck
#gemv mdl # markdown
# see also markdownlint
# http://lua-users.org/wiki/LuaInspect ?
# https://code.google.com/archive/p/lua-checker/ ?
# go get github.com/BurntSushi/toml/cmd/tomlv # for toml, but it's out of date. it only supports 0.1.0

## Formatters
pipv3 yapf
# autopep8 - format code per pep8
# https://pypi.python.org/pypi/docformatter - format docstrings per pep257
go get -u github.com/shurcooL/markdownfmt
#npmv pretty-js
#luav formatter

## As Needed

#go get -u github.com/ddo/fast # bandwidth speed testing
#go get -u github.com/jbenet/go-multihash/multihash # If needed to create a hash for use by hashpipe
#go get -u github.com/jbenet/hashpipe
#pipv pockyt # cli for Pocket
#pipv pocket-cli # other cli for Pocket, better interface
#pip_install datefinder # search text for dates, ala path-extractor
#pip_install pipdeptree
#go get -u github.com/pengwynn/flint # check for missing license/etc for a project
# Seemingly no cli install for: terra (terralang.org)

### Elixir Development
# erlang is specifically listed to ensure its binaries are symlinked as well
# as the elixir binaries, so erl is available
#brewv elixir elixir erlang

### Lua Development
# luvi?
#luav moonscript
#luav busted

### StackOverflow from the commandline
#npmv how2

### Video Downloading
#pipv3 youtube-dl

# Dropblame, constructs git history for individual files in dropbox, using
# dropbox's revision history.
#XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
#WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"
#pipv dropblame &&
#    mv "$WORKON_HOME/dropblame/bin/drop" "$WORKON_HOME/dropblame/bin/dropb" && \
#    mv "$XDG_DATA_HOME/../bin/drop" "$XDG_DATA_HOME/../bin/dropb"
