#!/bin/sh

XDG_DATA_HOME="${XDG_DATA_HOME:-~/.local/share}"
PIPX_HOME="${PIPX_HOME:-${XDG_DATA_HOME:-~/.local/share}/../pipx/venvs}"

python3 -m ensurepip --user --upgrade
python3 -m venv "$PIPX_HOME/pipx"

(
    . "$PIPX_HOME/pipx/bin/activate"
    python3 -m pip install --disable-pip-version-check pipx
)
pipx install --force pipx

mkdir -p "$XDG_DATA_HOME/../bin"
ln -sf "$PIPX_HOME/pipx/bin/pipx" "$XDG_DATA_HOME/../bin"
