#!/bin/sh

set -e

GOLANG_VERSION=1.11.2

. $(dirname "$0")/install-asdf

if [ ! -e $ASDF_DIR/installs/golang/$GOLANG_VERSION ]; then
    unset CFLAGS LDFLAGS

    if [ -e $ASDF_DIR/plugins/golang ]; then
        asdf plugin-update golang
    else
        asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    fi
    asdf install golang $GOLANG_VERSION
fi
asdf global golang $GOLANG_VERSION
