#!/bin/sh

: "${XDG_DATA_HOME:=$HOME/.local/share}"
export NVM_DIR="$XDG_DATA_HOME/nvm" && (
    git clone https://github.com/creationix/nvm.git "$NVM_DIR"
    cd "$NVM_DIR"
    git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" origin)"
) && \. "$NVM_DIR/nvm.sh"
nvm install ${NODE_VERSION:---lts}
if [ -n "$NODE_VERSION" ]; then
    nvm use --delete-prefix $NODE_VERSION --silent
    nvm alias default $NODE_VERSION
else
    nvm alias default node
fi
