#!/bin/sh

PY2_VERSION=2.7.15
PY3_VERSION=3.7.1

# Ensure we can run llvm-profdata on FreeBSD
for llvmdir in /usr/local/llvm*/bin; do
    if [ -d "$llvmdir" ]; then
        PATH="$PATH:$llvmdir"
    fi
done

export PYTHONNOUSERSITE=1
export CFLAGS="${CFLAGS--O2}"
export LDFLAGS

case "$OSTYPE" in
    darwin*)
        if which brew >/dev/null 2>&1; then
            eval "$(brew environment --shell=auto | grep -vw PATH)"
            CFLAGS="$CFLAGS -I$(brew --prefix sqlite)/include -I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include"
            LDFLAGS="$LDFLAGS -L$(brew --prefix sqlite)/lib -L$(brew --prefix openssl)/lib"
        fi
        ;;
esac

export PYENV_ROOT="${1:-${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}}"
PATH="$(dirname "$0"):$PYENV_ROOT/bin:$HOME/.local/bin:$PATH"

if [ -z "$CONFIGURE_OPTS" ] && [ -z "$PYTHON_CONFIGURE_OPTS" ]; then
    export PYTHON_CONFIGURE_OPTS="\
        --enable-shared \
        --with-system-expat \
        --with-system-zlib \
        --with-lto \
        --enable-loadable-sqlite-extensions \
    "
    no_pgo=0
    if [ "$OSTYPE" = linux-gnu ]; then
        case "$(uname -r)" in
            *-Microsoft)
                # WSL. test_ssl keeps hanging indefinitely
                no_pgo=1
                ;;
        esac
    fi
    if [ $no_pgo -eq 0 ]; then
        PYTHON_CONFIGURE_OPTS="$PYTHON_CONFIGURE_OPTS --enable-optimizations"
    fi
fi

pyenv-installer

if [ "$2" = "-f" ]; then
    rm -rf "$PYENV_ROOT/versions/$PY2_VERSION"
fi
pyenv install -v $PY2_VERSION && \
pyenv global $PY2_VERSION

if [ "$2" = "-f" ]; then
    rm -rf "$PYENV_ROOT/versions/$PY3_VERSION"
fi
pyenv install -v $PY3_VERSION && \
pyenv global $PY2_VERSION $PY3_VERSION

# At this point python is python2, and python2 and python3 work as expected,
# but python tools run with these pythons will have that python install first
# in the PATH. In the case of python3, this means in that process, 'python'
# will now correspond to python3, which will not do (see bitbake).
if [ -e "$PYENV_ROOT/versions/$PY3_VERSION" ]; then
    rm -f "$PYENV_ROOT/versions/$PY3_VERSION/bin/python"
fi
