#!/bin/sh

PY2_VERSION=2.7.16
PY3_VERSION=3.7.3

export PYENV_ROOT="${1:-${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}}"
PATH="$(dirname "$0"):$PYENV_ROOT/bin:$PYENV_ROOT/shims:$HOME/.local/bin:$PATH"

if [ ! -e "$PYENV_ROOT/bin" ]; then
    pyenvk installer || rm -rf "${PYENV_ROOT:?}/bin"
fi

if [ "$2" = "-f" ]; then
    rm -rf "$PYENV_ROOT/versions/$PY2_VERSION"
fi
pyenvk install -v $PY2_VERSION && \
pyenv global $PY2_VERSION

if [ "$2" = "-f" ]; then
    rm -rf "$PYENV_ROOT/versions/$PY3_VERSION"
fi
pyenvk install -v $PY3_VERSION && \
pyenv global $PY2_VERSION $PY3_VERSION

# At this point python is python2, and python2 and python3 work as expected,
# but python tools run with these pythons will have that python install first
# in the PATH. In the case of python3, this means in that process, 'python'
# will now correspond to python3, which will not do (see bitbake).
if [ -e "$PYENV_ROOT/versions/$PY3_VERSION" ]; then
    rm -f "$PYENV_ROOT/versions/$PY3_VERSION/bin/python"
fi
