#!/bin/sh

case $OSTYPE in
    Darwin*)
        PATH=/usr/bin:/bin
        ;;
esac

PIPSI_HOME="${PIPSI_HOME:-${XDG_DATA_HOME:-~/.local/share}/pipsi}"
if ! [ -e "$PIPSI_HOME/pipsi/bin/pipsi" ]; then
    python2 -m pip install --user virtualenv
    virtualenv "$PIPSI_HOME/pipsi" || exit 1
fi
. "$PIPSI_HOME/pipsi/bin/activate"
python2 -m pip install -U pipsi
XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
mkdir -p "$XDG_DATA_HOME/../bin"
ln -sf "$PIPSI_HOME/pipsi/bin/pipsi" "$XDG_DATA_HOME/../bin/pipsi"
