#!/bin/sh

# Install needed deps
if command -v pacman >/dev/null 2>&1; then
    sudo pacman -Sy --needed openssl openssl-1.0 bzip2 sqlite ncurses unzip
elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get -y install libssl-dev libbz2-dev libsqlite3-dev libncurses5-dev unzip
elif command -v brew >/dev/null 2>&1; then
    brew install openssl bzip2 sqlite3 ncurses unzip
fi

# shellcheck source=./install-asdf
. "$(dirname "$0")/install-asdf"
for i in golang ruby nodejs rust haskell; do
    asdf-install -g "$i"
done
install-cabal
install-python-asdf
install-pipsi
install-pipx

# TODO: remove the packages we installed, but not the ones the user did
