#!/bin/sh

PY2_VERSION=2.7.15
PY3_VERSION=3.6.6

export PYENV_ROOT="${1:-${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}}"
PATH="$(dirname "$0"):$PYENV_ROOT/bin:$HOME/.local/bin:$PATH"

export PYTHONNOUSERSITE=1
export CFLAGS="${CFLAGS--O2}"
if [ -z "$CONFIGURE_OPTS" ] && [ -z "$PYTHON_CONFIGURE_OPTS" ]; then
    export PYTHON_CONFIGURE_OPTS="\
        --enable-shared \
        --with-system-expat \
        --with-system-zlib \
        --enable-optimizations \
        --with-lto \
        --enable-loadable-sqlite-extensions \
    "
fi

pyenv-installer
eval "$(pyenv init -)"

case "$OSTYPE" in
    darwin*)
        eval "$(brew environment --shell=auto)"
        ;;
esac

pyenv install -v $PY2_VERSION
pyenv global $PY2_VERSION
pyenv install -v $PY3_VERSION
pyenv global $PY2_VERSION $PY3_VERSION

# At this point python is python2, and python2 and python3 work as expected,
# but python tools run with these pythons will have that python install first
# in the PATH. In the case of python3, this means in that process, 'python'
# will now correspond to python3, which will not do (see bitbake).
if [ -e "$PYENV_ROOT/versions/$PY3_VERSION" ]; then
    rm -f "$PYENV_ROOT/versions/$PY3_VERSION/bin/python"
fi
