#!/bin/sh

# Install needed deps
sudo pacman -Sy --needed openssl bzip2 sqlite ncurses unzip
sudo apt-get -y install libssl-dev libbz2-dev libsqlite3-dev libncurses5-dev unzip
brew install openssl bzip2 sqlite3 ncurses unzip

# shellcheck source=./install-asdf
. "$(dirname "$0")/install-asdf"
for i in golang ruby nodejs rust haskell; do
    asdf-install -g "$i"
done
install-python-asdf
install-cabal
install-pipsi

# TODO: remove the packages we installed, but not the ones the user did
