#!/bin/sh

set -e

KERL_CONFIGURE_OPTIONS="--disable-debug --disable-silent-rules --without-javac --enable-shared-zlib --enable-dynamic-ssl-lib --enable-shared-zlib --enable-hipe --enable-sctp --enable-smp-support --enable-threads --enable-kernel-poll --enable-wx"
case "$OSTYPE" in
    darwin*)
        KERL_CONFIGURE_OPTIONS="$KERL_CONFIGURE_OPTIONS --with-ssl=$(brew --prefix openssl) --enable-darwin-64bit"
        ;;
esac
#export KERL_BUILD_DOCS=yes

. $(dirname "$0")/install-asdf

ERLANG_VERSION="${ERLANG_VERSION:-$(asdf list-all erlang | grep -v rc | sort -nr | head -n 1)}" || exit $?

if [ ! -e $ASDF_DIR/installs/erlang/$ERLANG_VERSION ]; then
    unset CFLAGS LDFLAGS
    export KERL_CONFIGURE_OPTIONS

    if [ -e $ASDF_DIR/plugins/erlang ]; then
        asdf plugin-update erlang
    else
        asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
    fi

    # Building with a newer kerl:
    #    export KERL_BASE_DIR="$ASDF_DIR/plugins/erlang/kerl-home/"
    #    export KERL_BUILD_BACKEND=git
    #    curl -o kerl https://raw.githubusercontent.com/kerl/kerl/master/kerl
    #    chmod +x kerl
    #    ./kerl build $ERLANG_VERSION asdf_$ERLANG_VERSION
    #    ./kerl install asdf_$ERLANG_VERSION ~/.asdf/installs/erlang/$ERLANG_VERSION/
    asdf install erlang $ERLANG_VERSION
fi
asdf global erlang $ERLANG_VERSION
