#!/bin/sh

set -e

version_sort() {
    sort -V
    # if command -v python3; then
    #     python3 -c 'import distutils.version,sys; versions=sys.stdin.readlines(); sversions=sorted(distutils.version.LooseVersion(v.rstrip()) for v in versions); print("\n".join(str(v) for v in sversions))'
    # elif command -v gsort; then
    #     gsort -V
    # else
    #     sort -V
    # fi
}

# shellcheck source=./install-asdf
. "$(dirname "$0")/install-asdf"

if [ ! -e "$ASDF_DATA_DIR/plugins/haskell" ]; then
    asdf-plugin-add "haskell"
else
    asdf plugin-update "haskell" >/dev/null 2>&1
fi

HASKELL_VERSION="$(asdf list-all haskell | grep -E '^[0-9]*\.[0-9]*(\.[0-9]*)?$' | grep -v 8.8 | version_sort | tail -n 1)"
asdf-install -g haskell "$HASKELL_VERSION"
