#!/bin/sh

export XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
export CFLAGS="${CFLAGS--O2}"
export LDFLAGS

# Shut up 2.7 deprecation warning
export PYTHONWARNINGS=ignore:DEPRECATION

# shellcheck disable=SC2039
case "$OSTYPE" in
    darwin*)
        if command -v brew >/dev/null 2>&1; then
            eval "$(brew environment --shell=auto | grep -vw PATH)"
            CFLAGS="$CFLAGS -I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include"
            LDFLAGS="$LDFLAGS -L$(brew --prefix openssl)/lib"
            : "${HOMEBREW_PREFIX:=/opt/homebrew}"
            export OPENSSL_DIR="$HOMEBREW_PREFIX/opt/openssl"
        fi
        ;;
    *)

        if command -v brew >/dev/null 2>&1; then
            brew unlink pkg-config >/dev/null 2>&1 || :
        fi
        ;;
esac

pythonuserdir="$(python3 -c 'import site; print(site.getuserbase())')" || exit 1
PATH="$pythonuserdir/bin:$(dirname "$0"):$HOME/.local/bin:$PATH"
cd /


pipx_installed () {
    pipx list | sed -n -e 's/^   *package \([^ ]*\).*/\1/p' | grep -Fqx "$1"
}

pipx () {
    if [ $has_python3 -eq 1 ]; then
        pipx-install "$@"
    fi
}

pip3_install () {
    if [ $has_python3 -eq 1 ]; then
        command python3 -m pip -q install --user -U "$@" || { echo >&2 "Error installing $*"; return 1; }
    fi
}

if command -v python3 >/dev/null 2>&1; then
    has_python3=1
else
    has_python3=0
fi

export PIP_REQUIRE_VIRTUALENV=

mkdir -p "$XDG_DATA_HOME"

# Clang and llvm are needed to build `bat`
if command -v pacman >/dev/null 2>&1; then
    sudo pacman -S --needed llvm clang cmake pkg-config
elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get -y install --no-upgrade llvm clang cmake pkg-config
fi

export CARGO_INSTALL_ROOT=${CARGO_INSTALL_ROOT:-$XDG_DATA_HOME/..}
cargo install fd-find ripgrep bat exa git-delta git-series
cargo install --git https://github.com/jez/as-tree

# Upgrade pip
pip3_install pip

## Interactive mode python tools
#pip3_install see

## General Tools & Utilities
go get -u github.com/junegunn/fzf/...
pipx httpie
go get -u github.com/EricChiang/pup

# Very handy for screencasts
pipx asciinema

## For dotfiles
pipx peru

## Handy
go get -u github.com/direnv/direnv

## Script dependencies
go get -u github.com/tomnomnom/unfurl

## Pinboard client
#npmv pin-cushion
#pipx python-json2yaml # pcposts zsh function

## Development Tools
go get -u github.com/github/hub
pipx git+https://github.com/kergoth/git-imerge@no-completions-in-setup
pipx git-revise
go get -u github.com/x-motemen/ghq
# pprintpp + pp-ez?
# twine?
# wheel?
#pip3_install e

## Documentation
#gemv ronn
#npmv doctoc

## Formatters
GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
go get -u github.com/shurcooL/markdownfmt
# autopep8 - format code per pep8
# https://pypi.python.org/pypi/docformatter - format docstrings per pep257
#npmv pretty-js
#luav formatter

## Linting / Static Analysis
pipx flake8 pep8-naming flake8-docstrings

# ShellCheck is the only haskell tool I use, so cheat and avoid installing
# ghc.
case "$(uname -s)" in
    Linux)
        curl -fsSL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz | tar -C ~/.local/share -Jxf -
        ;;
    Darwin)
        curl -fsSL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz | tar -C ~/.local/share -Jxf -
        ;;
    *)
        echo >&2 "ERROR: unhandled $(uname -s) OS for shellcheck installation"
        ;;
esac
if [ -e "$XDG_DATA_HOME/shellcheck-stable/shellcheck" ]; then
    mkdir -p "$XDG_DATA_HOME/../bin"
    rm -f "$XDG_DATA_HOME/../bin/shellcheck"
    ln -sf "$XDG_DATA_HOME/shellcheck-stable/shellcheck" "$XDG_DATA_HOME/../bin/shellcheck"
fi

#luav luacheck
#gemv mdl # markdown
# see also markdownlint
# http://lua-users.org/wiki/LuaInspect ?
# https://code.google.com/archive/p/lua-checker/ ?
# go get github.com/BurntSushi/toml/cmd/tomlv # for toml, but it's out of date. it only supports 0.1.0

## As Needed

# cargo install --git https://github.com/pkolaczk/fclones # find duplicate files
# cargo install sd
# cargo install --locked --all-features --git https://github.com/ms-jpq/sad --branch senpai
#go get -u github.com/ddo/fast # bandwidth speed testing
#go get -u github.com/jbenet/go-multihash/multihash # If needed to create a hash for use by hashpipe
#go get -u github.com/jbenet/hashpipe
#go get -u github.com/pengwynn/flint # check for missing license/etc for a project
# Seemingly no cli install for: terra (terralang.org)

# cha(rs) is a commandline tool to display information about unicode characters
#   https://github.com/antifuchs/chars
#cargo install chars

# A more intuitive version of du in rust
#   https://github.com/bootandy/dust
#cargo install du-dust

# a calculator REPL, similar to bc(1)
#   https://github.com/NerdyPepper/eva
#cargo install eva

### Lua Development
#luav moonscript
#luav busted

### StackOverflow from the commandline
#npmv how2

### Video Downloading
#pipx youtube-dl
