#!/bin/sh

set -eu

usage () {
    echo >&2 "${0##*/} [-h|-s|-r INSTALL_REPO_PATH] INSTALL_PATH"
    echo >&2
    echo >&2 "Install homebrew to the specified INSTALL_PATH"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -r INSTALL_REPO_PATH Destination of the homebrew repo when using -s. Default: INSTALL_PATH/homebrew"
    echo >&2 "  -s    Separate the prefix and repo."
    echo >&2 "  -S    Use shallow clones."
    echo >&2 "  -h    Show this help."
    exit 2
}

HOMEBREW_REPO=
separate_prefix=0
shallow=
while getopts sSr:h opt; do
    case "$opt" in
        s)
            separate_prefix=1
            ;;
        S)
            shallow=1
            ;;
        r)
            HOMEBREW_REPO="$OPTARG"
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -gt 1 ]; then
    usage
fi

HOMEBREW_PREFIX="${1:-$HOMEBREW_PREFIX}"
if [ -z "$HOMEBREW_PREFIX" ]; then
    usage
fi

PATH="$HOMEBREW_PREFIX/bin:$PATH"

if [ $separate_prefix -eq 1 ]; then
    mkdir -p "$HOMEBREW_PREFIX"
    if [ -z "$HOMEBREW_REPO" ]; then
        HOMEBREW_REPO="$HOMEBREW_PREFIX/brew"
    fi
else
    HOMEBREW_REPO="$HOMEBREW_PREFIX"
fi

git clone ${shallow:+--depth 1} https://github.com/homebrew/brew "$HOMEBREW_REPO"
git config -f "$HOMEBREW_REPO/.git/config" homebrew.analyticsdisabled true
git clone ${shallow:+--depth 1} https://github.com/homebrew/homebrew-core "$HOMEBREW_REPO/Library/Taps/homebrew/homebrew-core"

HOMEBREW_PREFIX="$(cd "$HOMEBREW_PREFIX" && pwd -P)"
if [ "$separate_prefix" -eq 1 ]; then
    HOMEBREW_REPO="$(cd "$HOMEBREW_REPO" && pwd -P)"
    mkdir -p "$HOMEBREW_PREFIX/bin"
    if command -v lnr >/dev/null 2>&1; then
        lnr "$HOMEBREW_REPO/bin/brew" "$HOMEBREW_PREFIX/bin/brew"
    else
        ln -sf "$HOMEBREW_REPO/bin/brew" "$HOMEBREW_PREFIX/bin/brew"
    fi
fi

if [ "$(brew --prefix)" != "$HOMEBREW_PREFIX" ]; then
    printf >&2 "Error: brew prefix %s does not match the specified %s" "$(brew --prefix)" "$HOMEBREW_PREFIX"
    exit 1
fi

if [ "$(brew --repo)" != "$HOMEBREW_REPO" ]; then
    printf >&2 "Error: brew repo %s does not match the specified %s" "$(brew --repo)" "$HOMEBREW_REPO"
    exit 1
fi

if [ -d "$HOMEBREW_PREFIX/share/doc/homebrew" ]; then
    rm -rf "$HOMEBREW_PREFIX/share/doc/homebrew"
fi

for dir in etc include lib opt sbin share var/homebrew/linked Cellar Frameworks; do
    mkdir -p "$HOMEBREW_PREFIX/$dir"
    chown -R "$(whoami)" "$HOMEBREW_PREFIX/$dir"
done

brew update || exit 2
brew doctor || exit 0
