#!/bin/sh

set -e

export CFLAGS="${CFLAGS--O2}"
export LDFLAGS

case "$OSTYPE" in
    darwin*)
        if which brew >/dev/null 2>&1; then
            eval "$(brew environment --shell=auto | grep -vw PATH)"
            CFLAGS="$CFLAGS -I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include"
            LDFLAGS="$LDFLAGS -L$(brew --prefix openssl)/lib"
        fi
        ;;
esac

# if [ -z "$CONFIGURE_OPTS" ] && [ -z "$RUBY_CONFIGURE_OPTS" ]; then
#     export RUBY_CONFIGURE_OPTS="\
#         --enable-shared \
#         "--with-readline-dir=/usr/lib" \
#         "--with-openssl-dir=/usr/lib" \
#     "
# fi

. "$(dirname "$0")/install-asdf"

RUBY_VERSION="${RUBY_VERSION:-$(asdf list-all ruby | grep '^[0-9]' | grep -Ev '\-p|rc|dev' | sort -rn | head -n 1)}"

if [ ! -e "$ASDF_DIR/installs/ruby/$RUBY_VERSION" ]; then
    if [ -e "$ASDF_DIR/plugins/ruby" ]; then
        asdf plugin-update ruby
    else
        asdf plugin-list-all | grep '^ruby ' | while read -r name url; do asdf plugin-add "$name" "$url"; done
    fi

    asdf install ruby "$RUBY_VERSION"
fi
asdf global ruby "$RUBY_VERSION"
