#!/bin/sh

XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
ULUA_HOME="${ULUA_HOME:-${XDG_DATA_HOME}/ulua}"
mkdir -p "$ULUA_HOME"

tempdir="$(mktemp -d -t "${0##*/}.XXXXXX")" || exit 1
curl -fsSL -o "$tempdir/ulua-latest.zip" "http://ulua.io/download/ulua~latest.zip"
unzip -d "$tempdir" "$tempdir/ulua-latest.zip"
cp -a "$tempdir/ulua/." "$ULUA_HOME/"

BIT="$(test "$(uname -m)" = "x86_64" && echo "64" || echo "32")"
for p in "$ULUA_HOME/lua"* "$ULUA_HOME/bin/"*; do
    rm -f "$XDG_DATA_HOME/../bin/$(basename "$p")"
    cat >"$XDG_DATA_HOME/../bin/$(basename "$p")" <<END
#!/bin/sh
export BIT=$BIT
exec "$p" "\$@"
END
    chmod +x "$XDG_DATA_HOME/../bin/$(basename "$p")"
done
