#!/bin/sh

set -e

# Ensure we can run llvm-profdata on FreeBSD
for llvmdir in /usr/local/llvm*/bin; do
    if [ -d "$llvmdir" ]; then
        PATH="$PATH:$llvmdir"
    fi
done

export PYTHONNOUSERSITE=1
export CFLAGS="${CFLAGS--O2}"
export LDFLAGS

case "$OSTYPE" in
    darwin*)
        if which brew >/dev/null 2>&1; then
            eval "$(brew environment --shell=auto | grep -vw PATH)"
            CFLAGS="$CFLAGS -I$(brew --prefix sqlite)/include -I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include"
            LDFLAGS="$LDFLAGS -L$(brew --prefix sqlite)/lib -L$(brew --prefix openssl)/lib"
        fi
        ;;
esac

export PYENV_ROOT="${1:-${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}}"
PATH="$(dirname "$0"):$PYENV_ROOT/bin:$HOME/.local/bin:$PATH"

if [ -z "$CONFIGURE_OPTS" ] && [ -z "$PYTHON_CONFIGURE_OPTS" ]; then
    export PYTHON_CONFIGURE_OPTS="\
        --enable-shared \
        --with-system-expat \
        --with-system-zlib \
        --with-lto \
        --enable-loadable-sqlite-extensions \
    "
    no_pgo=0
    if [ "$OSTYPE" = linux-gnu ]; then
        case "$(uname -r)" in
            *-Microsoft)
                # WSL. test_ssl keeps hanging indefinitely
                no_pgo=1
                ;;
        esac
    elif [ "$(uname -s)" = FreeBSD ]; then
        no_pgo=1
        export PYTHON_CONFIGURE_OPTS="\
            --enable-shared \
            --with-system-expat \
            --with-system-zlib \
            --enable-loadable-sqlite-extensions \
        "
    fi
    if [ $no_pgo -eq 0 ]; then
        PYTHON_CONFIGURE_OPTS="$PYTHON_CONFIGURE_OPTS --enable-optimizations"
    fi
fi

pyenv install "$@"
