#!/bin/sh
# shellcheck disable=SC2039

set -eu

if [ "$OSTYPE" = linux-gnu ]; then
    case "$(uname -r)" in
        *-Microsoft)
            OSTYPE=WSL
            ;;
    esac
fi

modules="PowerShellGet PSReadLine Recycle BurntToast ZLocation posh-alias"
cmds="powershell pwsh"
if [ "$OSTYPE" = WSL ]; then
    cmds="$cmds powershell.exe pwsh.exe"
fi
for cmd in $cmds; do
    if command -v "$cmd" >/dev/null 2>&1; then
        "$cmd" -NoProfile -Command "Install-PackageProvider -Name NuGet -Scope CurrentUser" >/dev/null 2>&1 || :
        for module in $modules; do
            if ! "$cmd" -NoProfile -Command "Import-Module '$module'" >/dev/null 2>&1; then
                if ! "$cmd" -NoProfile -Command "Install-Module -Name '$module' -Scope CurrentUser -Confirm"; then
                    echo >&2 "Error installing powershell module $module for $cmd"
                fi
            fi
        done
    fi
done
