#!/bin/sh

if [ $# -ne 0 ]; then
    HOMEBREW_PATH="$1"
else
    HOMEBREW_PATH="${HOMEBREW_PATH:-${HOMEBREW_PREFIX:-/opt/homebrew}}"
fi
PATH="$HOMEBREW_PATH/bin:$(dirname "$0"):$PATH"

if [ ! -e "$HOMEBREW_PATH" ]; then
    sudo mkdir -p "$HOMEBREW_PATH" && \
        sudo chown $USER "$HOMEBREW_PATH" && \
            install-brew "$HOMEBREW_PATH"
    brew doctor || exit 1
fi

# Ensure that pbcopy/pbpaste work from tmux, etc
$HOMEBREW_PATH/bin/brew install reattach-to-user-namespace --with-wrap-pbcopy-and-pbpaste

brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/games
brew tap homebrew/head-only
brew tap homebrew/python
brew tap monochromegane/pt

brew install zsh
brew install the_silver_searcher
brew install mercurial git
brew install wget
brew install trash
brew install tag
brew install jq pup
brew install p7zip
brew install sshuttle

# Gaming
brew install dylibbundler makeicns icoutils
brew install --HEAD innoextract

# For brew-cask
brew install caskroom/cask/brew-cask
brew tap caskroom/fonts
brew tap caskroom/unofficial
brew tap caskroom/versions

# For 'att'
brew install dtach dvtm
