#!/bin/sh
#
# Sets reasonable OS X defaults.
#
# Pulled from https://github.com/holman/dotfiles
#
# The original idea (and a couple settings) were grabbed from:
#   https://github.com/mathiasbynens/dotfiles/blob/master/.osx

PATH="$(dirname "$0"):$PATH"

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Expand the save dialog by default in all applications
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true

# Disable press-and-hold for keys in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Use AirDrop over every interface. srsly this should be a default.
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1

# Stop full names from copying with email addresses in Mail.app
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# Always open everything in Finder's list view. This is important.
defaults write com.apple.finder FXPreferredViewStyle Nlsv

# Enable quit menu item for Finder
defaults write com.apple.finder QuitMenuItem -bool true

# Enable text selection in quick look windows
defaults write com.apple.finder QLEnableTextSelection -bool true

# Hide desktop icons completely
defaults write com.apple.finder CreateDesktop -bool false

# Remove autohide dock delay
defaults write com.apple.dock autohide-delay -float 0

# Speed up mission control animations
defaults write com.apple.dock expose-animation-duration -float 0.12

# Make hidden dock icons translucent
defaults write com.apple.dock showhidden -bool true

defaults write com.apple.iTunes allow-half-stars -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Show system info at the login screen
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Kill Skype's splash screen
defaults write com.skype.skype SKShowSplash NO

# Only show terminal scrollbars when scrolling
defaults write com.apple.Terminal AppleShowScrollBars -string WhenScrolling

sudo sh -c "echo kern.sysv.shmall=65536 >>/etc/sysctl.conf"
sudo sh -c "echo kern.sysv.shmmax=16777216 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfiles=10485760 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfilesperproc=1048576 >>/etc/sysctl.conf"
sudo sh -c "sort -u /etc/sysctl.conf >/tmp/foo && mv /tmp/foo /etc/sysctl.conf"
sudo sysctl -w $(cat /etc/sysctl.conf)

killall Finder
killall Dock

sudo mkdir -p /usr/local /opt
sudo chgrp -R staff /usr/local /opt
sudo find /usr/local /opt -type d -exec chmod g+wXs "{}" \;
sudo find /usr/local /opt -not -type d -exec chmod g+wX "{}" \;

$(dirname "$0")/setup-brew-system

chsh -s /opt/homebrew/bin/zsh

# launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
