#!/bin/sh

pythonuserdir="$(python -c 'import site; print(site.getuserbase())')" || exit 1
PATH="$pythonuserdir/bin:$PATH"

if ! which pip >/dev/null 2>&1; then
    # Install pip (and setuptools if needed)
    curl https://bootstrap.pypa.io/get-pip.py | python - --user
    if ! which pip >/dev/null 2>&1; then
        echo >&2 "Error: after installing pip, we are not able to execute it"
        exit 2
    fi
fi

# Install basic python development tools
pip install --user wheel twine virtualenv flake8 autopep8

# Convenient pretty-printing
pip install --user pprintpp pp-ez

# For ebook processing
pip install --user titlecase

# For a number of little scripts I use
pip install --user sh

# For lmwsaction
pip install --user SOAPpy

# So we can clone git repositories with mercurial
ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future" pip install --user hg-git

# For git-remote-dropbox
pip install --user dropbox

# Other useful bits I don't need installed right now
#pip install --user pip-tools
#pip install --user tox
#pip install --user stormssh
#pip install --user dash.py doc2dash
#pip install --user pylint
