#!/bin/sh

export TERMINAL=st
export DISPLAY="${DISPLAY:-:0.0}"
export LIBGL_ALWAYS_INDIRECT=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-${XDG_DATA_HOME:-$HOME/.local/share}}"
PATH="$(dirname "$(readlink -f "$0")")/scripts:$HOME/.local/bin:$PATH"

# Ensure we can use pyenv python
export PYENV_ROOT="${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}"
PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

xrdb -merge ${XDG_CONFIG_HOME:-~/.config}/X11/Xresources

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    echo >&2 "Starting dbus"
    pkill -f dbus-daemon
    export $(dbus-launch)
fi

pkill -f i3-urgent-notify-wsl
echo >&2 "Starting i3-urgent-notify-wsl"
i3-urgent-notify-wsl &

# Send fd.o notifications as windows notifications
pkill -f notify-burnt-toast
echo >&2 "Starting notify-burnt-toast"
notify-burnt-toast &

cd

exec ssh-agent i3
