#!/bin/sh

set -e

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

if ! command -v cabal >/dev/null 2>&1; then
    echo >&2 "Error: cabal-install must be installed"
    exit 1
fi

if [ $# -eq 0 ]; then
    cabal new-install --help
    exit $?
fi

cabal new-update
cabal new-install --symlink-bindir="${XDG_DATA_HOME%/*}/bin" "$@"
