#!/bin/bash
## A script to run and clean up after tests

git clone https://github.com/tmux-plugins/tmux-test.git
mkdir lib
mv tmux-test lib/tmux-test
./lib/tmux-test/setup
cp scripts/tests/test_float.sh tests/test_float.sh
./run_tests || echo Failed to run tests, is Vagrant installed?
[[ -z $1 ]] && rm -rf tests; rm -rf tmux-test; rm -rf lib; rm -rf run_tests
