#!/bin/bash
# pacsrc - get sources for an Arch package

set -e

PKGNAME=$1
REPOSITORY=$(pacman -Si "$PKGNAME" |awk '/^Repository/{print $3}')

case "$REPOSITORY" in
    "") exit 1 ;;
    community|multilib) REPOSITORY=community ;;
    *) REPOSITORY=packages ;;
esac

PKGBUILD_URL="http://projects.archlinux.org/svntogit/$REPOSITORY.git/plain/trunk/PKGBUILD?h=packages/$PKGNAME"

echo "# $PKGBUILD_URL"

(curl -sfLk "$PKGBUILD_URL";
 echo 'printf "%s\n" "${source[@]}" |
    sed "/:\/\//!s|.*|http://projects.archlinux.org/svntogit/'$REPOSITORY'.git/plain/trunk/&?h=packages/'$PKGNAME'|" | grep -v "\.sig$" | sed "s/.*:://"') | bash
