#!/usr/bin/env bash

set -euo pipefail

pager () {
    if [ -n "$interactive" ]; then
        if command -v bat >/dev/null 2>&1; then
            bat --file-name "fd $* | as-tree"
        else
            eval "${PAGER:-less}"
        fi
    else
        cat
    fi
}

if [ -t 1 ]; then
    interactive=1
else
    interactive=
fi

fd "$@" \
    | as-tree ${interactive:+--color always} \
    | pager "$@"
