#!/usr/bin/env python
"""Print a file containing python pickled data.

pprint is used to display the objects. If pprintpp is installed,
it will be used instead, for nicer output.

If the pickle file imports, you may of course need to adjust
PYTHONPATH the way the original code had it, if necessary.
"""

import os
import sys
try:
    import cPickle as pickle
except ImportError:
    import pickle
try:
    import pprintpp as pprint
except ImportError:
    import pprint


def iter_except(func, exception, start=None):
    'Yield a function repeatedly until it raises an exception'
    try:
        if start is not None:
            yield start()
        while True:
            yield func()
    except exception:
        pass


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit('Usage: {0} FILENAME'.format(os.path.basename(sys.argv[0])))

    filename = sys.argv[1]
    with open(filename, 'rb') as f:
        p = pickle.Unpickler(f)
        for loaded in iter_except(p.load, EOFError):
            pprint.pprint(loaded)
