#!/bin/sh
# Install packages into a virtualenv with pip, then symlink any scripts into
# $XDG_DATA_HOME/../bin.

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} VENV_NAME [PIP_ARGS..]"
    echo >&2
    echo >&2 "Existing environments (both python 2 and 3):"
    for dir in "$WORKON_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

venv="$1"
shift
case "$venv" in
    -*)
        echo >&2 "Error: venv starts with -: $venv"
        exit 1
        ;;
esac

venv_dir="$WORKON_HOME/$venv"
if [ ! -e "$venv_dir" ]; then
    virtualenv "$venv_dir" || exit 1
    PATH="$venv_dir/bin:$PATH"
    pip install -U pip || exit 5
fi
. "$venv_dir/bin/activate" || exit 2

case "$(which pip)" in
    "$venv_dir/"*)
        ;;
    *)
        curl https://bootstrap.pypa.io/get-pip.py | python - || exit 3
        ;;
esac

if [ $# -eq 0 ]; then
    set -- "$venv"
fi
pip install --disable-pip-version-check "$@" || exit 4

mkdir -p "$XDG_DATA_HOME/../bin"
for script in "$venv_dir/bin/"*; do
    filename="${script##*/}"
    case "$filename" in
        python|python[0-9]*|pydoc*|python-config*|virtualenv*|pip|pip2|pip2.*|pip-2*|pip3|pip3.*|pip-3*|easy_install*|activate*|wheel):
            continue
            ;;
    esac

    link_name="$XDG_DATA_HOME/../bin/$filename"
    printf >&2 '’%s’ -> ’%s’\n' "$link_name" "$script"
    rm -f "$link_name"
    cat >"$link_name" <<END
#!/bin/bash
. "$venv_dir/bin/activate"
exec "$venv_dir/bin/\${0##*/}" "\$@"
END
    chmod +x "$link_name"
done

pydoc="$venv_dir/bin/pydoc"
if [ ! -e "$pydoc" ]; then
    cat >"$pydoc" <<END
#!$venv_dir/bin/python

import pydoc
if __name__ == '__main__':
    pydoc.cli()
END
    chmod +x "$pydoc"
fi

for man in "$venv_dir/share/man/"man*/*; do
    if [ -e "$man" ]; then
        mandest="$XDG_DATA_HOME/man/${man#$venv_dir/share/man/}"
        mkdir -p "${mandest%/*}"
        ln -sfv "$man" "$mandest"
    fi
done
