#!/bin/sh

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"

for env in "${WORKON_HOME}/"*/; do
    env="${env%/}"
    package="${env##*/}"
    (
        set -e
        . "$env/bin/activate"
        if pip freeze -l | grep -q "^$package=="; then
            pip install --disable-pip-version-check -U pip "$package"
        else
            pip list -l -o --isolated --disable-pip-version-check | awk '{print $1}' | grep -vx setuptools | \
                tr '\n' '\0' | xargs -0 pip install --disable-pip-version-check -U
        fi
    ) || { echo >&2 "Error upgrading for $env"; exit 1; }
done
