#!/bin/sh

pipx_installed () {
    pipx list | sed -n -e 's/^   *package \([^ ]*\).*/\1/p' | grep -Fqx "$1"
}

usage() {
    echo >&2 "${0##*/} [options] PACKAGE [ADDITIONAL_PACKAGE..]"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -f   Force installation even if the venv exists already"
    echo >&2 "  -n   Non-implicit: do not pass PACKAGE to pipx install automatically"
    echo >&2 "       This lets you pass a path or url to be installed for PACKAGE."
    exit 2
}

force=
implicit_package=1
while getopts fnh opt; do
    case "$opt" in
        f)
            force=1
            ;;
        n)
            implicit_package=0
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
elif [ $# -lt 2 ] && [ $implicit_package -eq 0 ]; then
    usage
fi


package="$1"
shift

editable=
if [ $implicit_package -eq 0 ]; then
    spec="$1"
    shift
    if [ -e "$spec/setup.py" ]; then
        editable=1
    fi
else
    spec="$package"
fi

if pipx_installed "$package" && [ -z "$force" ]; then
    if [ -z "$editable" ]; then
        pipx upgrade "$spec"
    else
        echo >&2 "Skipping upgrade of local $spec"
    fi
else
    pipx install ${force:+--force} ${editable:+--editable} "$spec"
fi

if [ $# -gt 0 ]; then
    echo >&2 "Installing/upgrading additional packages: $*"
    for extra_package; do
        if [ -e "$extra_package/setup.py" ]; then
            editable=1
        else
            editable=
        fi
        pipx runpip "$package" install --quiet --upgrade ${editable:+--editable} "$extra_package"
    done
fi
