// See http://kb.mozillazine.org/Localize_extension_descriptions
pref("extensions.ybookmarks@yahoo.description", "chrome://ybookmarks/locale/ybookmarks.properties");
pref("extensions.ybookmarks@yahoo.engine.installed", false);
pref("extensions.ybookmarks@yahoo.addmechanism", 1);
pref("extensions.ybookmarks@yahoo.log", false);
pref("extensions.ybookmarks@yahoo.debug", false);
pref("extensions.ybookmarks@yahoo.bookmark.sync.interval", 10);
pref("extensions.ybookmarks@yahoo.bookmark.request.timeout", 90);
pref("extensions.ybookmarks@yahoo.bookmark.threshold", 2000 );
pref("extensions.ybookmarks@yahoo.sync.chunk.wait", 8000 );
pref("extensions.ybookmarks@yahoo.sync.chunk.size", 50 );
pref("extensions.ybookmarks@yahoo.sync.attempts", 5 );
pref("extensions.ybookmarks@yahoo.show.localonly.option", false);
pref("extensions.ybookmarks@yahoo.tagsview.overflow.enable", false); 
pref("extensions.ybookmarks@yahoo.tagsview.overflow.remove_from_toplevel", false); 
pref("extensions.ybookmarks@yahoo.tagsview.overflow.level", 40); 
pref("extensions.ybookmarks@yahoo.tagsview.overflow.spillover.max", 5); 
pref("extensions.ybookmarks@yahoo.tagsview.overflow.spillover.minsize", 3);
pref("extensions.ybookmarks@yahoo.toolbar.view", 0);
pref("extensions.ybookmarks@yahoo.original.ui.hide", false);
pref("extensions.ybookmarks@yahoo.original.keybindings.remap", true);
pref("extensions.ybookmarks@yahoo.original.keybindings.remap.secondary.add.key", "/");
pref("extensions.ybookmarks@yahoo.original.keybindings.remap.secondary.add.modifiers", "accel,shift");
pref("extensions.ybookmarks@yahoo.original.keybindings.remap.secondary.sidebar.key", "B");
pref("extensions.ybookmarks@yahoo.original.keybindings.remap.secondary.sidebar.modifiers", "accel,shift");
pref("extensions.ybookmarks@yahoo.original.add.suggest.delicious", true);
pref("extensions.ybookmarks@yahoo.original.keyword.conflicts.warn", true);
pref("extensions.ybookmarks@yahoo.deliciousmenu.hidetagsmenu", false );
pref("extensions.ybookmarks@yahoo.bookmark.notes.truncate_automatically", false );
pref("extensions.ybookmarks@yahoo.bookmark.delete.warn", true);
pref("extensions.ybookmarks@yahoo.bundles.menu.include_bookmarks", true);
pref("extensions.ybookmarks@yahoo.sidebar.keep_opened", false);
pref("extensions.ybookmarks@yahoo.bookmark.delete.warn", true);
pref("extensions.ybookmarks@yahoo.bundles.menu.include_bookmarks", true);
pref("extensions.ybookmarks@yahoo.sidebar.keep_opened", false);
