# Forward my SSH agent
ssh:
  forwardAgent: true

# I prefer podman or docker to containerd
containerd:
  system: false
  user: false

# Upgrade the instance on boot
# Reboot after upgrade if required
# 🟢 Builtin default: false
upgradePackages: null
