pref('extensions.secureLogin@blueimp.net.description', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin@blueimp.net.shortcut', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin@blueimp.net.hideStatusbarIcon',false);
pref('extensions.secureLogin@blueimp.net.hideToolsMenu',false);
pref('extensions.secureLogin@blueimp.net.searchLoginsOnload',true);
pref('extensions.secureLogin@blueimp.net.highlightColor','#FF9900');
pref('extensions.secureLogin@blueimp.net.highlightOutlineStyle','solid');
pref('extensions.secureLogin@blueimp.net.highlightOutlineWidth',1);
pref('extensions.secureLogin@blueimp.net.highlightStyle','');
pref('extensions.secureLogin@blueimp.net.autoSubmitForm',true);
pref('extensions.secureLogin@blueimp.net.domainChangeConfirm', true);
pref('extensions.secureLogin@blueimp.net.javascriptProtection',false);
pref('extensions.secureLogin@blueimp.net.playLoginFoundSound',false);
pref('extensions.secureLogin@blueimp.net.playLoginSound',false);
pref('extensions.secureLogin@blueimp.net.exceptionList','');
pref('extensions.secureLogin@blueimp.net.autofillFormsOnLogin',false);