# Set the colour scheme
colorscheme dracula

# Width of a tab
set-option global tabstop 4

# Indent with 4 spaces
set-option global indentwidth 4

# Indent with tab, rather than inserting a tab character
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Clipboard management mappings
map -docstring "yank the selection into the clipboard" global user y "<a-|> pbcopy<ret>"
map -docstring "paste the clipboard" global user p "<a-!> pbpaste<ret>"

# Shortcut to quickly exit the editor
define-command -docstring "save and quit" x "write-all; quit"

# Ensure the standard library is available
nop %sh{
    mkdir -p "$kak_config/autoload"
    ln -sf "$kak_runtime/autoload" "$kak_config/autoload/standard-library"
}

# Formatting
hook global BufSetOption filetype=elixir %{
    set-option buffer formatcmd 'mix format -'
}

hook global BufSetOption filetype=python %{
    set-option buffer formatcmd 'autopep8'
}

hook global BufSetOption filetype=sh %{
    set-option buffer formatcmd 'shfmt -ci -bn -i 4'
}

# Linting
hook global WinSetOption filetype=elixir %{
    # NOTE: The `Elixir.CredoNaming.Check.Consistency.ModuleFilename` rule is
    # not supported because Kakoune moves the file to a temporary directory
    # before linting.
    set-option window lintcmd "mix credo list --config-file=.credo.exs --format=flycheck --ignore-checks='Elixir.CredoNaming.Check.Consistency.ModuleFilename'"
}

hook global WinSetOption filetype=python %{
    set-option window lintcmd "flake8 --filename='*' --format='%%(path)s:%%(row)d:%%(col)d: error: %%(text)s' --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E501,E221,E127,E128,E129,F405"
}

hook global WinSetOption filetype=sh %{
    set-option window lintcmd "shellcheck -fgcc -Cnever"
}
