#!/bin/sh

die() {
    ret=$?
    echo >&2 "$@"
    exit $ret
}

# This ensures that hg doesn't explode if the hgrc referencing external
# modules is still symlinked, but the modules themselves are missing due to
# e.g. a `peru clean`.
export HGRCPATH=

dotfilesdir="$(cd "$(dirname "$0")/.." && pwd)"
cd "$dotfilesdir" || exit 1

tmpdir="$(cd "$(mktemp -dt "${0##*/}.XXXXXX")" && pwd)"
trap 'rm -rf "$tmpdir"' EXIT INT TERM

if ! which peru >/dev/null 2>&1; then
    pipx install peru || die "peru install failed"
fi
PATH="$PATH:${XDG_DATA_HOME:-$HOME/.local/share}/../bin"

peru reup -f || echo >&2 "peru reup failed"
peru sync -f || die "peru sync failed"

if [ -e vscode/zsh-functions/_code ]; then
    sed -i.bak -e 's/@@APPNAME@@/code/' vscode/zsh-functions/_code
    rm -f vscode/zsh-functions/_code.bak
fi

if [ -e external/scripts/diff-highlight.perl ]; then
    echo '#!/usr/bin/env perl' >external/scripts/diff-highlight
    cat external/scripts/DiffHighlight.pm >>external/scripts/diff-highlight
    cat external/scripts/diff-highlight.perl >>external/scripts/diff-highlight
    rm -f external/scripts/DiffHighlight.pm external/scripts/diff-highlight.perl
    chmod +x external/scripts/diff-highlight
fi

if [ -e windows-terminal/files/archlinux-icon-crystal.svg ] && ! [ -e windows-terminal/files/archlinux-icon-crystal.png ] && command -v convert >/dev/null 2>&1; then
    convert windows-terminal/files/archlinux-icon-crystal.svg -resize 32x32 windows-terminal/files/archlinux-icon-crystal.png
fi

if [ -e zsh/promptline.zsh ]; then
    vim -c "PromptlineSnapshot! $PWD/zsh/promptline.zsh airline" -c quit >/dev/null 2>&1
fi

if [ -e tmux/tmuxline.conf ]; then
    vim -c "TmuxlineSnapshot! $PWD/tmux/tmuxline.conf" -c quit >/dev/null 2>&1
fi

true
