#!/usr/bin/env bash

repodir="$(dirname "$(cd "$(dirname "$0")" && pwd -P)")"
PATH="$repodir/scripts:$repodir/script:$HOME/.local/bin:$PATH"

# shellcheck source=../scripts/common.sh
. "$repodir/scripts/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script expects to use sudo if needed"
else
    need_sudo
fi

if [ -z "$HOMEBREW_PREFIX" ]; then
    die "HOMEBREW_PREFIX must be set or unset, not the empty string"
fi

if [ "$OS" = "linux" ]; then
    if [ -z "$DISTRO" ]; then
        msg "Warning: Unknown DISTRO, please ensure /etc/os-release exists, or set DISTRO manually."
    else
        if check_child_script "setup-system-$DISTRO"; then
            run_child_script "setup-system-$DISTRO"
        else
            if [ -n "${DISTRO_LIKE:-}" ] && check_child_script "setup-system-$DISTRO_LIKE"; then
                run_child_script "setup-system-$DISTRO_LIKE"
            fi
        fi
    fi
fi

run_child_script "setup-system-$OS"

msg "System setup complete"
