#!/usr/bin/env bash

repodir="$(dirname "$(cd "$(dirname "$0")" && pwd -P)")"
PATH="$repodir/scripts:$repodir/script:$PATH"

# shellcheck source=../scripts/common.sh
. "$repodir/scripts/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script is for user setup"
fi

bootstrap

if [ "$OS" = "linux" ]; then
    if [ -z "${DISTRO:-}" ]; then
        msg "Warning: Unknown DISTRO, please ensure /etc/os-release exists, or set DISTRO manually."
    else
        if check_child_script "setup-user-$DISTRO" &>/dev/null; then
            run_child_script "setup-user-$DISTRO"
        else
            if [ -n "${DISTRO_LIKE:-}" ] && check_child_script "setup-user-$DISTRO_LIKE" &>/dev/null; then
                run_child_script "setup-user-$DISTRO_LIKE"
            fi
        fi
    fi
fi

run_child_script "setup-user-$OS"

msg "User setup complete"
