#!/usr/bin/env bash

repodir="$(dirname "$(cd "$(dirname "$0")" && pwd -P)")"
PATH="$repodir/scripts:$repodir/scripts:$HOME/.local/bin:$PATH"

# shellcheck source=../scripts/common.sh
. "$repodir/scripts/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script is for user setup"
fi

if command -v "setup-user-$DISTRO" &>/dev/null; then
    msg "Running setup-user-$DISTRO"
    "setup-user-$DISTRO"
else
    msg "No setup-user-$DISTRO script found"
fi

if command -v "setup-user-$OS" &>/dev/null; then
    msg "Running setup-user-$OS"
    "setup-user-$OS"
else
    msg "No setup-user-$OS script found"
fi

msg "User setup complete"
