#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)

HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-$HOME/.brew}"

# shellcheck source=../scripts/common.sh
. "$scriptdir/../scripts/common.sh" || exit 1

"$scriptdir/bootstrap"

if ! [ -t 1 ]; then
    set -- --no-tty --no-pager "$@"
fi

# Export the github token for externals if available
if [ -s ~/.config/chezmoi_github_token ]; then
    export CHEZMOI_GITHUB_ACCESS_TOKEN
    CHEZMOI_GITHUB_ACCESS_TOKEN=$(cat ~/.config/chezmoi_github_token)
fi

echo >&2 "Applying dotfiles"
if chezmoi apply --keep-going "$@"; then
    echo >&2 "Dotfiles applied successfully"
else
    msg "Failed to apply dotfiles"
    if ! [ -e ~/.local/bin/uv ]; then
        # If the chezmoi apply failed due to a script or the like, we could end
        # up without our externals. Explicitly attempt to apply those.
        chezmoi apply ~/.local/bin
    fi
    exit 1
fi
