#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)

HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-$HOME/.brew}"
PATH="$HOMEBREW_PREFIX/bin:$HOME/.local/bin:$PATH"

# shellcheck source=../scripts/common.sh
. "$scriptdir/../scripts/common.sh" || exit 1

"$scriptdir/bootstrap"

if ! [ -t 1 ]; then
    set -- --no-tty --no-pager "$@"
fi

echo >&2 "Applying dotfiles"
chezmoi apply --keep-going "$@"
