#!/usr/bin/env bash

repodir="$(dirname "$(cd "$(dirname "$0")" && pwd -P)")"
PATH="$repodir/scripts:$repodir/scripts:$HOME/.local/bin:$PATH"

# shellcheck source=../scripts/common.sh
. "$repodir/scripts/common.sh" || exit 1

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
    die "Error: Do not run as root, this script expects to use sudo if needed"
else
    need_sudo
fi

if [ -z "$HOMEBREW_PREFIX" ]; then
    die "HOMEBREW_PREFIX must be set or unset, not the empty string"
fi

if [ "$OS" = "linux" ]; then
    if [ -z "$DISTRO" ]; then
        msg "Warning: Unknown DISTRO, please ensure /etc/os-release exists, or set DISTRO manually."
    else
        if command -v "setup-system-$DISTRO" &>/dev/null; then
            msg "Running setup-system-$DISTRO"
            "setup-system-$DISTRO"
        else
            msg "No setup-system-$DISTRO script found"
            if [ -n "${DISTRO_LIKE:-}" ] && command -v "setup-system-$DISTRO_LIKE" &>/dev/null; then
                msg "Running setup-system-$DISTRO_LIKE"
                "setup-system-$DISTRO_LIKE"
            else
                msg "No setup-system-$DISTRO${DISTRO_LIKE:+ or setup-system-$DISTRO_LIKE} script found"
            fi
        fi
    fi
fi

if command -v "setup-system-$OS" &>/dev/null; then
    msg "Running setup-system-$OS"
    "setup-system-$OS"
else
    msg "No setup-system-$OS script found"
fi

msg "System setup complete"
