#!/bin/sh

set -e

DOTFILESDIR="$(cd "$(dirname "$0")" && cd .. && pwd -P)"
cd "$DOTFILESDIR" || exit 1
if command -v mr >/dev/null 2>&1 && mr list | grep -qxF "mr list: $DOTFILESDIR"; then
    mr update
elif [ -e .git ]; then
    git pull
    if [ -e vim/.git ]; then
        (cd vim && git pull)
    fi
fi
