#!/bin/bash

set -euo pipefail

usage() {
    echo >&2 "${0##*/} [options] APP_DIR NEW_APP_ID"
    exit 2
}

excluded_utis=(
    public.folder
    public.directory
    public.data
    com.apple.bundle
    com.apple.resolvable
)
dry_run=0
while getopts x:nh opt; do
    case "$opt" in
        x)
            excluded_utis+=("$OPTARG")
            ;;
        n)
            dry_run=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

excluded_pattern="^(dyn.*|$(echo "${excluded_utis[*]}" | tr ' ' '|' | sed -e 's/\./\\./g'))$"
app_dir="$1"
new_app_id="$2"

tmpdir=$(mktemp -d -t "${0##*/}.XXXXXX")
trap 'rm -rf "$tmpdir"' EXIT

new_app_dir="$(mdfind "kMDItemCFBundleIdentifier == '$new_app_id'")"
if [ -z "$new_app_dir" ]; then
    echo "Error: App with ID '$new_app_id' not found." >&2
    exit 1
fi

PATH="$(cd "$(dirname "$0")" && pwd -P):$PATH"

duti-all -n "$app_dir" | cut -d" " -f 4- | sort -f >"$tmpdir/existing.txt"
duti-all -n "$new_app_dir" | cut -d" " -f 4- | sort -f >"$tmpdir/new.txt"
comm -12 "$tmpdir/existing.txt" "$tmpdir/new.txt" |
    while read -r uti role; do
        if [[ "$uti" =~ $excluded_pattern ]]; then
            continue
        fi
        echo "duti -vs $new_app_id $uti $role"
    done |
    sed -e 's/ *$//' |
    if [ "$dry_run" -eq 1 ]; then
        cat
    else
        tr '\n' '\0' | xargs -0 -n 1 -I"{}" sh -c "{}"
    fi
