#!/bin/sh

set -eu

PATH="$(cd "$(dirname "$0")" && pwd -P):$PATH"

dry_run=
case "$1" in
    -n)
        dry_run=1
        shift
        ;;
esac

app_dir="$1"
new_app_id="$2"

app_id="$(mdls -raw -name kMDItemCFBundleIdentifier "$app_dir")"
duti-all -n "$app_dir" \
    | while read -r _ _ app_id uti role; do
        echo "duti -vs $new_app_id $uti $role"
    done \
    | sed -e 's/ *$//' \
    | if [ -n "$dry_run" ]; then
        cat
    else
        tr '\n' '\0' | xargs -0 -n 1 -I"{}" sh -c "{}"
    fi
