#!/bin/sh
# The OverSight installer runs OverSight in the foreground, so avoid it.

set -e

add_login () {
    osascript -e "tell application \"System Events\" to make login item at end with properties {path:\"$1\", hidden:false}"
}

if ! [ -e /Applications/OverSight.app ]; then
    tmpdir="$(mktemp -d -t "${0##*/}.XXXXXX")" || exit 1
    trap 'rm -rf "$tmpdir"' EXIT INT TERM
    cd "$tmpdir"

    curl -fSL -o OverSight.zip https://bitbucket.org/objective-see/deploy/downloads/OverSight_1.2.0.zip
    unzip OverSight.zip
    ditto OverSight_Installer.app/Contents/Resources/OverSight.app /Applications/OverSight.app
fi
mkdir -p ~/Library/Application\ Support/Objective-See/OverSight
touch ~/Library/Application\ Support/Objective-See/OverSight/OverSight.log
add_login /Applications/OverSight.app/Contents/Library/LoginItems/OverSight\ Helper.app || :
open -g /Applications/OverSight.app/Contents/Library/LoginItems/OverSight\ Helper.app || :
