# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[✘](bold #ff5555)"
success_symbol = "[❯](bold #50fa7b)"

[cmd_duration]
format = '[$duration]($style) '
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold #ff79c6"
symbol = ""

[git_status]
format = '([$all_status$ahead_behind]($style) )'
untracked = ""
stashed = ""
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
