#!/bin/sh

# These always seem to think they're outdated
excluded_casks="whatsyoursign|oversight"

# I prefer to install this via brew, but using rustup rather than brew's rust
excluded_casks="$excluded_casks|geckodriver"

ignored_depends="geckodriver"
excluded_ignored="$(echo "$ignored_depends" | tr " " "|")"
excluded="$excluded_ignored"

trap 'brew clean; brew clean-cask-pkgs' EXIT INT TERM

unset HOMEBREW_AUTO_UPDATE

brew update || :

brew outdated --fetch-HEAD --quiet |
	if [ -n "$excluded" ]; then grep -Ev "$excluded"; else cat; fi |
	xargs brew upgrade --fetch-HEAD
if [ -n "$ignored_depends" ]; then
    ignored_outdated="$(brew outdated --fetch-HEAD --quiet | grep -E "$excluded_ignored")"
    for outdated in $ignored_outdated; do
        brew uninstall --force "$outdated"
        brew install --force --ignore-dependencies --force-bottle -v --env=std "$outdated"
    done
fi

if brew tap | grep -qxF homebrew/cask; then
    brew cask outdated --quiet |
            if [ -n "$excluded_casks" ]; then grep -Ev "$excluded_casks"; else cat; fi |
            xargs -n 1 brew cask upgrade
fi
