#!/bin/bash

prompt_colors () {
    if [ -e $HOME/.vimcolors -a -e $HOME/.vimtopromptcolors ]; then
        while read tag higrp; do
            if echo "$tag" | grep -q "^#"; then
                continue
            fi
            code=`cat $HOME/.vimcolors|grep "^$higrp "|sed -e"s,^$higrp ,,"`
            eval "color_$tag='$code'"
        done < $HOME/.vimtopromptcolors
    fi
}

prompt_promptstrs () {
    tags="xterm_set userathost user host debian_chroot ccase vim scm \
          basecwd cwd bell esc fullhost context"
    promptstr_userathost="\u@\h"
    promptstr_user="\u"
    promptstr_host="\h"
    promptstr_debian_chroot=
    if type -a scm-prompt-output &>/dev/null; then
        promptstr_scm="\$(scm-prompt-output)"
    else
        promptstr_scm=""
    fi
    promptstr_basecwd="\\W"
    promptstr_cwd="\\w"
    promptstr_bell="\\a"
    promptstr_esc="\\e"
    promptstr_fullhost="\\H"

    promptstr_context=""
    if [ -z "$context_seperator" ]; then
        context_seperator=" "
    fi

    case $TERM in
    rxvt*|Xterm|xterm*|aterm|urxvt*|cygwin)
        promptstr_xterm_set='\[\033]0;\u@\h:\w\007\]'
        ;;
    *)
        promptstr_xterm_set=''
        ;;
    esac

    if [ -n "$CLEARCASE_ROOT" ]; then
        promptstr_ccase="`echo $CLEARCASE_ROOT|cut -d/ -f3`"
        promptstr_context="$promptstr_ccase"
    fi

    if [ -n "$VIM" ]; then
        promptstr_vim="vim"
        if [ -n "$promptstr_context" ]; then
            promptstr_context="$promptstr_context$context_seperator$promptstr_vim"
        else
            promptstr_context="$promptstr_vim"
        fi
    fi

    if [ -n "$debian_chroot" ]; then
        promptstr_debian_chroot="$debian_chroot"
    elif [ -r "/etc/debian_chroot" ]; then
        promptstr_debian_chroot="$(cat /etc/debian_chroot)"
    fi

    if [ -n "$promptstr_debian_chroot" ]; then
        if [ -n "$promptstr_context" ]; then
            promptstr_context="$promptstr_context$context_seperator$promptstr_debian_chroot"
        else
            promptstr_context="$promptstr_debian_chroot"
        fi
    fi
}

parse_prompt () {
    prompt_colors
    prompt_promptstrs

    prompt="$1"
    var="$2"
    for tag in $tags; do
        promptstr="`eval echo '${promptstr_'${tag}'}'`"
        if [ -n "$promptstr" ]; then
            if supports_color; then
                colorpre="`eval echo '${color_'${tag}'}'`"
                if [ -n "$colorpre" ]; then
                    colorpre="\[\033[${colorpre}m\]"
                fi
                if [ -n "$colorpre" ]; then
                    colorpost="\[\033[${color_default}m\]"
                else
                    colorpost=""
                fi
            fi
            eval "pattern=\"\${pattern_${tag}}\""
            if [ -n "$pattern" ]; then
                promptstr="`printf \"$pattern\" \"$promptstr\"`"
            fi
        fi
        prompt="${prompt//\[$tag\]/$colorpre$promptstr$colorpost}"
#        echo "prompt: $prompt"
    done
    eval "$var='$prompt'"
}

# context is $context_seperator seperated "context" fields (are we running
# under vim, in a chroot, or under clearcase)
context_seperator="|"
pattern_context="[%s] "

pattern_ccase="[%s]"
pattern_vim="[%s]"
pattern_debian_chroot="[%s]"

prompt="[xterm_set][userathost] [context][basecwd][scm]\$ "
parse_prompt "$prompt" "PS1"
