[urls]
Anti-Paywall = "https://github.com/nextgens/anti-paywall"
CanvasBlocker = "https://github.com/kkapsner/CanvasBlocker/"
"Containers On The Go" = "https://addons.mozilla.org/en-US/firefox/addon/containers-on-the-go/"
"Duplicate Tabs Closer" = "https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer/"
"Enhancer for YouTube™" = "https://www.mrfdev.com/enhancer-for-youtube"
"GitHub Issue Hoister" = "https://github.com/mcomella/github-issue-hoister"
"Multiple Tab Handler" = "http://piro.sakura.ne.jp/xul/_multipletab.html.en"
"Never Force Download" = "https://addons.mozilla.org/en-US/firefox/addon/never-force-download/"
OneTab = "https://www.one-tab.com/"
"Save Page WE" = "https://addons.mozilla.org/en-US/firefox/addon/save-page-we/"
"SiteDelta Watch" = "http://sitedelta.schierla.de/"
"Tab Session Manager" = "https://github.com/sienori/Tab-Session-Manager"
"TabSubmit Basic" = "https://addons.mozilla.org/en-US/firefox/addon/tabsubmit-basic/"
"Tree Style Tab" = "http://piro.sakura.ne.jp/xul/_treestyletab.html.en"
"uBlock Origin" = "https://github.com/gorhill/uBlock#ublock-origin"
WebToEpub = "https://github.com/dteviot/WebToEpub"
Tab2QR = "https://addons.mozilla.org/en-US/firefox/addon/tab2qr/"
Decentraleyes = "https://decentraleyes.org/"
"about:about Button" = "https://addons.mozilla.org/en-US/firefox/addon/firefox-about-button/"
"Disable HTML5 Autoplay" = "https://addons.mozilla.org/en-US/firefox/addon/disable-autoplay/"
"Download Star" = "https://addons.mozilla.org/en-US/firefox/addon/download-star/"
"FairSteam - Gameplay video for Steam" = "http://www.fairsteam.com/"
"HTTP/2 Indicator" = "https://github.com/bsiegel/http2-indicator"
"HTTPS by default" = "https://github.com/Rob--W/https-by-default"
LoadTabOnSelect = "https://github.com/aghorler/LoadTabOnSelect"
"Multithreaded Download Manager" = "https://addons.mozilla.org/en-US/firefox/addon/multithreaded-download-manager/"
"Prevent Duplicate Tabs" = "https://github.com/brcontainer/prevent-duplicate-tabs"
"Referer Control" = "https://addons.mozilla.org/en-US/firefox/addon/referercontrol/"
"Request Control" = "https://github.com/tumpio/requestcontrol"
"Resurrect Pages" = "https://addons.mozilla.org/en-US/firefox/addon/resurrect-pages/"
"SiteDelta Highlight" = "http://sitedelta.schierla.de/"
"View Image in New Tab" = "https://addons.mozilla.org/en-US/firefox/addon/new-tab-image_exe-boss/"
"Zoom Page WE" = "https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/"
Redirector = "http://einaregilsson.com/redirector/"
"Synology Download Manager" = "https://github.com/seansfkelley/synology-download-manager"
tabs2txt = "https://zvxr.net/posts/project/2017/04/tabs2txt/"
"Privacy Badger" = "https://www.eff.org/privacybadger"
"Print Edit WE" = "https://addons.mozilla.org/en-US/firefox/addon/print-edit-we/"
"Fakespot - Analyze Fake Amazon Reviews" = "https://www.fakespot.com/"
"Vim Vixen" = "https://github.com/ueokande/vim-vixen"
Instapaper = "https://addons.mozilla.org/en-US/firefox/addon/instapaper-official/"
