[urls]
Anti-Paywall = "https://github.com/nextgens/anti-paywall"
CanvasBlocker = "https://github.com/kkapsner/CanvasBlocker/"
"Containers On The Go" = "https://addons.mozilla.org/en-US/firefox/addon/containers-on-the-go/"
"Duplicate Tabs Closer" = "https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer/"
"Enhancer for YouTube™" = "https://www.mrfdev.com/enhancer-for-youtube"
"GitHub Issue Hoister" = "https://github.com/mcomella/github-issue-hoister"
"Multiple Tab Handler" = "http://piro.sakura.ne.jp/xul/_multipletab.html.en"
"Never Force Download" = "https://addons.mozilla.org/en-US/firefox/addon/never-force-download/"
OneTab = "https://www.one-tab.com/"
"Save Page WE" = "https://addons.mozilla.org/en-US/firefox/addon/save-page-we/"
"SiteDelta Watch" = "http://sitedelta.schierla.de/"
"Tab Session Manager" = "https://github.com/sienori/Tab-Session-Manager"
"TabSubmit Basic" = "https://addons.mozilla.org/en-US/firefox/addon/tabsubmit-basic/"
"Tree Style Tab" = "http://piro.sakura.ne.jp/xul/_treestyletab.html.en"
"uBlock Origin" = "https://github.com/gorhill/uBlock#ublock-origin"
WebToEpub = "https://github.com/dteviot/WebToEpub"
Tab2QR = "https://addons.mozilla.org/en-US/firefox/addon/tab2qr/"
Decentraleyes = "https://decentraleyes.org/"
"about:about Button" = "https://addons.mozilla.org/en-US/firefox/addon/firefox-about-button/"
"Disable HTML5 Autoplay" = "https://addons.mozilla.org/en-US/firefox/addon/disable-autoplay/"
"Download Star" = "https://addons.mozilla.org/en-US/firefox/addon/download-star/"
"FairSteam - Gameplay video for Steam" = "http://www.fairsteam.com/"
"HTTP/2 Indicator" = "https://github.com/bsiegel/http2-indicator"
"HTTPS by default" = "https://github.com/Rob--W/https-by-default"
LoadTabOnSelect = "https://github.com/aghorler/LoadTabOnSelect"
"Multithreaded Download Manager" = "https://addons.mozilla.org/en-US/firefox/addon/multithreaded-download-manager/"
"Prevent Duplicate Tabs" = "https://github.com/brcontainer/prevent-duplicate-tabs"
"Referer Control" = "https://addons.mozilla.org/en-US/firefox/addon/referercontrol/"
"Request Control" = "https://github.com/tumpio/requestcontrol"
"Resurrect Pages" = "https://addons.mozilla.org/en-US/firefox/addon/resurrect-pages/"
"SiteDelta Highlight" = "http://sitedelta.schierla.de/"
"View Image in New Tab" = "https://addons.mozilla.org/en-US/firefox/addon/new-tab-image_exe-boss/"
"Zoom Page WE" = "https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/"
Redirector = "http://einaregilsson.com/redirector/"
"Synology Download Manager" = "https://github.com/seansfkelley/synology-download-manager"
tabs2txt = "https://zvxr.net/posts/project/2017/04/tabs2txt/"
"Privacy Badger" = "https://www.eff.org/privacybadger"
"Print Edit WE" = "https://addons.mozilla.org/en-US/firefox/addon/print-edit-we/"
"Fakespot - Analyze Fake Amazon Reviews" = "https://www.fakespot.com/"
"Vim Vixen" = "https://github.com/ueokande/vim-vixen"
Instapaper = "https://addons.mozilla.org/en-US/firefox/addon/instapaper-official/"
"1Password: Password Manager and Secure Wallet" = "https://agilebits.com/onepassword"
"Auto Tab Discard" = "http://add0n.com/tab-discard.html"
"Awesome RSS" = "https://chriszuber.com"
Canonical = "https://github.com/bhadaway/canonical"
ClearURLs = "https://github.com/KevinRoebert/ClearUrls"
"Cookie AutoDelete" = "https://github.com/mrdokenny/Cookie-AutoDelete"
"Drag-Select Link Text" = "https://github.com/nkestrel/dragselectlinktext"
"Enhanced Steam" = "http://www.EnhancedSteam.com/"
"Firefox Multi-Account Containers" = "https://testpilot.firefox.com/"
h264ify = "https://github.com/erkserkserks/h264ify"
"Header Editor" = "http://team.firefoxcn.net"
"HTTPS Everywhere" = "https://www.eff.org/https-everywhere"
"Incognito This Tab" = "https://browsernative.com/incognito-tab-firefox/"
instakeybinds = "https://github.com/sbdchd/instakeybinds"
"Load Background Tabs Lazily" = "https://addons.mozilla.org/en-US/firefox/addon/load-background-tabs-lazily/"
"Load Progress Bar" = "https://github.com/luben/load-progress-bar"
"Lovely forks" = "https://github.com/musically-ut/lovely-forks"
"Min Vid" = "https://testpilot.firefox.com/experiments/min-vid"
"Pinboard Pin" = "https://github.com/Cito/Pinboard-Pin"
"Refined GitHub" = "https://github.com/sindresorhus/refined-github"
"Shut Up: Comment Blocker" = "https://rickyromero.com/shutup/"
"Skip Redirect" = "https://github.com/sblask/webextension-skip-redirect"
"Smart Referer" = "https://github.com/meh/smart-referer"
snoozetabs = "https://github.com/bwinton/SnoozeTabs#readme"
Stylus = "https://add0n.com/stylus.html"
"Switch Container" = "https://gitlab.com/mjanetmars/switch-container"
"Tab Tally" = "https://addons.mozilla.org/en-US/firefox/addon/tab-tally/"
"Test Pilot" = "https://testpilot.firefox.com/"
"Textarea Cache" = "https://addons.mozilla.org/en-US/firefox/addon/textarea-cache/"
Violentmonkey = "https://violentmonkey.github.io/"
"Bookmark Toolbar Menu Button" = "https://codefisher.org/toolbar_button/"
"Chrome Store Foxified" = "https://github.com/Noitidart/Chrome-Store-Foxified/"
"Clear Cache" = "https://github.com/TenSoja/clear-cache"
ColorfulTabs = "https://www.addongenie.com/"
"Cookie Quick Manager" = "https://github.com/ysard/cookie-quick-manager"
"Gmail Quick Links" = "https://github.com/kevinwucodes/gmail-quick-links"
HoldTab = "https://github.com/Reeywhaar/holdtab"
"IdentFavIcon Quantum" = "https://www.github.com/wolfgang42/identfavicon-quantum"
"Morning Coffee Quantum" = "http://www.1122productions.com/brandon/"
"Nightly Tester Tools" = "https://wiki.mozilla.org/QA/Automation/Projects/Addons/NightlyTesterTools"
"Popup Blocker (strict)" = "http://add0n.com/popup-blocker.html"
"Reload in address bar" = "http://truben.no"
"Reload Skip Cache Button" = "https://codefisher.org/toolbar_button/"
"Sea Containers" = "https://github.com/jonathanKingston/sea-containers"
"Tab Auto Refresh" = "http://mybrowseraddon.com/tab-auto-refresh.html"
tabzen = "http://tabzen.org"
"cookies.txt" = "https://github.com/lennonhill/cookies-txt"
"Push to Kindle" = "http://fivefilters.org/kindle-it/"
"Awesome Autocomplete for GitHub" = "https://github.com/algolia/github-awesome-autocomplete"
