#!/bin/sh

abspath () {
    _path="$1"
    if [ -n "${_path##/*}" ]; then
        _path="${2:-$PWD}/$1"
    fi
    echo "$_path"
}

for arg; do
    echo "$(abspath "$(readlink "$arg")" "$(dirname "$arg")")"
done
