#!/bin/sh

usage() {
    echo >&2 "${0##*/} [-r RELATIVETO] PATH [PATH..]"
    exit 2
}

while getopts r:h opt; do
    case "$opt" in
        r)
            relativeto="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

if [ -z "$relativeto" ]; then
    relativeto="$PWD"
fi

for arg; do
    testabs="${arg##[!/]*}"
    echo "${testabs:-$relativeto/$arg}"
done
