#!/bin/sh

while getopts r:h opt; do
    case "$opt" in
        r)
            relativeto="$OPTARG"
            ;;
        \?|h)
            usage
            echo >&2 "${0##*/}: [-r RELATIVETO] PATH [PATH..]"
            ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "$relativeto" ]; then
    relativeto="$PWD"
fi

for arg; do
    testabs=${arg##[^/]*}
    echo ${testabs:-$relativeto/$arg}
done
