#!/bin/sh

if which abduco >/dev/null 2>&1; then
    socket_dir="${TMPDIR:-/tmp}/.abduco"

    # Prefer the $TMPDIR path
    mkdir -p ~/.abduco
    chmod 000 ~/.abduco

    list_sessions () {
        abduco | sed '/^Active/d; /^\*/s/$/*/; s/^..//;' | awk '{print $4}'
    }

    create_session () {
        name="$1"
        shift
        abduco -A "$name" dvtm-kergoth-status "$name"
    }
else
    : "${XDG_RUNTIME_DIR:=${TMPDIR:-/tmp}/runtime-$LOGNAME}"
    : "${XDG_DATA_HOME:=$HOME/.local/share}"
    socket_dir="${XDG_RUNTIME_DIR:-${XDG_DATA_HOME}}/att-${HOST:-$(hostname -s)}"

    list_sessions () {
        ls -tu "$socket_dir/" | sed -n -e "s,\.socket$,,p" | {
            if [ -n "$ATT_SESSION" ]; then
                sed "s#^$ATT_SESSION\$#$ATT_SESSION*#"
            else
                cat
            fi
        }
    }

    create_session () {
        name="$1"
        shift
        dtach -A "$socket_dir/$name.socket" -z -r winch dvtm-kergoth-status "$name"
    }
fi

if [ $# -lt 1 ]; then
    list_sessions
else
    if [ -n "$ATT_SESSION" ]; then
        echo >&2 "att: already inside an att session"
        exit 1
    fi

    session_name="$1"
    shift
    ENV_VARS="^(DISPLAY|SSH_AGENT_PID|SSH_ASKPASS|SSH_CONNECTION|SSH_AUTH_SOCK|WINDOWID|XAUTHORITY)="

    mkdir -p "$socket_dir"
    export ATT_SESSION="$session_name"
    export ATT_ENV="$socket_dir/$session_name.env"
    env | grep -E "$ENV_VARS" >"$socket_dir/$session_name.env"
    if [ -n "$STY" -o -n "$TMUX" ]; then
        printf "\033k%s\033\\" "$session_name"
    else
        printf "\033]0;%s\007" "$session_name"
    fi
    create_session "$session_name" "$@"
fi
