#!/bin/sh

session_name="${1:-$ATT_SESSION}"
if [ -z "$session_name" ]; then
    echo >&2 "Error: not within a session, and no session specified."
    echo >&2 "Usage: att-env [SESSIONNAME]"
    exit 1
fi

if which abduco >/dev/null 2>&1; then
    socket_dir="${TMPDIR:-/tmp}/.abduco"
else
    socket_dir="${TMPDIR:-/tmp}/dtach-$USER"
fi
if [ ! -d "$socket_dir" ]; then
    echo >&2 "Error: socket directory not found for this user, aborting"
    exit 2
fi

cat "$socket_dir/$session_name.env"
