#!/bin/sh

items="$(mktemp bgrm.XXXXXX)" || exit 1
trap "rm -f $items" EXIT

while [ $# -gt 0 ]; do
    echo "$1" >>$items
    shift
done

while read item; do
    if [ "${item%bgrm.}" != "$item" ]; then
        # Existing bgrm directories can presumably be skipped
        :
    fi
    if basename "$item" | grep -q "^bgrm."; then
        continue
    fi

    dir="$(dirname "$item")"
    tmpdir="$(mktemp -d "$dir/bgrm.XXXXXX")" || exit 1

    mv "$item" "$tmpdir/" && set -- "$@" "$tmpdir"
done <$items

rm -rf "$@" &>/dev/null </dev/null &
disown
