#!/bin/sh

items="$(mktemp bgrm.XXXXXX)" || exit 1
trap "rm -f $items" EXIT

while [ $# -gt 0 ]; do
    echo "$1" >>$items
    shift
done

while read item; do
    if [ "${item%bgrm.}" != "$item" ]; then
        # Existing bgrm directories can presumably be skipped
        continue
    fi
    if [ ! -e "$item" ] && [ ! -L "$item" ]; then
        continue
    fi

    dir="$(dirname "$item")"
    tmpdir="$(mktemp -d "$dir/bgrm.XXXXXX")" || exit 1

    mv "$item" "$tmpdir/" && set -- "$@" "$tmpdir"
done <$items

nohup rm -rf "$@" >/dev/null 2>&1 </dev/null &
