#!/bin/sh

basename=$1
shift

basename="${basename%.bin}"
basename="${basename%.cue}"

if [ ! -e "$basename.cue" ]; then
    if [ -e "$basename.toc" ]; then
        toc2cue "$basename.toc" "$basename.cue"
    else
        echo >&2 "Error: $basename.cue does not exist"
        exit 1
    fi
fi

bchunk "$@" "$basename.bin" "$basename.cue" "$basename"
