#!/bin/sh
# OSX-only script to run bmaptool against the internal SD Card Reader on a Mac

set -u

get_sdcard_device () {
    diskutil list | sed -n '/^\/dev\/disk/s/ (internal, physical)://p' | \
        grep -v '/dev/disk0$' | while read -r disk; do
            if [ "$(diskutil info "$disk" | sed -n 's# *Device / Media Name: *##p')" = "SD Card Reader" ]; then
                echo "$disk"
                return 0
            fi
        done
    return 1
}

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} BMAP_FILE [IMAGE_FILE]"
    echo >&2
    echo >&2 "If unspecified, IMAGE_FILE is BMAP_FILE with .bmap replaced by .bz2"
    exit 2
fi

bmap_file="$1"
if [ $# -lt 2 ]; then
    image_file="${bmap_file%.bmap}.bz2"
fi

sdcard_device="$(get_sdcard_device)"
if [ -z "$sdcard_device" ]; then
    echo >&2 "Error: no SD Card Reader found"
    exit 1
fi

diskutil info "$sdcard_device"
diskutil list "$sdcard_device"
diskutil unmountDisk "$sdcard_device" || exit $?
rdevice="/dev/r${sdcard_device#/dev/}"
sudo -k bmaptool copy --bmap "$bmap_file" "$image_file" "$rdevice"
