#!/bin/sh

clean_caskroom () {
    find "$(brew --prefix)/Caskroom" -iname \*.dmg -o -iname \*.pkg -o -iname \*.app -prune | grep -iv uninstall | nlxargs trash -v
}

brew cleanup && brew wipe-cache && clean_caskroom
