#!/bin/sh

set -eu
trap 'brew clean; brew clean-cask-pkgs' EXIT INT TERM

brew update || :
brew upgrade --fetch-HEAD
brew cu
find "$(brew --prefix)/Caskroom" -iname \*.pkg -o -iname \*.app -prune | grep -iv uninstall | nlxargs -t -n 1 open -W
