#!/bin/sh
# Install packages into a fresh homebrew install, then symlink its
# binaries/scripts into $XDG_DATA_HOME/../bin

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
HOMEBREWS_HOME="${HOMEBREWS_HOME:-$XDG_DATA_HOME/homebrews}"

usage () {
    echo >&2 "Usage: ${0##*/} BREWENV_NAME [BREW_ARGS..]"
    echo >&2
    echo >&2 "Existing isolated homebrew installations:"
    for dir in "$HOMEBREWS_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
    exit 1
}

while getopts h opt; do
    case "$opt" in
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

brewenv="$1"
shift
brewenv_dir="$HOMEBREWS_HOME/$brewenv"
if [ ! -e "$brewenv_dir" ]; then
    "$(dirname "$0")/install-brew" "$brewenv_dir"
fi

PATH="$brewenv_dir/bin:$PATH"

if [ $# -eq 0 ]; then
    set -- "$brewenv"
fi
brew install "$@"

cat <<END >"$brewenv_dir/bin/man"
#!/bin/sh
scriptdir="\$(dirname "\$0")"
MANPATH="\${scriptdir%/*}/share/man:\$(manpath)" /usr/bin/man "\$@"
END
chmod +x "$brewenv_dir/bin/man"

dest="$XDG_DATA_HOME/../bin"
mkdir -p "$dest"

for brew; do
    case "$brew" in
        -*)
            continue
            ;;
    esac
    brew="${brew##*/}"
    for bin in "$brewenv_dir/opt/$brew/bin/"*; do
        filename="${bin##*/}"
        if [ -e "$bin" ] && [ -e "$brewenv_dir/bin/$filename" ]; then
            rm -f "$dest/$filename"
            cat >"$dest/$filename" <<END
PATH="$brewenv_dir/bin:\$PATH"
exec "$brewenv_dir/bin/$filename" "\$@"
END
            chmod u+x "$dest/$filename"
            echo >&2 "Created wrapper script at $dest/$filename"
        fi
    done

    for man in "$brewenv_dir/opt/$brew/share/man/"man*/*; do
        if [ -e "$man" ]; then
            mandest="$XDG_DATA_HOME/man/${man#$brewenv_dir/opt/$brew/share/man/}"
            mkdir -p "${mandest%/*}"
            ln -sfv "$man" "$mandest"
        fi
    done
done
