#!/bin/sh

# These always seem to think they're outdated
excluded_casks="whatsyoursign|oversight"

set -eu
trap 'brew clean; brew clean-cask-pkgs' EXIT INT TERM

unset CARGO_HOME HOMEBREW_AUTO_UPDATE

# We clear out any old packages/apps here, since we only want to run installers
# that we just installed, not old ones. If the installer reboots the system
# before it exits, the clean up won't happen after it installs, so we need it
# to run up front for that as well.
brew clean || :
brew clean-cask-pkgs || :

brew update || :
brew upgrade --fetch-HEAD
brew cask outdated \
    | if [ -n "$excluded_casks" ]; then grep -Ev "$excluded_casks"; else cat; fi \
    | xargs brew cask reinstall
brew cask cleanup
find "$(brew --prefix)/Caskroom" -iname \*.pkg -o -iname \*.app -prune | grep -iv uninstall | nlxargs -t -n 1 open -W
