#!/bin/sh
# Install packages into a fresh homebrew install, then symlink its
# binaries/scripts into $XDG_DATA_HOME/../bin

XDG_DATA_HOME="${XDG_DATA_HOME:-~/.local/share}"
HOMEBREWS_HOME="${HOMEBREWS_HOME:-$XDG_DATA_HOME/homebrews}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} BREWENV_NAME [BREW_ARGS..]"
    echo >&2
    echo >&2 "Existing isolated homebrew installations:"
    for dir in "$HOMEBREWS_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

brewenv="$1"
shift
brewenv_dir="$HOMEBREWS_HOME/$brewenv"
if [ ! -e "$brewenv_dir" ]; then
    if which brew >/dev/null 2>&1; then
        git clone-via "$(brew --prefix)" "$brewenv_dir"
    else
        git clone https://github.com/Homebrew/homebrew.git "$brewenv_dir"
    fi
fi

PATH="$brewenv_dir/bin:$PATH"

if [ $# -eq 0 ]; then
    set -- "$brewenv"
fi
brew install "$@"

dest="$XDG_DATA_HOME/../bin"
mkdir -p "$dest"

for brew; do
    case "$brew" in
        -*)
            continue
            ;;
    esac
    brew="${brew##*/}"
    for bin in "$brewenv_dir/opt/$brew/bin/"*; do
        filename="${bin##*/}"
        if [ -e "$bin" ] && [ -e "$brewenv_dir/bin/$filename" ]; then
            rm -f "$dest/$filename"
            cat >"$dest/$filename" <<END
PATH="$brewenv_dir/bin:\$PATH"
exec "$brewenv_dir/bin/$filename" "\$@"
END
            chmod u+x "$dest/$filename"
            echo >&2 "Created wrapper script at $dest/$filename"
        fi
    done
done
