#!/bin/bash
#Jun 11, 2003 10:38 AM Shankar Chakkere
#burn the AudioCD,VCD and DataCD

#Enable the following line if you have Superdrive
#You might have to add IODVDServices/1
#or IODVDServices/2 if you have multiple drives
DEVICE=IODVDServices

#Enable the following line if you have regular/combo drive
#You might have to add IOCompactDiscServices/1
#or IOCompactDiscServices/2 if you have multiple drives
#DEVICE=IOCompactDiscServices

DRIVER=generic-mmc

case $# in
  0)
    echo 'Usage: burncd toc_file' >&2 ; exit 1;;
  *)
  sudo cdrdao write --device $DEVICE --driver $DRIVER  $1;;
esac
