#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
repodir=${scriptdir%/*}
tmpfile=$(mktemp -t "${0##*/}.XXXXXX")

usage() {
    echo >&2 "${0##*/} [-t TAGS] [PATH..]"
    exit 2
}

tags=Dotfiles
while getopts t:h opt; do
    case "$opt" in
        t)
            tags="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

for filename; do
    filename="${filename#"$HOME"/}"
    mkdir -p "$(dirname "$repodir/home/$filename")"
    op document create "$HOME/$filename" --tags "$tags" --title "$filename" | tee "$tmpfile"
    if command -v jq >/dev/null 2>&1; then
        uuid=$(jq -r '.uuid' "$tmpfile")
    else
        uuid=PLACEHOLDER
        echo >&2 "Warning: jq not found, using placeholder UUID. Please edit $filename.tmpl"
    fi
    chezmoi add --template "$HOME/$filename"
    src=$(chezmoi source-path "$HOME/$filename")
    if [ -f "$src" ]; then
        printf '{{- onepasswordDocument "%s" -}}\n' "$uuid" >"$src"
    fi
done
