#!/usr/bin/env bash
# Interpreter which executes after applying chezmoi templating.
#
# In order to use this, the path to this script must be either fully qualified
# or in the PATH.  The script must be executable.
#
# Example usage:
#
#     $ cat >hello-chemzoi <<EOF
#     #!/usr/bin/env chezmoi-exec
#     #!/usr/bin/env bash
#     echo "Hello, {{ .chezmoi.username }}"
#     EOF
#     $ chmod +x hello-chemzoi
#     $ ./hello-chemzoi
#     Hello, kergoth

abspath() {
    _path="$1"
    if [ -n "${_path##/*}" ]; then
        _path="${2:-$PWD}/$1"
    fi
    echo "$_path"
}

script=$(abspath "$1")
tmpfile=$(mktemp -t "${script##*/}.XXXXXX")
trap 'rm -f "$tmpfile"' EXIT INT TERM

tail -n +2 "$script" |
    chezmoi execute-template >"$tmpfile"
chmod +x "$tmpfile"

interpreter=$(sed -n -e '1s/^#!//p' "$tmpfile")
case "$interpreter" in
/usr/bin/env\ *)
    interpreter=$(command -v "${interpreter#/usr/bin/env }") || exit 1
    ;;
esac

export CHEZMOI_EXEC_SCRIPT="$tmpfile"
case "$interpreter" in
*/bash | */zsh)
    exec -a "$script" "$interpreter" -c ". \"$tmpfile\"" "$@"
    ;;
*)
    exec -a "$script" "$tmpfile" "$@"
    ;;
esac
