#!/usr/bin/env bash
# Interpreter which executes after applying chezmoi templating.
#
# In order to use this, the path to this script must be either fully qualified
# or in the PATH.  The script must be executable.
#
# Example usage:
#
#     $ cat >hello-chemzoi <<EOF
#     #!/usr/bin/env chezmoi-exec
#     #!/usr/bin/env bash
#     echo "Hello, {{ .chezmoi.username }}"
#     EOF
#     $ chmod +x hello-chemzoi
#     $ ./hello-chemzoi
#     Hello, kergoth

abspath() {
    _path="$1"
    if [ -n "${_path##/*}" ]; then
        _path="${2:-$PWD}/$1"
    fi
    echo "$_path"
}

script=$(abspath "$1")
tmpdir=$(mktemp -d -t "${script##*/}.XXXXXX")
trap 'rm -rf "$tmpdir"' EXIT INT TERM

tail -n +2 "$script" >"$tmpdir/script.pre"
chezmoi execute-template --output "$tmpdir/script" --file "$tmpdir/script.pre"
chmod +x "$tmpdir/script"

interpreter=$(sed -n -e '1s/^#!//p' "$tmpdir/script")
case "$interpreter" in
/usr/bin/env\ *)
    interpreter=$(command -v "${interpreter#/usr/bin/env }") || exit 1
    ;;
esac

export CHEZMOI_EXEC_SCRIPT="$tmpdir/script"
case "$interpreter" in
*/bash | */zsh)
    exec -a "$script" "$interpreter" -c ". \"$tmpdir/script\"" "$@"
    ;;
*)
    exec -a "$script" "$tmpdir/script" "$@"
    ;;
esac
