#!/bin/sh

usage () {
    cat >&2 <<END
Usage: comm-files [-123] DIR1 DIR2 [find arguments..]

Compare the files within two directories, but not the contents of those files.

Options (default: -3. To specify multiple, use a single argument, e.g. -23):

     -1      Suppress printing of column 1.
     -2      Suppress printing of column 2.
     -3      Suppress printing of column 3.

find arguments default to: -type f -o -type l
END
    exit 1
}

abspath () {
    for arg; do
        testabs=${arg##[!/]*}
        echo ${testabs:-$PWD/$arg}
    done
}

exclude () {
    if [ -n "$exclusion" ]; then
        grep -Ev "^$exclusion"
    else
        cat
    fi
}


comm_arg=-3
case "$1" in
    -[123]*)
        comm_arg="$1"
        shift
        ;;
    -h)
        usage
        ;;
esac

exclusion=
if echo "$comm_arg" | grep -q 1; then
    exclusion="-"
fi
if echo "$comm_arg" | grep -q 2; then
    exclusion="$exclusion|\+"
fi
if echo "$comm_arg" | grep -q 3; then
    exclusion="$exclusion| "
fi
exclusion="${exclusion#|}"

if [ $# -lt 2 ]; then
    usage
fi

from="$(abspath "$1")"
to="$(abspath "$2")"
shift 2

if [ $# -eq 0 ]; then
    set -- -type f -o -type l
fi

fromfiles="$(mktemp -t "${0##*/}.XXXXXX")"
tofiles="$(mktemp -t "${0##*/}.XXXXXX")"
trap 'rm -f $fromfiles $tofiles' EXIT INT TERM

echo >&2 "Comparing the list of files from $from to $to"

cd "$from"
find . "$@" | sort >"$fromfiles"
cd - >/dev/null
cd "$to"
find . "$@" | sort >"$tofiles"
comm "$fromfiles" "$tofiles" | \
    sed "s#^	\./#+#; s#^\./#-#; s#^		\./# #" | exclude | \
        sort | ${PAGER:-more}
