#!/bin/sh

if [ $# -lt 2 ]; then
    cat >&2 <<END
Usage: comm-files DIR1 DIR2 [find arguments..]

Compare the files within two directories, but not the contents of those files.

find arguments default to: -type f -o -type l
END
    exit 1
fi

abspath () {
    for arg; do
        testabs=${arg##[^/]*}
        echo ${testabs:-$relativeto/$arg}
    done
}


from="$(abspath "$1")"
to="$(abspath "$2")"
shift 2

if [ $# -eq 0 ]; then
    set -- -type f -o -type l
fi

fromfiles="$(abspath "$(mktemp -t ${0##*/}.XXXXXX)")"
tofiles="$(abspath "$(mktemp -t ${0##*/}.XXXXXX)")"
trap "rm -f $fromfiles $tofiles" EXIT INT TERM

echo >&2 "Comparing the list of files from $from to $to"

cd "$from"
find . "$@" | sort >"$fromfiles"
cd "$to"
find . "$@" | sort >"$tofiles"
comm "$fromfiles" "$tofiles" | \
    sed "s#^	\./#+#; s#^\./#-#; s#^		\./# #" | sort | \
    ${PAGER:-more}
