#!/bin/bash
# install AUR packages with cower

mkdir -p "$HOME/Build"
cd "$HOME/Build" && cower -d "$1" || exit 1
builddir="$_"
cd "$builddir" || exit 2

${EDITOR:-vim} PKGBUILD

makepkg -sci && cd - &>/dev/null

read -p "Remove Build directory? [Y/n]? " yn
if [ "$yn" = "y" ]; then
    printf "\n%s\n" "Removing build directory..."
    rm -rf "$builddir"
else
    printf "%s\n" "Build completed."
fi
