#!/bin/sh

set -e

title="$1"
if [ -z "$title" ]; then
    echo >&2 "Usage: $0 TITLE"
    exit 2
fi

tocfile=$(mktemp -t $(basename $0).XXXXXX)
trap "rm -f $tocfile" EXIT

rm -f "$tocfile"
cdrdao read-cd --driver generic-mmc:0x20000 --read-raw --datafile "$title.bin" "$tocfile"
toc2cue $tocfile "$title".cue
growlnotify -m "$title" rip complete
