#!/bin/sh
#
# Seeks and prints dead symlinks recursively
#
# From https://github.com/infertux/bin-scripts/blob/master/dead-symlinks

usage() {
    cat <<END >&2
${0##*/} [options..] [PATH..]

Options:
  options
  -h   Show usage
END
    exit 2
}

show_dest=
while getopts dh opt; do
    case "$opt" in
        d)
            show_dest=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    set -- .
fi

printf >&2 'Searching for dead symbolic links in: %s\n' "$*"

tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM

TAB="$(printf '\t')"
find "$@" -type l -not \
    \( -path '/proc/*' -o -path '/dev/*' -o -path '/data/*' -prune \) 2>/dev/null \
    | while read -r fn; do
        if ! [ -e "$fn" ]; then
            printf '%s' "$fn"
            if [ "$show_dest" = "1" ]; then
                printf '\t%s' "$(readlink "$fn")"
            fi
            printf '\n'
        fi
    done
exit 0
