#!/usr/bin/env bash

set -euo pipefail

jdupes-oneline \
    | sed -e 's/\\ / /g' \
    | while read -r line; do
        printf '%s\n' "$line" | tr '\t' '\0' | tr -d '\n' | xargs -0 "$@" || :
    done
