#!/bin/sh

for url; do
    http -FI "$url" | pup script | grep mp4 | tr '"' '\n' | grep '^http' | grep mp4 | sort -u | head -n 1 | \
        while read -r video_url; do
            # name="$(basename "$video_url" | sed 's,\?.*,,')"
            title="$(http -FIb "$url" | pup head title 'text{}' | sed 's, |.*,,; s,: *, - ,')"
            http -FIdo "$title.mp4" "$video_url"
        done
done
