#!/bin/sh

for url; do
    subdir="$(echo "$url" | sed -e 's#https://standardebooks.org/ebooks/##')"
    mkdir -p "$subdir"
    grab-links "$url" \
        | grep -F "$url/" \
        | grep -Ev '\.(epub3|kepub)' \
        | while read -r url; do
            fn="$subdir/${url##*/}"
            wget -cO "$fn" "$url"
        done
done
