#!/bin/sh

if which trash >/dev/null 2>&1; then
    alias remove="trash -v"
else
    alias remove=bgrm
fi

if which drop-external >/dev/null 2>&1; then
    drop_external () {
        drop-external "$@"
    }
else
    drop_external () {
        false
    }
fi

for arg; do
    if drop_external "$arg"; then
        :
    elif [ -h "$arg" ]; then
        echo >&2 "$arg"
        bgrm "$arg"
    elif [ -e "$arg" ]; then
        remove "$arg"
    fi
done
