#!/bin/sh

if which trash >/dev/null 2>&1; then
    alias remove="trash -v"
fi

for arg; do
    if [ -h "$arg" ]; then
        bgrm "$arg"
    elif [ -e "$arg" ]; then
        remove "$arg"
    fi
done
