#!/bin/sh
# Courtesy http://waxandwane.org/dvtm.html, with modification

if [ $# -lt 1 ] || [ -z "$1" ]; then
    printf "Usage:  ${0##*/} ID [CMD..]\n" >&2
    exit 1
fi


ID=$(echo $1 | tr [A-Z] [a-z])
shift
LOGNAME="${LOGNAME:-$(logname)}"
DVTM_TMPDIR="${TMPDIR:-/tmp}/dvtm-$LOGNAME"
if [ ! -e "$DVTM_TMPDIR" ]; then
    mkdir -p $DVTM_TMPDIR
    chmod 0700 $DVTM_TMPDIR
fi
FIFO="$DVTM_TMPDIR/$ID-status"

[ -e "$FIFO" ] || mkfifo "$FIFO"
chmod 600 $FIFO

dvtm-print-status -c 60 "$ID" >$FIFO &

STATUS_PID=$!
trap "kill $STATUS_PID; rm $FIFO" EXIT INT TERM
disown $STATUS_PID
export DVTM_ID=$ID
dvtm -s $FIFO -h 4096 "$@" 2>/dev/null
