#!/usr/bin/env python
# encoding: utf-8

import argparse
import errno
import os
import re
import shutil
import string
import subprocess
import sys
import titlecase

def get_metadata(filename):
    output = subprocess.check_output(['ebook-meta', filename])
    data = {}
    for line in output.splitlines():
        try:
            field, value = line.split(':', 1)
        except ValueError:
            field = field.strip()
            data[field] = data[field] + ' ' + line.rstrip()
        else:
            data[field.strip()] = value.strip()
    return data

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file_from')
    parser.add_argument('file_to')
    args = parser.parse_args()

    data = get_metadata(args.file_from)
    if not data.get('Title'):
        sys.exit("Error: title is not set")

    authors, title = data['Author(s)'], data['Title']
    cmd = ['ebook-meta', '--authors', authors, '--title', title, args.file_to]
    subprocess.check_call(cmd)
