#!/bin/sh

tempdir="$(mktemp -d -t ExtractIcons.XXXX)"
trap "rm -rf \"$tempdir\"" EXIT INT
wrestool -x -t14 -o $tempdir "$@"
for ico in $tempdir/*.ico; do
    noext="${ico%.ico}"
    base="${noext##*/}"
    makeicns -in "$ico" -out "$base.icns"
done
