#!/usr/bin/perl
# f [FIELDS,FIELD-RANGE] - output nth fields
# originally from http://perl.plover.com/classes/mybin/samples/slide011.html

my $o = shift or do { print STDERR "Usage: $0 fields,field-range\n"; exit 1; };
my @o = map { $_ > 0 ? $_-1 : $_ }
        map { /\d\K-/ ? $`..$' : $_ }
        split ",", $o;

while (<>) {
        chomp;
        print join(" ", (split)[@o]), "\n";
}
