#!/bin/sh

PATH="$(dirname "$0"):$PATH"

tag_opts=
show_game_wrapper_type=0
while [ $# -gt 0 ]; do
    case "$1" in
        -t)
            show_game_wrapper_type=1
            ;;
        -0)
            tag_opts="$tag_opts -0"
            ;;
        -p)
            shift || usage
            tag_opts="$tag_opts -p \"$1\""
            ;;
        -h|--help)
            echo >&2 "${0##*/} [OPTIONS] [TAG..]"
            echo >&2
            echo >&2 "Options:"
            echo >&2
            echo >&2 "  -0        Use a \0 separator rather than newline"
            echo >&2 "  -t        Show game wrapper type in column 2"
            echo >&2 "  -p PATH   Limit to games under the specified path"
            exit 2
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
    shift
done

if [ $show_game_wrapper_type -eq 1 ]; then
    tag_opts="$tag_opts -0"
fi

utis="com.apple.application-bundle net.washboardabs.boxer-game-package"
game_match () {
    printf "( "
    for uti in $utis; do
        printf " || kMDItemContentType == '%s'" "$uti"
    done | sed "s,^ || ,,"
    printf " || kMDItemFSName == '*.nes'c"
    printf " || kMDItemFSName == '*.smc'c"
    printf " || kMDItemFSName == '*.gba'c"
    printf " || kMDItemFSName == '*.bin'c"
    printf " )"
}

eval tag-find $tag_opts "-q \"$(echo $(game_match))\" Game \"\$@\"" | {
    if [ $show_game_wrapper_type -eq 1 ]; then
        xargs -0 identify-game-wrapper
    else
        cat
    fi
}
