#!/bin/sh

if [ ! -e /Volumes/My\ Passport ]; then
    echo >&2 "My Passport drive is not mounted, aborting"
    exit 1
fi

{
    find-games | grep '/Volumes/My Passport/'
    find /Volumes/My\ Passport/Games*/ -iname \*.app -prune -type l -print -maxdepth 2 | sed 's,//,/,g'
    find /Volumes/Games/Games*/ -iname \*.app -prune -print -maxdepth 2|grep -Ev 'Setup|Launcher|-64' | sed 's,//,/,g'
} | grep -Ev '\.Trashes|Archived|Pending|Backup' | \
    tr '\n' '\0' | xargs -0 identify-game-wrapper | sed 's,.unknown$,,' | \
    sed 's,/Volumes/[^/]*/,,; s,OpenEmu Library/roms/,OpenEmu/,' | sort -u
