#!/bin/sh

PATH="$(dirname "$0"):$PATH"

tag_args=
show_game_wrapper_type=0
while getopts t0p:h opt; do
    case "$opt" in
        t)
            show_game_wrapper_type=1
            ;;
        0)
            tag_args="$tag_args -0"
            ;;
        p)
            tag_args="$tag_args -p \"$OPTARG\""
            ;;
        \?|h)
            echo >&2 "${0##*/} [OPTIONS]"
            echo >&2
            echo >&2 "Options:"
            echo >&2
            echo >&2 "  -0      Use a \0 separator rather than newline"
            echo >&2 "  -t      Show game wrapper type in column 2"
            exit 2
            ;;
    esac
done
shift $(($OPTIND - 1))


eval tag-find $tag_args "-q \"( kMDItemContentType == 'com.apple.application-bundle' || kMDItemContentType == 'net.washboardabs.boxer-game-package' )\" Game \"\$@\"" | {
    if [ $show_game_wrapper_type -eq 1 ]; then
        xargs -0 identify-game-wrapper
    else
        cat
    fi
}
