#!/bin/sh
# Run a smart recursive grep if such a tool is available.
# Prefers, in this order: rg, pt, ag, ack, grep -r

usage() {
    cat <<END >&2
${0##*/} [options..] PATTERN [PATH ...]

Options:
  -S   Case sensitive, no smart-case
  -i   Case insensitive
  -u   Unrestricted. Do not respect ignore files
  -l   Only print the paths with at least one match
  -w   Only match whole words
  -V   Vim-style
  -v   Verbose. Show the search command to be run
  -h   Show usage
END
    exit 2
}

parse_args() {
    smart_case=1
    no_smart_case=
    ignore_case=
    unrestricted=
    files_with_matches=
    word_regexp=
    vimgrep=
    verbose=0
    while getopts SiulwVvh opt; do
        case "$opt" in
            S)
                smart_case=
                no_smart_case=1
                ignore_case=
                ;;
            i)
                smart_case=
                no_smart_case=
                ignore_case=1
                ;;
            u)
                unrestricted=1
                ;;
            l)
                files_with_matches=1
                ;;
            w)
                word_regexp=1
                ;;
            V)
                vimgrep=1
                ;;
            v)
                verbose=1
                ;;
            \? | h)
                usage
                ;;
        esac
    done
    shift $((OPTIND - 1))

    if [ $# -eq 0 ]; then
        usage
    fi

    if [ -t 1 ]; then
        paged=1
    else
        paged=
    fi
}

has() {
    command -v "$1" >/dev/null 2>&1
}

pager() {
    if [ -n "$paged" ]; then
        if [ -n "$PAGER" ]; then
            case "$PAGER" in
                less*)
                    $PAGER -R
                    ;;
                *)
                    $PAGER
                    ;;
            esac
        elif has less; then
            less -R
        else
            more
        fi
    else
        cat
    fi
}

run() {
    # shellcheck disable=SC2046
    set -- $(eval 'echo "$G_'"$1"'_ARGS"') "$@"
    if [ $verbose -eq 1 ]; then
        echo >&2 "RUN $*"
    fi
    command "$@"
}

parse_args "$@"
shift $((OPTIND - 1))

set -- ${word_regexp:+--word-regexp} ${ignore_case:+--ignore-case} ${files_with_matches:+--files-with-matches} "$@"

if has rg; then
    if [ -n "$paged" ] && [ -z "$files_with_matches" ] && [ -z "$vimgrep" ] && has bat && has batgrep; then
        run batgrep ${unrestricted:+--rg:unrestricted} ${smart_case:+--smart-case} "$@"
    else
        run rg ${vimgrep:+--vimgrep} ${unrestricted:+--unrestricted} ${smart_case:+--smart-case} ${paged:+--pretty} --line-number "$@" | pager
    fi
elif has pt; then
    run pt ${vimgrep:+--column} ${unrestricted:+--skip-vcs-ignores} ${smart_case:+--smart-case} ${paged:+--color --group} "$@" | pager
elif has ag; then
    run ag ${vimgrep:+--vimgrep} ${unrestricted:+--skip-vcs-ignores} ${smart_case:+--smart-case} ${no_smart_case:+--case-sensitive} ${paged:+--color --group} "$@" | pager
elif has ack; then
    if command -v ack-grep; then
        alias ack=ack-grep
    fi
    run ack ${vimgrep:+--column} ${smart_case:+--smart-case} ${paged:+--color --group} "$@" | pager
else
    if [ $# -eq 1 ]; then
        set -- "$@" .
    fi
    run grep ${paged:+--color=always} --line-number --recursive ${smart_case:+--ignore-case} -I "$@" | pager
fi
