#!/bin/sh
# Install packages into a separate home with gem, then link any scripts into
# $XDG_DATA_HOME/../bin.

GEM="${GEM:-gem}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
GEMENV_HOME="${GEMENV_HOME:-$XDG_DATA_HOME/gem}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} GEMENV_NAME [PIP_ARGS..]"
    echo >&2
    echo >&2 "Existing environments:"
    for dir in "$GEMENV_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

if [ "$GEM" != gem ]; then
    alias gem="$GEM"
fi

gemenv="$1"
shift

ruby_version="$(gem env | grep 'RUBY VERSION:' | cut -d: -f2 | awk '{print $1}')" || exit 1
gemenv_dir="$GEMENV_HOME/$gemenv/$ruby_version"

mkdir -p "$gemenv_dir/bin"
cat >"$gemenv_dir/bin/activate" <<END
export GEM_HOME="$gemenv_dir"
export PATH="\$GEM_HOME/bin:\$PATH"
END
. "$gemenv_dir/bin/activate"

if [ $# -eq 0 ]; then
    set -- "$gemenv"
fi
gem install --no-user-install "$@"

mkdir -p "$XDG_DATA_HOME/../bin"
for script in "$gemenv_dir/bin/"*; do
    filename="${script##*/}"
    case "$filename" in
        activate):
            continue
            ;;
    esac

    link_name="$XDG_DATA_HOME/../bin/$filename"
    printf >&2 '’%s’ -> ’%s’\n' "$link_name" "$script"
    cat >"$link_name" <<END
#!/bin/bash
. "$gemenv_dir/bin/activate"
exec "$gemenv_dir/bin/\${0##*/}" "\$@"
END
    chmod +x "$link_name"
done

gem list -l | tr -d '()' | while read -r name version; do
    mandir="$gemenv_dir/gems/$name-$version/man"
    if [ -e "$mandir" ]; then
        for man in "$mandir"/*.[0-9]; do
            if [ -e "$man" ]; then
                mandestdir="$XDG_DATA_HOME/man/man${man##*.}"
                mkdir -p "$mandestdir"
                ln -sfv "$man" "$mandestdir/"
            fi
        done
    fi
done
