#!/bin/sh
# Install packages into a separate home with gem, then link any scripts into
# $XDG_DATA_HOME/../bin.

XDG_DATA_HOME="${XDG_DATA_HOME:-~/.local/share}"
GEMENV_HOME="${GEMENV_HOME:-$XDG_DATA_HOME/gem}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} GEMENV_NAME [PIP_ARGS..]"
    echo >&2
    echo >&2 "Existing environments:"
    for dir in "$GEMENV_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

gemenv="$1"
shift
gemenv_dir="$GEMENV_HOME/$gemenv"

mkdir -p "$gemenv_dir/bin"
cat >"$gemenv_dir/bin/activate" <<END
export GEM_HOME="$gemenv_dir"
export PATH="\$GEM_HOME/bin:\$PATH"
END
. "$gemenv_dir/bin/activate"

if [ $# -eq 0 ]; then
    set -- "$gemenv"
fi
gem install --no-user-install "$@"

mkdir -p "$XDG_DATA_HOME/../bin"
for script in "$gemenv_dir/bin/"*; do
    filename="${script##*/}"
    case "$filename" in
        activate):
            continue
            ;;
    esac

    link_name="$XDG_DATA_HOME/../bin/$filename"
    printf >&2 '’%s’ -> ’%s’\n' "$link_name" "$script"
    cat >"$link_name" <<END
#!/bin/bash
. "$gemenv_dir/bin/activate"
exec "$gemenv_dir/bin/\${0##*/}" "\$@"
END
    chmod +x "$link_name"
done
