#!/bin/sh

usage () {
    echo >&2 "${0##*/} [-a]"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -a      Show all branches"
    exit 2
}

pattern=refs/heads/
while getopts ah opt; do
    case "$opt" in
        a)
            pattern=
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))


git for-each-ref --sort=committerdate $pattern --format='%(color:yellow)%(HEAD) %(refname:short)|%(color:bold green)%(committerdate:relative)|%(color:reset)%(objectname:short) %(upstream:trackshort) %(subject) <%(color:blue)%(authorname)>%(color:reset)' "$@" | column -ts'|'
