#!/bin/sh
# Resurrect all files removed from the repository, using git-attic

PATH="$PATH:$(dirname "$0")"

git attic |
    cut -d" " -f2- |
    grep -E "^[^:]*:$*" |
    while IFS=: read commit file; do
        if [ ! -e "$file" ] && [ ! -h "$file" ]; then
            git checkout "$commit" -- "$file"
        fi
    done
