#!/bin/sh

set -eu

if [ $# -gt 0 ]; then
    fork="$1"
else
    fork="$USER"
    hub fork
fi

git fetch -p "$fork"

ret=0
git prune-merged -R -r "$fork" || ret=1
git prune-merged -R -r "$fork" -c origin || ret=1
exit "$ret"
