#!/bin/sh
#
# git-mvd - Move or rename a file, a directory, or a symlink, creating
#           any missing leading directories in the destination.

usage () {
    git mv -h
    exit 2
}

evalf () {
    fmt="$1"
    shift
    # printf >&2 "evalf: $fmt\n" "$@"
    # eval echo >&2 "evalf: $(printf "$fmt" "$@")"
    eval "$(printf "$fmt" "$@")"
}

while getopts vnfkh opt; do
    case "$opt" in
        \?|h)
            usage
            ;;
    esac
done

if [ $# -lt 2 ]; then
    usage
fi

destination="$(eval printf "\$$#")"
destdir="$destination"
if [ $# -eq 2 ]; then
    case "$destination" in
        */)
            ;;
        *)
            if [ ! -d "$destination" ]; then
                destdir="$(dirname "$destdir")"
            fi
            ;;
    esac
fi

mkdir -pv "$destdir"
git mv "$@"
