#!/bin/bash

git fetch origin
github-list-forks "$@" | while read -r remote url; do
    if ! git config "remote.$remote.url" >/dev/null; then
        git remote add "$remote" "$url"
    fi
    git remote set-url "$remote" "$url"
    git fetch "$remote"

    echo >&2 Pruning matching tracking branches for $remote
    git prune-merged -r "$remote" -c origin

    echo >&2 Pruning topic branches merged to master for $remote
    git prune-merged -r "$remote"
done
