#!/bin/bash

git fetch origin
github-list-forks | while read -r remote url; do
    if ! git config "remote.$remote.url"; then
        git remote add "$remote" "$url"
    fi
    git remote set-url "$remote" "$url"
    git fetch "$remote"

    # Prune matching tracking branches
    git prune-merged -r "$remote" -c origin

    # Prune merged topic branches
    git prune-merged -r "$remote"
done
