#!/bin/sh


usage() {
    cat <<END >&2
${0##*/} [options..] URL [URL..]

Options:
  -p PUP_ARGS
  -h   Show usage
END
    exit 2
}

pup_args=
while getopts p:h opt; do
    case "$opt" in
        p)
            pup_args="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

# shellcheck disable=SC2086
for url; do
    http --follow --check-status --ignore-stdin "$url" | pup-links "$url" $pup_args
done
