#!/usr/bin/env bash
# Interactively select file search results to edit
#   Uses g to search, fzf to select, vim to edit

set -euo pipefail

PATH="$(dirname "$0"):$PATH"
FZF_G_OPTS="$FZF_DEFAULT_OPTS ${FZF_G_OPTS:-"-m --preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"}"

# shellcheck disable=SC2086
g -c always -V "$@" | eval fzf --ansi $FZF_G_OPTS | vimerrors
