#! /usr/bin/env python

import i3ipc
import pgi
pgi.require_version('Notify', '0.7')
from pgi.repository import Notify

i3conn = i3ipc.Connection()
Notify.init('Urgent!')

def on_urgent(i3, event):
    urgent = find_urgent(i3.get_tree().descendents())
    if urgent:
        n = Notify.Notification.new(
            'Window %s:%s on workspace %s requires your attention' % (
                urgent.window_instance,
                urgent.name,
                urgent.workspace().name),
            None,
            "dialog-information")
        n.show()

def find_urgent(descendents):
    try:
        return next(c for c in descendents if c.urgent and c.type == 'con')
    except StopIteration:
        return None

i3conn.on('window::urgent', on_urgent)

i3conn.main()