#!/usr/bin/env python3

import i3ipc
import subprocess

i3conn = i3ipc.Connection()

def on_urgent(i3, event):
    urgent = find_urgent(i3.get_tree().descendents())
    if urgent:
        subprocess.run(['powershell.exe',
                        '-command', 'New-BurntToastNotification',
                        '-Text',
                        '"i3 Window %s:%s on workspace %s requires your attention"' % (
                            urgent.window_instance,
                            urgent.name,
                            urgent.workspace().name)])


def find_urgent(descendents):
    try:
        return next(c for c in descendents if c.urgent and c.type == 'con')
    except StopIteration:
        return None


i3conn.on('window::urgent', on_urgent)
i3conn.main()
