#!/bin/sh

pythonuserdir="$(python -c 'import site; print(site.getuserbase())')" || exit 1
PATH="$pythonuserdir/bin:$PATH"

pipv () {
    command pipv "$1" -U "$@"
}

pipv3 () {
    command pipv3 "$1" -U "$@"
}

pip_install () {
    command pip install --user --disable-pip-version-check -U "$@"
}

pip3_install () {
    command pip3 install --user --disable-pip-version-check -U "$@"
}

setup_pip () {
    python -m ensurepip --user
    python -m pip install --user --upgrade pip
    python -m pip install --user --upgrade virtualenv
    if which python3 >/dev/null 2>&1; then
        python3 -m ensurepip --user
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user --upgrade virtualenv
    fi
}


setup_pip

## Interactive mode python tools
pip_install see
pip3_install see

## General Tools & Utilities
brew install the_silver_searcher
brew install gnu-sed
brew install jq
go get -u github.com/monochromegane/the_platinum_searcher/... # or brew install pt
go get -u github.com/junegunn/fzf/... # or brew install fzf
go get -u github.com/edi9999/path-extractor/path-extractor
gemv mdless # Markdown syntax-highlighting pager
npmv tldr # or go get -u github.com/pranavraja/tldr
gemv boom

pipv pythonpy
pipv httpie
go get -u github.com/EricChiang/pup # or brew install pup
pip_install hg-git
pipv git-remote-dropbox
# Dropblame, constructs git history for individual files in dropbox, using
# dropbox's revision history.
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"
pipv dropblame &&
    mv "$WORKON_HOME/dropblame/bin/drop" "$WORKON_HOME/dropblame/bin/dropb" && \
    mv "$XDG_DATA_HOME/../bin/drop" "$XDG_DATA_HOME/../bin/dropb"

## For dotfiles
pipv3 peru

## Script dependencies
pip_install SOAPpy # lmwsaction
pip_install dropbox # git-remote-dropbox
pip_install titlecase # variety of scripts, and zsh alias
pip_install toml # toml-set/toml-get, used by the game scripts
pip_install sh # various scripts
pip_install hungarian # git-tbdiff
pipv json2yaml # pcposts zsh function
pip_install gitpython # buildhistory-diff

## Pinboard client
npmv pin-cushion

## Development Tools
go get -u github.com/github/hub
OPENSSL_DIR=/opt/homebrew/opt/openssl cargov git-series
# pprintpp + pp-ez?
# twine?
# wheel?
pip_install ptpython
pip_install pathlib2
pip_install click
pip_install e
pip3_install e
pip_install better-exceptions-hook
pip3_install better-exceptions-hook

## Documentation
gemv ronn
npmv doctoc

## Linting / Static Analysis
brew install shellcheck # or cabalv shellcheck or cabal install shellcheck
pipv flake8 flake8 pep8-naming flake8-docstrings
#pipv prospector
#pipv vim-vint
#luav luacheck
#gemv mdl # markdown
# see also markdownlint
# http://lua-users.org/wiki/LuaInspect ?
# https://code.google.com/archive/p/lua-checker/ ?
# go get github.com/BurntSushi/toml/cmd/tomlv # for toml, but it's out of date. it only supports 0.1.0

## Formatters
pipv yapf
# autopep8 - format code per pep8
# https://pypi.python.org/pypi/docformatter - format docstrings per pep257
go get -u github.com/shurcooL/markdownfmt
#npmv pretty-js
#luav formatter

## As Needed

#go get -u github.com/ddo/fast # bandwidth speed testing
#go get -u github.com/jbenet/go-multihash/multihash # If needed to create a hash for use by hashpipe
#go get -u github.com/jbenet/hashpipe
#pipv pockyt # cli for Pocket
#pipv pocket-cli # other cli for Pocket, better interface
#pip_install datefinder # search text for dates, ala path-extractor
#pip_install pipdeptree
#go get -u github.com/pengwynn/flint # check for missing license/etc for a project
# Seemingly no cli install for: terra (terralang.org)
#go get -u github.com/asciinema/asciinema # or brew install asciinema

### Elixir Development
# erlang is specifically listed to ensure its binaries are symlinked as well
# as the elixir binaries, so erl is available
#brewv elixir elixir erlang

### Lua Development
# luvi?
#luav moonscript
#luav busted

### StackOverflow from the commandline
#npmv how2

### Video Downloading
#pipv3 youtube-dl
