#!/bin/sh

set -eu

PATH="$HOME/.local/bin:$PATH"

if ! which ghc >/dev/null 2>&1 || ! which cabal >/dev/null 2>&1; then
    if ! which stack >/dev/null 2>&1; then
        curl -sSL https://raw.githubusercontent.com/commercialhaskell/stack/master/etc/scripts/get-stack.sh | sh -s - -d ~/.local/bin
    fi
fi

if which stack >/dev/null 2>&1; then
    stack update
    stack setup
    GHC="$(stack exec which ghc)"
    if [ -n "$GHC" ]; then
        ln -sfv "$GHC" ~/.local/bin/
    fi
    stack install cabal-install
fi

which cabal
