#!/bin/sh

: "${XDG_DATA_HOME:=~/.local/share}"
export NVM_DIR="$XDG_DATA_HOME/nvm" && (
    git clone https://github.com/creationix/nvm.git "$NVM_DIR"
    cd "$NVM_DIR"
    git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" origin)"
) && \. "$NVM_DIR/nvm.sh"
nvm install --lts
nvm alias default node
