#!/bin/sh

PATH=/usr/bin:/bin

pythonuserdir="$(python -c 'import site; print(site.getuserbase())')" || exit 1
PATH="$pythonuserdir/bin:$PATH"

curl https://bootstrap.pypa.io/get-pip.py | python - --user
if [ "$(which pip)" != "$pythonuserdir/bin/pip" ]; then
    echo >&2 "Error in pip installation"
    exit 1
fi
pip install --user --ignore-installed virtualenv
curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
