#!/bin/sh

export PYENV_ROOT="${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}"
PATH="$(dirname "$0"):$PYENV_ROOT/bin:$HOME/.local/bin:$PATH"

pyenv-installer
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv install 3.6.5
pyenv install 2.7.14
pyenv global 2.7.14 3.6.5
