#!/bin/sh
if [ $# -lt 1 ]; then
    echo >&2 "Usage: `basename $0` IPKFILE"
    exit 2
fi
if ar t "$1" | grep -qx data.tar.xz; then
    ar p "$1" data.tar.xz | tar -tvJ
else
    ar p "$1" data.tar.gz | tar -tvz
fi
ar p "$1" control.tar.gz | tar -tvz
