#!/bin/sh
if [ $# -lt 1 ]; then
    echo >&2 "Usage: `basename $0` IPKFILE"
    exit 2
fi

basepath="${1%.ipk}"
outdir="${basepath##*/}"
mkdir -p "$outdir/CONTROL"
if ar t "$1" | grep -qx data.tar.xz; then
    ar p "$1" data.tar.xz | tar -Jxvf - -C "$outdir"
else
    ar p $1 data.tar.gz | tar -zxvf - -C "$outdir"
fi || exit $?
ar p $1 control.tar.gz | tar -zxvf - -C "$outdir/CONTROL" || exit $?
echo >&2 "Extracted to '$outdir'."
