#!/usr/bin/env python3
# Given fdupes oneline output, output grouped multiline output like jdupes

import os
import sys


def main():
    first = True
    for line in sys.stdin:
        entries = line.strip('\r\n').split('\t')
        if first:
            first = False
        else:
            sys.stdout.write('\n')
        sys.stdout.writelines(entry.replace('\\ ', ' ') + '\n' for entry in entries)


if __name__ == '__main__':
    try:
        main()
        sys.stdout.flush()
    except BrokenPipeError:
        # Python flushes standard streams on exit; redirect remaining output
        # to devnull to avoid another BrokenPipeError at shutdown
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, sys.stdout.fileno())
        sys.exit(1)  # Python exits with error code 1 on EPIPE
