#!/usr/bin/env python3
# Given fdupes oneline output, output grouped multiline output like jdupes

import sys

first = True
for line in sys.stdin:
    entries = line.strip('\r\n').split('\t')
    if first:
        first = False
    else:
        sys.stdout.write('\n')
    sys.stdout.writelines(entry.replace('\\ ', ' ') + '\n' for entry in entries)
