#!/usr/bin/env python3
# Given multiline dupe output, remove any missing files

import os
import sys

for line in sys.stdin:
    line = line.rstrip('\r\n')
    if not line or os.path.exists(line):
        print(line)
