#!/usr/bin/env python3
"""Adjust jdupes output to match fdupes oneline output."""

import os
import sys


def main():
    """Adjust jdupes output to match fdupes oneline output."""
    block = []
    for line in sys.stdin:
        line = line.rstrip('\r\n')
        if not line:
            if block:
                print('\t'.join(block))
            block.clear()
        else:
            block.append(line.replace(' ', '\\ '))

    if block:
        print('\t'.join(block))


if __name__ == '__main__':
    try:
        main()
        sys.stdout.flush()
    except BrokenPipeError:
        # Python flushes standard streams on exit; redirect remaining output
        # to devnull to avoid another BrokenPipeError at shutdown
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, sys.stdout.fileno())
        sys.exit(1)  # Python exits with error code 1 on EPIPE
