#!/usr/bin/env python3
# Given multiline dupe output, remove any with a single entry

import os
import sys


def print_block(block, first):
    if len(block) > 1:
        if not first:
            sys.stdout.write('\n')
        sys.stdout.writelines(block)
        return True


def main():
    first, block = True, []
    for line in sys.stdin:
        if not line.rstrip('\r\n'):
            if print_block(block, first):
                first = False
            block.clear()
        else:
            block.append(line)

    if block:
        print_block(block, first)


if __name__ == '__main__':
    try:
        main()
        sys.stdout.flush()
    except BrokenPipeError:
        # Python flushes standard streams on exit; redirect remaining output
        # to devnull to avoid another BrokenPipeError at shutdown
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, sys.stdout.fileno())
        sys.exit(1)  # Python exits with error code 1 on EPIPE
