#!/usr/bin/env python3
# Given the output of jdupes, adjust to match fdupes oneline output, to use
# with postprocessing scripts like my own fdupes-select

import sys

block = []
for line in sys.stdin:
    line = line.rstrip('\r\n')
    if not line:
        if block:
            print('\t'.join(block))
        block.clear()
    else:
        block.append(line.replace(' ', '\\ '))

if block:
    print('\t'.join(block))
