#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

chroot=$1

uid=$(id -u)
if [ $uid -ne 0 ]; then
    exec sudo env OLDUSER=$USER PASSLINE="$USER::$(id -u):$(id -g)::$HOME:/bin/sh" $0 "$@"
elif [ -z "$OLDUSER" ]; then
    OLDUSER=$USER
    PASSLINE="$USER::$(id -u):$(id -g)::$HOME:/bin/sh"
fi

copyfiles="/etc/passwd /etc/shadow /etc/group /etc/sudoers /etc/hostname /etc/resolv.conf /etc/hosts"
mountpaths="/dev /dev/pts /sys /proc /home /scratch"

for file in $copyfiles; do
    if [ -e "$file" ]; then
        mkdir -p $(dirname $chroot/$file)
        cp -f $file $chroot/$file
    fi
done

for path in $mountpaths; do
    mkdir -p $chroot/$path
    mount -o bind $path $chroot/$path
done

set -x

if ! grep -q "^$OLDUSER:" $chroot/etc/passwd; then
    echo "$PASSLINE" >> $chroot/etc/passwd
fi

if ! grep -q "^$OLDUSER" $chroot/etc/sudoers; then
    echo "$OLDUSER ALL=(ALL) ALL" >> $chroot/etc/sudoers
fi

chroot $chroot sudo -u $OLDUSER /bin/sh

for path in $mountpaths; do
    umount $chroot/$path
done
