#!/bin/sh
# - Accept file paths on stdin
# - Accept the identifier command via command-line argument
# - Output files grouped by the identifier
#
# NOTE: Currently assumes the command will output '<id><TAB
# CHARACTER><filename>' lines

PATH=$(dirname "$0"):$PATH
TAB=$(printf '\t')

usage() {
    cat <<END >&2
${0##*/} [options..] [CMD [ARGS..]]

Options:
  -a   Also show non-duplicates
  -h   Show usage
END
    exit 2
}

all=0
while getopts ah opt; do
    case "$opt" in
        a)
            all=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if echo "$*" | grep -q '{}'; then
    set -- -I"{}" "$@"
fi

remove_nondupes() {
    jdupes-oneline | sed -e "s/$TAB*$//" | grep "$TAB" | jdupes-multiline
}

if [ $# -gt 0 ]; then
    tr '\n' '\0' \
        | xargs -0 "$@"
else
    cat
fi \
    | grep -v "^ *$TAB" \
    | sort -t"$TAB" -k1 \
    | group-by-column 1 "$TAB" \
    | cut -d"$TAB" -f2- \
    | if [ $all -eq 1 ]; then
        cat
    else
        remove_nondupes
    fi
