#!/bin/sh

set -e

delays=1,2,0,0

dsleep () {
    delay="$(echo "$delays" | cut -d, -f"$1")"
    if [ -n "$delay" ] && [ "$delay" -ne "0" ]; then
        sleep "$delay"
    fi
}

kkill () {
    kkill_sig=$1
    shift
    # ps -p"$(pgrep "$@" | grep -vx "$$" | tr '\n' ',')"
    pgrep "$@" | grep -vx "$$" | tr '\n' '\0' | xargs -0 kill "-$kkill_sig" 2>/dev/null
}

kgrep_if () {
    test -n "$(pgrep 2>/dev/null "$@" | grep -vx "$$")"
}

pgrep () {
    command pgrep -U "$uid" "$@"
}

uid=$(id -u)

kkill TERM "$@"
if kgrep_if "$@"; then
    dsleep 1
    if kgrep_if "$@"; then
        echo >&2 "Process(es) still running, waiting.."
        dsleep 2
        if kgrep_if "$@"; then
            echo >&2 "Process(es) still running, using pkill -9.."
            kkill KILL "$@"
            dsleep 3
            pids="$(pgrep -f "$*" 2>/dev/null | grep -vx "$$")"
            if [ -z "$pids" ]; then
                exit 0
            fi
            echo >&2 "Process(es) still running after pkill -9, using kill -9.."
            for pid in $pids; do
                kill -9 "$pid" || :
            done
            dsleep 4
            if kgrep_if "$@"; then
                echo >&2 "Error: process(es) still running after kill -9"
                exit 1
            fi
        fi
    fi
fi
