#!/bin/sh
#
# Based on https://gist.github.com/rnapier/3370649, by Rob Napier
# <robnapier@gmail.com>, rewritten from scratch in
# shell by Christopher Larson <kergoth@gmail.com>
#
# Script to link in all your old SDKs every time you upgrade Xcode
#
# Create a directory called /SDKs (or point to it with -s)
# Under it, put all the platform directories:
#	MacOSX.platform          iPhoneOS.platform        iPhoneSimulator.platform
# Under those, store the SDKs:
#	MacOSX10.4u.sdk MacOSX10.5.sdk  MacOSX10.6.sdk  MacOSX10.7.sdk  MacOSX10.8.sdk

sdk_path=/SDKs
while getopts s:h opt; do
    case "$opt" in
        s)
            sdk_path="$OPTARG"
            ;;
        \?|h)
            echo >&2 "${0##*/} [-s SDKPATH]"
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ ! -d "$sdk_path" ]; then
    echo >&2 "Error: SDK path $sdk_path does not exist"
    exit 2
fi

xcode_path="$(xcode-select --print-path)"

for platform in "$sdk_path"/*.platform; do
    platform="${platform#$sdk_path/}"
    for sdk in "$sdk_path/$platform/"*.sdk; do
        dest="$xcode_path/Platforms/$platform/Developer/SDKs/${sdk##*/}"
        if [ ! -d "$dest" ] || [ -h "$dest" ]; then
            sudo rm -f "$dest"
            sudo ln -s "$sdk" "$dest"
        fi
    done
done
