#!/bin/sh

if [ $# -eq 0 ]; then
    echo >&2 "${0##*/} source_path alias_path"
    echo >&2 "${0##*/} source_path existing_destdir"
    echo >&2 "${0##*/} source_path destdir/"
    exit 0
fi

dest=
source_path="$1"
dest_dir="$2"

case "$dest_dir" in
    */)
        dest="$dest_dir/$(basename "$source_path")"
        ;;
    *)
        if [ -d "$dest_dir" ]; then
            dest="$dest_dir/$(basename "$source_path")"
        fi
        ;;
esac

if [ -z "$dest" ]; then
    dest="$dest_dir"
    dest_dir="$(dirname "$dest")"
fi

osascript <<END
tell application "Finder"
    make new alias at POSIX file "$dest_dir" to POSIX file "$source_path"
end tell
END

if [ "$dest" != "$dest_dir/$(basename "$source_path")" ]; then
    mv "$dest_dir/$(basename "$source_path")" "$dest"
fi
