#!/bin/sh

usage () {
    echo >&2 "Usage: ${0##*/} URL [FILENAME]"
    exit 2
}

if [ $# -lt 1 ]; then
    usage
fi

url="$1"
if [ $# -lt 2 ]; then
    if which curl >/dev/null 2>&1 && which pup >/dev/null 2>&1; then
        title="$(curl -Ls "$url" | pup 'title text{}' | tr '/\n"' ' ')"
        if [ -n "$title" ]; then
            filename="$(echo "$title" | sed 's,:, - ,g; s,^ *,,; s, *$,,; s,   *, ,g')"
        fi
    fi
    if [ -z "$filename" ]; then
        echo >&2 "Unable to default filename based on page title, please specify."
        usage
    fi
else
    filename="$2"
fi
filename="${filename%.webloc}.webloc"
/usr/libexec/PlistBuddy -c "Add URL string '$(printf "%s" "$1" | sed "s/'/\\\\'/g")'" "$filename"
