#!/bin/sh
# Install packages into isolated environments for npm/node, then link/wrap
# binaries/scripts into $XDG_DATA_HOME/../bin

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
NPMENV_HOME="${NPMENV_HOME:-$XDG_DATA_HOME/npm_envs}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} NPMENV_NAME [NPM_INSTALL_ARGS..]"
    echo >&2
    echo >&2 "Existing isolated homebrew installations:"
    for dir in "$NPMENV_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

npmenv="$1"
shift
npmenv_dir="$NPMENV_HOME/$npmenv"
mkdir -p "$npmenv_dir/bin"
cat >"$npmenv_dir/bin/activate" <<END
PATH="$npmenv_dir/bin:\$PATH"
export MANPATH="$npmenv_dir/share/man:\$(manpath)"
export NODE_PATH="$npmenv_dir/lib/node_modules:\$NODE_PATH"
END
. "$npmenv_dir/bin/activate"

# To install npm, if we have node but not npm
if ! which node >/dev/null 2>&1; then
    if which nodejs >/dev/null 2>&1; then
        ln -s $(which nodejs) "$npmenv_dir/bin/node"
    else
        echo >&2 "Error: Node.js must be installed to install npm"
        exit 1
    fi
fi
if ! which npm >/dev/null 2>&1; then
    if which hashpipe >/dev/null 2>&1; then
        curl -L https://npmjs.org/install.sh | hashpipe QmPXLdPeNdQSFn9W9wJyFv71cNvrwEuRdcjpCMrXvxi1xs | npm_config_prefix="$npmenv_dir" sh
    else
        curl -L https://npmjs.org/install.sh | npm_config_prefix="$npmenv_dir" sh
    fi
fi


if [ $# -eq 0 ]; then
    set -- "$npmenv"
fi
npm install -g --prefix="$npmenv_dir" "$@"
if [ $(find "$npmenv_dir/bin" -type l | wc -l) = 0 ]; then
    echo >&2 "Error: no binaries exist after installation, aborting"
    rm -r "$npmenv_dir"
    exit 1
fi

dest="$XDG_DATA_HOME/../bin"
mkdir -p "$dest"

for bin in "$npmenv_dir/bin/"*; do
    if [ -e "$bin" ]; then
        filename="${bin##*/}"
        case "$filename" in
            activate|npm|node):
                continue
                ;;
        esac

        rm -f "$dest/$filename"
        cat >"$dest/$filename" <<END
. "$npmenv_dir/bin/activate"
exec "$npmenv_dir/bin/$filename" "\$@"
END
        chmod u+x "$dest/$filename"
        echo >&2 "Created wrapper script at $dest/$filename"
    fi
done
