#!/bin/sh

case "$OSTYPE" in
    darwin*)
        if which reattach-to-user-namespace >/dev/null 2>&1; then
            exec reattach-to-user-namespace /usr/bin/pbcopy "$@"
        else
            exec /usr/bin/pbcopy "$@"
        fi
        ;;
    *)
        if which xsel >/dev/null 2>&1; then
            exec xsel --clipboard --input "$@"
        else
            exec xclip -selection clipboard "$@"
        fi
        ;;
esac
