#!/bin/sh

case "$OSTYPE" in
    darwin*)
        if which reattach-to-user-namespace >/dev/null 2>&1; then
            exec reattach-to-user-namespace /usr/bin/pbpaste "$@"
        else
            exec /usr/bin/pbpaste "$@"
        fi
        ;;
    *)
        if which win32yank >/dev/null 2>&1; then
            # WSL
            exec win32yank -o
        elif which paste.exe >/dev/null 2>&1; then
            # WSL
            exec paste.exe
        elif which xsel >/dev/null 2>&1; then
            exec xsel --clipboard --output "$@"
        else
            exec xclip -selection clipboard -o "$@"
        fi
        ;;
esac
