#!/bin/sh
# Install packages into a virtualenv with pip, then symlink any scripts into
# $XDG_DATA_HOME/../bin.

XDG_DATA_HOME="${XDG_DATA_HOME:-~/.local/share}"
WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} VENV_NAME [PIP_ARGS..]"
    echo >&2
    echo >&2 "Existing environments (both python 2 and 3):"
    for dir in "$WORKON_HOME"/*/; do
        if [ -e "$dir" ]; then
            printf >&2 '  %s\n' "$(basename "${dir%/}")"
        fi
    done
    exit 2
fi

venv="$1"
shift
venv_dir="$WORKON_HOME/$venv"
if [ ! -e "$venv_dir" ]; then
    virtualenv "$venv_dir"
fi
. "$venv_dir/bin/activate"

if [ $# -eq 0 ]; then
    set -- "$venv"
fi
pip install "$@"

mkdir -p "$XDG_DATA_HOME/../bin"
for script in "$venv_dir/bin/"*; do
    filename="${script##*/}"
    case "$filename" in
        python*|pydoc*|virtualenv*|pip*|easy_install*|activate*|wheel):
            continue
            ;;
    esac

    link_name="$XDG_DATA_HOME/../bin/$filename"
    printf >&2 '’%s’ -> ’%s’\n' "$link_name" "$script"
    cat >"$link_name" <<END
#!/bin/bash
. "$venv_dir/bin/activate"
exec "$venv_dir/bin/\${0##*/}" "\$@"
END
    chmod +x "$link_name"
done
