#!/bin/sh
# Install packages into a virtualenv with pip, then symlink any scripts into
# $XDG_DATA_HOME/../bin.

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} VENV_NAME [PIP_ARGS..]"
    exit 2
fi

venv="$1"
shift
XDG_DATA_HOME="${XDG_DATA_HOME:-~/.local/share}"
WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"
venv_dir="$WORKON_HOME/$venv"
if [ ! -e "$venv_dir" ]; then
    virtualenv "$venv_dir"
fi
. "$venv_dir/bin/activate"

if [ $# -eq 0 ]; then
    set -- "$venv"
fi
pip install "$@"

mkdir -p "$XDG_DATA_HOME/../bin"
for script in "$venv_dir/bin/"*; do
    filename="${script##*/}"
    case "$filename" in
        python*|pydoc*|virtualenv*|pip*|easy_install*|activate*):
            continue
            ;;
    esac
    ln -sfv "$script" "$XDG_DATA_HOME/../bin/$filename"
done
