#!/bin/sh
# Install packages into a virtualenv with pip, then symlink any scripts into
# $XDG_DATA_HOME/../bin.

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
WORKON_HOME="${WORKON_HOME:-$XDG_DATA_HOME/virtualenvs}"

if [ $# -eq 0 ]; then
    echo >&2 "Usage: ${0##*/} VENV_NAME [PIP_ARGS..]"
    echo >&2
    echo >&2 "Existing environments (both python 2 and 3):"
    for dir in "$WORKON_HOME"/*/; do
        printf >&2 '  %s\n' "$(basename "${dir%/}")"
    done
    exit 2
fi

venv="$1"
case "$venv" in
    -*)
        echo >&2 "Error: venv starts with -: $venv"
        exit 1
        ;;
esac

venv_dir="$WORKON_HOME/$venv"
if [ ! -e "$venv_dir" ]; then
    python3 -m venv "$venv_dir" || exit 3
    . "$venv_dir/bin/activate" || exit 4
    pip install -U pip || :
fi
"$(dirname "$0")"/pipv "$@"
