#!/bin/bash
#
# Email me if my pocket article count has gone up since the last time the
# script was run

set -euo pipefail

: "${XDG_DATA_HOME:=~/.local/share}"
: "${EMAIL:=${DEBEMAIL:=$(git config user.email 2>/dev/null)}}"
if [ -z "$EMAIL" ]; then
    echo >&2 "Error: unable to determine email, please set EMAIL"
    exit 1
fi
name="${0##*/}"
datadir="$XDG_DATA_HOME"
cfg="$datadir/$name.toml"

mkdir -p "$datadir"
touch "$cfg"

article_count="$(toml-get "article-count" 2>/dev/null <"$cfg")"
tags="$(toml-get "count-tags" 2>/dev/null <"$cfg")"
query_tags="$(toml-get "query-tags" 2>/dev/null <"$cfg")"

if [ -n "$tags" ]; then
    set -- -t "$tags"
else
    set --
fi

tmp="$(mktemp -t "$name.XXXXXX")" || exit 1
pocket-search-formatted "$@" >"$tmp"
new_article_count=$(wc -l <"$tmp")
if [ -z "$article_count" ] || [ $new_article_count -gt $article_count ]; then
    if [ -n "$query_tags" ]; then
        set -- -t "$query_tags"
    else
        set --
    fi
    pocket-search-formatted "$@" | mail -s "Pocket article count grew from $article_count to $new_article_count" "$EMAIL"
    toml-set -f "$cfg" article-count "$new_article_count"
fi
