#!/usr/bin/env python3

import os
import sys
from configparser import ConfigParser
from pocket import Pocket

config = ConfigParser()
with open(os.path.expanduser('~/.pocket-config')) as f:
    config.readfp(f)

key = config.get('pocket', 'consumer_key')
token = config.get('pocket', 'access_token')

id = sys.argv[1]
tags = sys.argv[2:]
pocket = Pocket(key, token)
pocket.tags_remove(int(id), tags).commit()
