#!/bin/sh

set -eu

if [ $# -ne 0 ]; then
    destdir="$1"
elif [ -e /Volumes/video/To\ Watch ]; then
    destdir="/Volumes/video/To Watch"
else
    destdir="$HOME/Downloads"
fi

echo >&2 "Downloading to $destdir"
cd "$destdir"
pocket-cli search -s unread -t watch -o newest '' | \
    pocket-cli-join-entries | \
    grep -v '/user/' | \
    while read -r id url _; do
        youtube-dl --convert-subs srt --write-sub --write-auto-sub --embed-subs --no-playlist "$url" && pocket-cli archive "$id"
    done
