#!/bin/sh
# Get a list of process ids which match the provided pattern, excluding the
# current process, and pass all their session IDs to ps.

pids="$(pgrep -f "$*" | grep -vx "$$")"

if [ -z "$pids" ]; then
    echo >&2 "No processes found for" "$@"
    exit 1
fi

sids=
for pid in $pids; do
    if [ -e "/proc/$pid/stat" ]; then
        read procpid name state ppid pgid sess rest </proc/$pid/stat
        sids="$sids $sess"
    fi
done
sids="$(echo $sids | sed "s,^ ,," | tr " " ",")"
if [ -n "$sids" ]; then
    set -- --sid "$sids"
else
    set --
fi

pids="$(echo $pids | tr " " ",")"
exec ps fu --pid "$pids" --ppid "$pids" "$@"
