#!/usr/bin/env python

import sys
try:
    import cPickle as pickle
except ImportError:
    import pickle
try:
    import pprintpp as pprint
except ImportError:
    import pprint


def iter_except(func, exception, start=None):
    'Yield a function repeatedly until it raises an exception'
    try:
        if start is not None:
            yield start()
        while 1:
            yield func()
    except exception:
        pass


if len(sys.argv) < 2:
    sys.exit('Usage: dump-pickle FILENAME')

filename = sys.argv[1]
with open(filename, 'rb') as f:
    p = pickle.Unpickler(f)
    for loaded in iter_except(p.load, EOFError):
        pprint.pprint(loaded)
