#!/bin/sh
# Get a list of process ids which match the provided pattern, excluding the
# current process, and pass that process list to ps.

pids="$(pgrep -f "$@"|grep -vx "$$")"
pids="$(echo $pids|sed -e's/ /,/g')"

if [ -z "$pids" ]; then
    echo >&2 "No processes found for" "$@"
    exit 1
fi

if echo $OSTYPE | grep -q "^darwin"; then
    exec ps u -p"$pids"
else
    exec ps fu -p"$pids"
fi
