#!/bin/sh
# Get a list of process ids which match the provided pattern, excluding the
# current process, and pass that process list to ps.

pids="$(pgrep -f "$*" | grep -vx "$$")"
pids="$(echo $pids | tr " " ",")"

if [ -z "$pids" ]; then
    echo >&2 "No processes found for" "$@"
    exit 1
fi

case "$(uname -s)" in
    Darwin)
        exec ps u -p"$pids"
        ;;
    *)
        exec ps fu -p"$pids"
        ;;
esac
