#!/usr/bin/env python3

import os
import sys

args = sys.argv[1:]
if len(args) < 1 or len(args) > 2:
    sys.stderr.write('Usage: relpath PATH [START]\n')
    sys.stderr.write('\n')
    sys.stderr.write('Returns a relative version of PATH.')
    sys.exit(2)

if len(args) == 2:
    first, second = args
else:
    first, second = args[0], '.'
first, second = os.path.realpath(first), os.path.realpath(second)

common_prefix = os.path.commonprefix([first, second])
if common_prefix == '/':
    sys.stderr.write("Warning: common prefix of '%s' and '%s' is /\n" % (first, second))

print(os.path.relpath(first, second))
