#!/bin/sh

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo >&2 "Usage: relpath PATH [START]"
    echo >&2
    echo >&2 "Returns a relative version of PATH."
    exit 2
fi

python -c "import os, sys; print(os.path.relpath(*sys.argv[1:]))" "$@"
