#!/bin/sh

if which gfind >/dev/null 2>&1; then
    alias find=gfind
fi

if [ "$1" = "-n" ]; then
    dry_run=1
    shift
else
    dry_run=
fi

if [ $# -eq 0 ]; then
    set -- .
fi

{
    find "$@" -type d -name @eaDir
    find "$@" -type f -name .DS_Store
    find "$@" -type f -name 'Icon
    '
    find "$@" -type f -empty
    find "$@" -type d -empty
} |
    awk '!visited[$0]++' |
    grep -Ev '/\.stfolder|/\.git/|/\.placeholder|\.gitkeep|\.[^.]*/' |
    tr '\n' '\0' |
    xargs -0 ${dry_run:+echo }rm -rfv
