#!/bin/sh
#
# Replace a symlink with a copy of its destination

while getopts r:h opt; do
    case "$opt" in
        r)
            relativeto="$OPTARG"
            ;;
        \?|h)
            usage
            echo >&2 "${0##*/}: [-r RELATIVETO] PATH [PATH..]"
            ;;
    esac
done
shift $((OPTIND - 1))

backup=$(mktemp resolvelink.XXXX)
trap 'rm -f "$backup"' EXIT INT TERM

ret=1
for link; do
    if [ -n "$relativeto" ]; then
        link_relativeto="$relativeto"
    else
        link_relativeto="$(dirname "$link")"
    fi
    dest="$(abspath -r "$link_relativeto" "$(readlink "$link")")"

    if [ -z "$dest" ]; then
        echo >&2 "No destination found for $link, skipping"
        ret=1
        continue
    elif [ ! -e "$dest" ]; then
        printf >&2 'Destination `%s` for `%s` does not exist, skipping\n' "$dest" "$link"
        ret=1
        continue
    fi

    mv "$link" "$backup"
    cp -av "$dest" "$link" || {
        ret=$?
        echo >&2 "Restoring original link for $link"
        mv "$backup" "$link"
    }
done
exit $ret
