#!/bin/sh

show_original=0
while getopts oh opt; do
    case "$opt" in
        o)
            show_original=1
            ;;
        \?|h)
            usage
            echo >&2 "${0##*/}: [-o] PATH [PATH..]"
            ;;
    esac
done
shift $((OPTIND - 1))

abspath () {
    testabs=${1##[!/]*}
    echo ${testabs:-$PWD/$1}
}

finder_resolve_alias () {
    script="$(printf 'tell application "Finder" to get the posix path of (original item of (POSIX file "file://%s" as alias) as text)' "$(abspath "$1")")"
    osascript -e "$script"
}

if which aliasPath >/dev/null 2>&1; then
    resolve () {
        resolved="$(aliasPath "$1")"
        if [ -z "$resolved" ] || [ ! -e "$resolved" ]; then
            resolved="$(finder_resolve_alias "$1")" || return $?
        fi
        echo "$resolved"
    }
else
    resolve () {
        finder_resolve_alias "$1"
    }
fi

ret=0
for alias; do
    resolved="$(resolve "$alias")" || ret=$?
    if [ "$show_original" -eq 1 ]; then
        printf '%s\t%s\n' "$alias" "$resolved"
    else
        printf '%s\n' "$resolved"
    fi
done
exit $ret
