#!/bin/sh
#
# Replace a symlink with a copy of its destination

if [ $# -eq 0 ]; then
    echo >&2 "Usage: $0 FILENAME [FILENAME...]"
    exit 2
fi

backup=$(mktemp resolvelink.XXXX)
trap "rm -f \"$backup\"" EXIT INT TERM

ret=1
for link; do
    dest="$(readlink "$link")"
    if [ -z "$dest" ]; then
        echo >&2 "No destination found for $link, skipping"
        ret=1
        continue
    fi

    mv "$link" "$backup"
    cd "${link%/*}"
    cp -av "$dest" "${link##*/}" || {
        ret=$?
        echo >&2 "Restoring original link for $link"
        mv "$backup" "$link"
    }
    cd - >/dev/null
done
exit $ret
