#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
repodir=$(dirname "$scriptdir")
PATH="$scriptdir/macos:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

if ! [ -x "$HOMEBREW_PREFIX/bin/brew" ]; then
    msg "Installing homebrew"
    run install-brew -s "$HOMEBREW_PREFIX" || {
        rm -rf "$HOMEBREW_PREFIX"
        die "Failed to install homebrew"
    }
fi

msg "Installing applications with homebrew"
unset HOMEBREW_AUTO_UPDATE
export HOMEBREW_NO_AUTO_UPDATE=1

brewfile_install "$scriptdir/macos/Brewfile"

if [ "$(sw_vers -productVersion | cut -d. -f1)" -lt 14 ]; then
    brewfile_install "$scriptdir/macos/Brewfile-pre-Sonoma"
fi

# Dotfiles
if [ -z "${CHEZMOI:-}" ]; then
    "$repodir/script/setup"
fi

# Install UV for python tooling
if ! [ -e ~/.local/bin/uv ] || ! [ -e ~/.local/bin/uvx ]; then
    run sh -c 'curl -LsSf https://astral.sh/uv/install.sh | sh'
fi

# Install PowerShell modules and prompt, if needed
if has pwsh; then
    msg "Installing PowerShell modules"
    # Ignore failure, as these are not critical to my workflow, and can fail due
    # to transient network issues.
    run pwsh -NoProfile "$scriptdir/install-pwsh-modules.ps1" || :

    if ! brew list --formula | grep -qFx starship; then
        msg "Installing PowerShell prompt"
        run "$HOMEBREW_PREFIX/bin/brew" install starship
    fi
fi

# shellcheck disable=SC2046
if [ -d ~/.ssh/keys ] && [ $(find ~/.ssh/keys -maxdepth 1 -type f -not -name '*.pub' | wc -l) -gt 0 ]; then
    msg "Adding SSH keys to keychain"
    find ~/.ssh/keys -maxdepth 1 \( -type f -not -name '*.pub' -not -name '*.ppk' -not -name .DS_Store \) |
        while read -r key; do
            if ! [ -e "$key.pub" ]; then
                run ssh-keygen -y -f "$key" >"$key.pub"
            fi
            if ! ssh-add -T "$key.pub"; then
                run ssh-add --apple-use-keychain "$key" || :
            fi
        done
fi

msg "Configuring"
"$scriptdir/macos/configure"
"$scriptdir/macos/setup-apps"

msg "Configuring complete"
