#!/bin/sh

set -e

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
repodir=$(dirname "$scriptdir")
PATH="$scriptdir/freebsd:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

uv_check git-revise git-revise
uv_check git-imerge git-imerge
cargo_check choose choose
cargo_check atuin atuin

{{ if .work -}}
# Bug tracking and workflow
go_check github.com/ankitpokhrel/jira-cli/...@latest jira
{{- end }}

# As we don't support nix, install asdf for local environments
if ! command -v asdf >/dev/null 2>&1; then
    install-asdf
fi

# Installation
uvs_install
cargos_install
gos_install

# Dotfiles
if [ -z "${CHEZMOI:-}" ]; then
    "$repodir/script/setup"
fi

# User shell
if [ -e /usr/local/bin/zsh ]; then
    current_shell="$(getent passwd "$USER" | sed -e 's#.*:##')"
    if [ "$current_shell" != /usr/local/bin/zsh ]; then
        msg "Changing current user shell to zsh"
        chsh -s /usr/local/bin/zsh
    fi
fi
