#!/bin/sh

if [ $# -ne 0 ]; then
    HOMEBREW_PATH="$(cd "$1" && pwd)"
else
    HOMEBREW_PATH="${HOMEBREW_PATH:-/opt/homebrew}"
fi
PATH="$HOMEBREW_PATH/bin:$PATH"

if [ ! -e "$HOMEBREW_PATH" ]; then
    sudo mkdir -p "$HOMEBREW_PATH" && \
        sudo chown $USER "$HOMEBREW_PATH" && \
            curl -L https://github.com/Homebrew/homebrew/tarball/master | \
                tar xz --strip 1 -C "$HOMEBREW_PATH"
    brew update
    brew doctor
fi

# Ensure that pbcopy/pbpaste work from tmux, etc
$HOMEBREW_PATH/bin/brew install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste

brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/binary
brew tap homebrew/games
brew tap homebrew/headonly
brew tap homebrew/python
brew tap caskroom/cask
brew tap caskroom/fonts
brew tap caskroom/unofficial
brew tap caskroom/versions
brew tap monochromegane/pt

brew install fish
brew install apple-gcc42

# For 'att'
brew install abduco dvtm
brew install the_silver_searcher
brew install mercurial git
brew install dylibbundler
brew install tag

brew install brew-cask

brew install lftp
brew install p7zip
brew install wget
brew install csup
brew install ranger
