#!/bin/sh
#
# Sets reasonable OS X defaults.
#
# Pulled from https://github.com/holman/dotfiles
#
# The original idea (and a couple settings) were grabbed from:
#   https://github.com/mathiasbynens/dotfiles/blob/master/.osx

PATH="$(dirname "$0"):$PATH"

# Disable press-and-hold for keys in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Use AirDrop over every interface. srsly this should be a default.
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1

# Stop full names from copying with email addresses in Mail.app
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# Always open everything in Finder's list view. This is important.
defaults write com.apple.finder FXPreferredViewStyle Nlsv

# Enable quit menu item for Finder
defaults write com.apple.finder QuitMenuItem -bool true

# Enable text selection in quick look windows
defaults write com.apple.finder QLEnableTextSelection -bool true

# Hide desktop icons completely
defaults write com.apple.finder CreateDesktop -bool false

# Remove autohide dock delay
defaults write com.apple.dock autohide-delay -float 0

# Speed up mission control animations
defaults write com.apple.dock expose-animation-duration -float 0.12

# Make hidden dock icons translucent
defaults write com.apple.dock showhidden -bool true

defaults write com.apple.iTunes allow-half-stars -bool TRUE


# Show the ~/Library folder
chflags nohidden ~/Library

# Show system info at the login screen
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Kill Skype's splash screen
defaults write com.skype.skype SKShowSplash NO

sudo sh -c "echo kern.sysv.shmall=65536 >>/etc/sysctl.conf"
sudo sh -c "echo kern.sysv.shmmax=16777216 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfiles=10485760 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfilesperproc=1048576 >>/etc/sysctl.conf"
sudo sh -c "sort -u /etc/sysctl.conf >/tmp/foo && mv /tmp/foo /etc/sysctl.conf"
sudo sysctl -w $(cat /etc/sysctl.conf)

killall Finder
killall Dock

HOMEBREW_PATH="${HOMEBREW_PATH:-/opt/homebrew}"
PATH="$HOMEBREW_PATH/bin:$PATH"
if [ ! -e "$HOMEBREW_PATH" ]; then
    sudo mkdir -p "$HOMEBREW_PATH" && \
        sudo chown $USER "$HOMEBREW_PATH" && \
            curl -L https://github.com/Homebrew/homebrew/tarball/master | \
                tar xz --strip 1 -C "$HOMEBREW_PATH"
    brew update
    brew doctor
fi
if [ ! -e /etc/paths.d/homebrew ]; then
    sudo sh -c "echo \"$HOMEBREW_PATH/bin\" >/etc/paths.d/homebrew"
fi
if [ ! -e /etc/manpaths.d/homebrew ]; then
    sudo sh -c "echo \"$HOMEBREW_PATH/share/man\" >/etc/manpaths.d/homebrew"
fi

sudo mkdir -p /usr/local /opt
sudo chgrp -R staff /usr/local /opt
sudo find /usr/local /opt -type d -exec chmod g+wXs "{}" \;
sudo find /usr/local /opt -not -type d -exec chmod g+wX "{}" \;

# Ensure that pbcopy/pbpaste work from tmux, etc
$HOMEBREW_PATH/bin/brew install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste

# launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
