#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
PATH="$scriptdir/macos:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

if ! [ -e /nix ]; then
    install_nix
fi

if ! [ -x "$HOMEBREW_PREFIX/bin/brew" ]; then
    msg "Installing homebrew"
    install-brew -s "$HOMEBREW_PREFIX" || {
        rm -rf "$HOMEBREW_PREFIX"
        die "Failed to install homebrew"
    }
fi

msg "Installing applications with homebrew"
# shellcheck disable=SC2154
"$HOMEBREW_PREFIX/bin/brew" bundle --no-upgrade install --file="$scriptdir/macos/Brewfile.admin"

CASKROOM="$("$HOMEBREW_PREFIX/bin/brew" --caskroom)"
if [ -d "$CASKROOM"/whatsyoursign ]; then
    find "$CASKROOM"/whatsyoursign -name WhatsYourSign\ Installer.app -print0 \
        | xargs -0 open || :
fi

install-oversight

# Configuration
"$scriptdir/macos/configure-admin"
