#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
PATH="$scriptdir/debian:$scriptdir/linux:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

need_sudo

# Install xz for nix
if ! has xz; then
    sudorun apk add --no-interactive xz
fi

if ! has zsh; then
    sudorun apk add --no-interactive zsh
fi
