#!/bin/sh

pythonver="$(python -V 2>&1|cut -d" " -f2|cut -d. -f1-2)"
if [ -z "$pythonver" ]; then
    echo >&2 "Error getting python version from 'python -V'"
    exit 1
fi
pythondir="$HOME/Library/Python/$pythonver"
PATH="$pythondir/bin:$PATH"

# Install new setuptools (formerly distribute)
curl https://bootstrap.pypa.io/ez_setup.py | python - --user

# Install pip
curl https://bootstrap.pypa.io/get-pip.py | python - --user
if ! which pip >/dev/null 2>&1; then
    echo >&2 "Error: after installing pip, we are not able to execute it"
    exit 2
fi

echo '/opt/homebrew/lib/python2.7/site-packages' >$pythondir/lib/python/site-packages/homebrew.pth

# Convenient pretty-printing
pip install --user pprintpp pp-ez
# For ebook processing
pip install --user titlecase
# For a number of little scripts I use
pip install --user sh
# For lmwsaction
pip install --user SOAPpy
# So we can clone git repositories with mercurial
ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future" pip install --user hg-git

# Other useful bits I don't need installed right now
#pip install --user pip-tools
#pip install --user tox
#pip install --user stormssh
#pip install --user dash.py doc2dash
#pip install --user pep8 pyflakes pylint flake8 autopep8
