#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
PATH="$scriptdir/linux:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

cargo_check unar unar
cargo_check sd sd
cargo_check dua dua
cargo_check sapling sl
cargos_install
