#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
repodir=$(dirname "$scriptdir")
PATH="$scriptdir/linux:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

ret=0

# Dotfiles
"$repodir/script/setup" || ret=$?

# Install pipx, if needed
if ! command -v pipx &>/dev/null; then
    msg "Installing pipx"
    /usr/bin/python3 -m pip install --user --disable-pip-version-check pipx
    /usr/bin/python3 -m pipx ensurepath
fi || ret=$?

# Install PowerShell modules, if needed
if has pwsh; then
    msg "Installing PowerShell modules"
    # Ignore failure, as these are not critical to my workflow, and can fail due
    # to transient network issues.
    pwsh -NoProfile "$scriptdir/install-pwsh-modules.ps1" || :
fi || ret=$?

# Install dtrx, if unar is missing
if ! command -v unar &>/dev/null; then
    msg "Installing dtrx"
    pipx install dtrx
fi || ret=$?

if chezmoi dump-config 2>/dev/null | grep -q ephemeral.\*true; then
    exit $ret
fi

# User shell should be zsh
zsh_binary=$(command -v zsh 2>/dev/null) || :
if [ -n "$zsh_binary" ] && grep -qFx "$zsh_binary" /etc/shells; then
    if [ "$(getent passwd "$(id -un)" | awk -F : '{print $NF}')" != "$zsh_binary" ]; then
        msg "Changing user shell to zsh"
        # Failure is ignored here, as in some cases the user password might not be
        # known or set, as is the case with some container usage.
        chsh -s /bin/zsh || ret=$?
    fi
fi

exit $ret
