#!/bin/sh

set -e

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
repodir=$(dirname "$scriptdir")
PATH="$scriptdir/freebsd:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

uv_check() {
    pkg="$1"
    cmd="${2:-}"

    if [ -n "$cmd" ] && command -v "$cmd" >/dev/null 2>&1; then
        return 0
    fi
    uvs="$uvs $pkg"
}

cargo_check() {
    pkg="$1"
    cmd="${2:-}"

    if [ -n "$cmd" ] && command -v "$cmd" >/dev/null 2>&1; then
        return 0
    fi
    cargos="$cargos $pkg"
}

go_check() {
    pkg="$1"
    cmd="${2:-}"

    if [ -n "$cmd" ] && command -v "$cmd" >/dev/null 2>&1; then
        return 0
    fi
    gos="$gos $pkg"
}

uvs=
cargos=
gos=

uv_check git-revise git-revise
uv_check git-imerge git-imerge
cargo_check choose choose

{{ if .work -}}
# Bug tracking and workflow
go_check github.com/ankitpokhrel/jira-cli/...@latest jira
{{- end }}

# As we don't support nix, install asdf for local environments
if ! command -v asdf >/dev/null 2>&1; then
    install-asdf
fi

# Installation
if [ -n "$(echo "$uvs" | sed -e 's/^ *//; s/ *$//')" ]; then
    msg "Installing via uv: $uvs"
    echo "$uvs" | tr ' ' '\n' | sort -u | tr '\n' '\0' | xargs -0 --no-run-if-empty -o -n 1 uv tool install
fi

if [ -n "$(echo "$cargos" | sed -e 's/^ *//; s/ *$//')" ]; then
    msg "Installing via cargo: $cargos"
    echo "$cargos" | tr ' ' '\n' | sort -u | tr '\n' '\0' | xargs -0 --no-run-if-empty -o cargo install --locked
fi

if [ -n "$(echo "$gos" | sed -e 's/^ *//; s/ *$//')" ]; then
    msg "Installing via go: $gos"
    echo "$gos" | tr ' ' '\n' | sort -u | tr '\n' '\0' | xargs -0 --no-run-if-empty -o go install
fi

# Dotfiles
"$repodir/script/setup"

# User shell
if [ -e /usr/local/bin/zsh ]; then
    current_shell="$(getent passwd "$USER" | sed -e 's#.*:##')"
    if [ "$current_shell" != /usr/local/bin/zsh ]; then
        msg "Changing current user shell to zsh"
        chsh -s /usr/local/bin/zsh
    fi
fi
