#!/usr/bin/env bash

set -euo pipefail

scriptdir=$(cd "$(dirname "$0")" && pwd -P)
repodir=$(dirname "$scriptdir")
PATH="$scriptdir/macos:$scriptdir:$PATH"

# shellcheck source=./common.sh
. "$scriptdir/common.sh" || exit 1

# Dotfiles
if [ -z "${CHEZMOI:-}" ]; then
    "$repodir/script/setup"
fi

# shellcheck disable=SC2046
if [ -d ~/.ssh/keys ] && [ $(find ~/.ssh/keys -maxdepth 1 -type f -not -name '*.pub' | wc -l) -gt 0 ]; then
    msg "Adding SSH keys to keychain"
    find ~/.ssh/keys -maxdepth 1 \( -type f -not -name '*.pub' -not -name '*.ppk' -not -name .DS_Store \) |
        while read -r key; do
            if ! [ -e "$key.pub" ]; then
                run ssh-keygen -y -f "$key" >"$key.pub"
            fi
            if ! ssh-add -T "$key.pub"; then
                run ssh-add --apple-use-keychain "$key" || :
            fi
        done
fi

#msg "Configuring"
"$scriptdir/macos/configure.tmpl"
"$scriptdir/macos/setup-apps"

msg "Configuring complete"
