#!/bin/sh

investigate_threshold=1
destdir=.
incomplete_blacklist="Descent|Fantasy General|Stargunner Original Soundtrack"

if which gln >/dev/null 2>&1; then
    alias ln=gln
fi

if [ $# -eq 0 ]; then
    set -- .
fi

for source_dir; do
    if [ "$(cd "$source_dir" && pwd -P)" = "$(pwd -P)" ]; then
        # Don't recurse into ourselves
        continue
    fi
    for dir in "$source_dir"/*/*/; do
        if [ ! -e "$dir" ]; then
            continue
        fi
        dir="${dir%/}"
        count=$(find "$dir/" -not -name ._\* \( -type f -o -type l \) | wc -l)
        # count=$(find "$dir" -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg | wc -l)
        if [ $count -lt 1 ]; then
            continue
        fi
        first="$(find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \) | head -n 1)"
        total="$(exiftool -p '$Tracktotal' "$first" 2>/dev/null)"
        if [ -z "$total" ]; then
            track="$(exiftool -p '$Track' "$first" 2>/dev/null)"
            if [ -n "$track" ]; then
                case "$track" in
                    */*)
                        total="${track#*/}"
                        ;;
                esac
            else
                track="$(exiftool -p '$TrackNumber' "$first" 2>/dev/null)"
                case "$track" in
                    *\ of\ *)
                        total="${track##* }"
                        ;;
                esac
            fi
        fi
        if [ -z "$total" ]; then
            if [ $count -gt 1 ]; then
                d="./_Complete Albums"
            else
                d="./_Single-Track"
            fi
        elif [ $count -ge $total ]; then
            if [ $total -le 2 ]; then
                d="./_Complete Singles"
            else
                d="./_Complete Albums"
            fi
        elif [ $total -eq 1 ]; then
            d="./_Single-Track"
        else
            if [ $count -gt "$investigate_threshold" ]; then
                if basename "$dir" | grep -qEx "$incomplete_blacklist"; then
                    d="./_Complete Albums"
                else
                    # Possibly screwed up, or an incomplete album
                    d="./_Incomplete Albums"
                fi
            else
                d="./_Single-Track"
            fi
        fi
        if [ "$d" = "./_Single-Track" ]; then
            mkdir -p "$d"
            find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \) \
                | while read -r fn; do
                    ext="${fn##*.}"
                    ln -rsfv "$fn" "$d/$(exiftool -p '$Artist - $Title' "$fn").$ext"
                done
            continue
        fi

        rel="$(relpath "$dir" "$source_dir")"
        dest="$d/$rel"
        destdir="$(dirname "$dest")"

        echo "$rel: $count / $total"
        mkdir -p "$destdir"
        if [ -h "$dest" ]; then
            if [ -d "$dest" ]; then
                olddest="$(cd "$dest" && pwd -P)"
            else
                olddest="$(cd "$destdir" && abspath "$(readlink "$(basename "$rel")")")"
            fi
            absdir="$(cd "$dir" && pwd -P)"
            if [ "$olddest" != "$absdir" ]; then
                echo >&2 "Error: $dest exists but points to $olddest, not $absdir"
                continue
            fi
        fi
        rm -f "$dest"
        ln -rsfv "$dir" "$dest"
    done
done
