#!/bin/sh

investigate_threshold=1
destdir=.
albumsdir=./_Albums
extrasdir="./_Albums With Extra Tracks"
incompletedir="./_Incomplete Albums"
singlesdir=./_Singles
singletracksdir="./_Single Tracks"

# Games with data tracks and amazon albums whose videos and booklets are
# counted in the track total. This blacklist only allows one track to be
# missing at this time.
incomplete_blacklist="Descent|Shadow Warrior|Fantasy General|Stargunner Original Soundtrack|King's Quest VI Heir Today, Gone Tomorrow|Command & Conquer Red Alert Counterstrike|Command & Conquer Tiberian Dawn Covert Operations|Warcraft II Tides of Darkness|Total Annihilation|Moto Racer|Return to Zork|Quake|.*\\[\\+video\\]|.*\\[\\+Digital Booklet\\]"

if which gln >/dev/null 2>&1; then
    alias link='gln -rsfv'
else
    alias link='ln -rsfv'
fi

if [ $# -eq 0 ]; then
    set -- .
fi

get_metadata () {
    ffprobe -loglevel quiet -of compact=p=0 -show_entries format_tags "$1" \
        | tr '|' '\n' \
        | sed -e 's/tag://' \
        | grep -v '\\r' \
        | while IFS="=" read -r key value; do
            case "$key" in
                lyrics*)
                    continue
                    ;;
                *\ *)
                    key="$(echo "$key" | tr " " _)"
                    ;;
            esac
            key="$(printf '%s\n' "$key" | tr ".:/-#=\`" "_______" | tr "[:upper:]" "[:lower:]" | tr -d '\')"
            value="$(printf '%s\n' "$value" | sed -e 's/"/\\"/g; s/\\$//; s/`/\\`/g')"
            printf '%s="%s"\n' "$key" "$value"
        done
}

eval_metadata () {
    eval "$(get_metadata "$@")"
}

get_tracknumber () {
    case "$track" in
        */*)
            tracknumber="${track%/*}"
            tracktotal="${track##*/}"
            ;;
        '')
            ;;
        *)
            tracknumber="$track"
            ;;
    esac
    if [ -z "$tracknumber" ]; then
        return 1
    fi
    if [ -z "$tracktotal" ] && [ -n "$totaltracks" ]; then
        tracktotal="$totaltracks"
    fi
    printf "$tracknumber"
    if [ -n "$tracktotal" ]; then
        printf "/$tracktotal"
    fi
    printf '\n'
}

get_discnumber () {
    case "$disc" in
        */*)
            discnumber="${disc%/*}"
            disctotal="${disc##*/}"
            ;;
        '')
            ;;
        *)
            discnumber="$disc"
            ;;
    esac
    if [ -z "$discnumber" ]; then
        discnumber=1
    fi
    if [ -z "$disctotal" ] && [ -n "$totaldiscs" ]; then
        disctotal="$totaldiscs"
    fi
    printf "$discnumber"
    if [ -n "$disctotal" ]; then
        printf "/$disctotal"
    fi
    printf '\n'
}

# We need to get the total tracks for all discs to get a true total
get_album_track_total () {
    file_count=$(find "$1/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) | wc -l)
    find "$1/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) \
        | (
            total=0
            while read -r fn; do
                eval_metadata "$fn"

                track="$(get_tracknumber)"
                case "$track" in
                    */*)
                        tracknumber="${track%/*}"
                        tracktotal="${track##*/}"
                        ;;
                    *)
                        tracknumber="$track"
                        tracktotal=
                        ;;
                esac

                disc="$(get_discnumber)"
                case "$disc" in
                    */*)
                        discnumber="${disc%/*}"
                        disctotal="${disc##*/}"
                        ;;
                    *)
                        discnumber="$disc"
                        disctotal=
                        ;;
                esac

                existing_total="$(eval "printf '%s' \"\${total$discnumber}\"")"
                if [ -z "$existing_total" ]; then
                    if [ -n "$tracktotal" ]; then
                        eval "total$discnumber=$tracktotal"
                        total=$((total+tracktotal))
                    else
                        return 0
                    fi
                fi
                if [ $total -ge $file_count ]; then
                    break
                fi
            done
            if [ $total -gt 0 ]; then
                echo "$total"
            fi
        )
}

for source_dir; do
    if [ "$(cd "$source_dir" && pwd -P)" = "$(pwd -P)" ]; then
        # Don't recurse into ourselves
        continue
    fi
    for dir in "$source_dir"/*/*/; do
        if [ ! -e "$dir" ]; then
            continue
        fi
        dir="${dir%/}"
        count="$(find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) | wc -l)"
        if [ $count -lt 1 ]; then
            continue
        fi
        first="$(find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg -o -iname \*.dsf \) | head -n 1)"
        total="$(get_album_track_total "$dir/")"

        if [ -z "$total" ]; then
            if [ $count -gt 1 ]; then
                d="$albumsdir"
            else
                d="$singletracksdir"
            fi
        elif [ $count -eq $total ]; then
            if [ $total -eq 1 ] || basename "$dir" | grep -q Single; then
                d="$singlesdir"
            else
                d="$albumsdir"
            fi
        elif [ $count -gt $total ]; then
            # The most common case is multiple discs
            # find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \)
            d="$extrasdir"
        elif [ $total -eq 1 ]; then
            d="$singletracksdir"
        else
            if [ $count -gt "$investigate_threshold" ]; then
                if [ $count -eq $((total - 1)) ] && basename "$dir" | grep -qEx "$incomplete_blacklist"; then
                    d="$albumsdir"
                else
                    # Possibly screwed up, or an incomplete album
                    d="$incompletedir"
                fi
            else
                d="$singletracksdir"
            fi
        fi
        if [ "$d" = "$singletracksdir" ]; then
            mkdir -p "$d"
            find "$dir/" -not -name ._\* \( -iname \*.flac -o -iname \*mp3 -o -iname \*.m4a -o -iname \*.ogg \) \
                | while read -r fn; do
                    ext="${fn##*.}"
                    link "$fn" "$d/$(exiftool -qm -Artist -Title -p '$Artist - $Title' "$fn" 2>/dev/null).$ext"
                done
        else
            rel="$(relpath "$dir" "$source_dir")"
            dest="$d/$rel"
            destdir="$(dirname "$dest")"

            echo "$rel: $count / $total"
            mkdir -p "$destdir"
            if [ -h "$dest" ]; then
                if [ -d "$dest" ]; then
                    olddest="$(cd "$dest" && pwd -P)"
                else
                    olddest="$(cd "$destdir" && abspath "$(readlink "$(basename "$rel")")")"
                fi
                absdir="$(cd "$dir" && pwd -P)"
                if [ "$olddest" != "$absdir" ]; then
                    echo >&2 "Error: $dest exists but points to $olddest, not $absdir"
                    continue
                fi
            fi
            rm -f "$dest"
            link "$dir" "$dest"
        fi
    done
done
