#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] PREFIX_STRING"

Filter lines/fields that start with PREFIX_STRING.

This avoids issues that regex-based tools run into in the case where the
specified path prefix contains regex special characters.

Examples:

    $ find fzf | startswith fzf/vim/bundle/fzf/plugin/
    fzf/vim/bundle/fzf/plugin/fzf.vim

    $ find fzf | startswith -F/ -n2 zsh
    fzf/zsh-functions
    fzf/zsh-functions/cdp
    fzf/zsh-functions/fo

Options:
  -F FIELD     Field separator
  -n FIELD_NUM Field number. 0 for full line.
  -h   Show usage
END
    exit 2
}

separator=
field_number=0
while getopts F:n:h opt; do
    case "$opt" in
        F)
            separator="$OPTARG"
            ;;
        n)
            field_number="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

awk ${separator:+"-F$separator"} -v "field=$field_number" -v "prefix=$*" '{ if (index($field, prefix) == 1) { printf("%s\n", $0) } }'
