#!/bin/sh
destdir=$1
url=$2

if [ ! -e $destdir ]; then
    svnadmin create $destdir
    if [ -x /bin/true ]; then
        ln -s /bin/true $destdir/hooks/pre-revprop-change
    else
        echo '#!/bin/sh' >$destdir/hooks/pre-revprop-change
        chmod +x $destdir/hooks/pre-revprop-change
    fi
    uuid="$(svn info $url|sed -n -e's/^Repository UUID: \(.*\)$/\1/p')"
    svnadmin setuuid $destdir $uuid

    svnrdump dump "$url" | svnadmin load --bypass-prop-validation $destdir
    svnsync init --allow-non-empty "file://$destdir" "$url"
fi
svnsync sync "file://$destdir"
