#!/bin/sh

usage () {
    echo >&2 "${0##*/} [-0] TAG [TAG..]"
    exit 2
}

query_string () {
    for tag; do
        case "$tag" in
            -*)
                printf " && kMDItemUserTags != '${tag#-}'"
                ;;
            *)
                printf " && kMDItemUserTags == '$tag'"
                ;;
        esac
    done | sed 's,^ && ,,'
}

quote(){
    sed -e "s,','\\\\'',g; 1s,^,',; \$s,\$,',;" << EOF
$1
EOF
}

save () {
    case "$1" in
    # when a string contains a "'" we have to escape it
    *\'*)
        saved="$saved $(quote "$1")"
        ;;
    # otherwise just quote the variable
    *)
        saved="$saved '$1'"
        ;;
    esac
}


if [ $# -eq 0 ]; then
    usage
fi

user_query=
while getopts 0q:h opt; do
    case "$opt" in
        0)
            save "-$opt"
            ;;
        q)
            user_query="$OPTARG && "
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $(($OPTIND - 1))

query="$user_query$(query_string "$@")"
eval set -- "$saved"
mdfind "$@" "$query"
