#!/bin/sh

usage () {
    echo >&2 "${0##*/} [-0] TAG [TAG..]"
    exit 2
}

query_string () {
    for tag; do
        case "$tag" in
            -*)
                printf " && kMDItemUserTags != '${tag#-}'"
                ;;
            *)
                printf " && kMDItemUserTags == '$tag'"
                ;;
        esac
    done | sed 's,^ && ,,'
}


if [ $# -eq 0 ]; then
    usage
fi

user_query=
mdfind_args=
while getopts 0q:h opt; do
    case "$opt" in
        0)
            mdfind_args="-0"
            ;;
        q)
            user_query="$OPTARG && "
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $(($OPTIND - 1))

mdfind $mdfind_args "$user_query$(query_string "$@")"
