#!/bin/sh

usage () {
    echo >&2 "${0##*/} [-0] TAG [TAG..]"
    exit 2
}

query_string () {
    for tag; do
        case "$tag" in
            -*)
                printf " && kMDItemUserTags != '${tag#-}'"
                ;;
            *)
                printf " && kMDItemUserTags == '$tag'"
                ;;
        esac
    done | sed 's,^ && ,,'
}


user_query=
mdfind_args=
show_untagged=0
show_all_tagged=0
while getopts q:0uah opt; do
    case "$opt" in
        q)
            user_query="$OPTARG && "
            ;;
        0)
            mdfind_args="-0"
            ;;
        u)
            show_untagged=1
            ;;
        a)
            show_all_tagged=1
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $(($OPTIND - 1))


if [ $show_untagged -eq 1 ]; then
    if [ $# -ne 0 ] || [ $show_all_tagged -eq 1 ]; then
        echo >&2 "Error: -a, -u, and tag list are mutually exclusive"
        exit 3
    fi
    mdfind $mdfind_args tag:
elif [ $show_all_tagged -eq 1 ]; then
    if [ $# -ne 0 ]; then
        echo >&2 "Error: -a, -u, and tag list are mutually exclusive"
        exit 3
    fi
    mdfind $mdfind_args 'tag:""'
elif [ $# -eq 0 ]; then
    usage
else
    mdfind $mdfind_args "$user_query$(query_string "$@")"
fi
