#!/bin/sh
# Courtesy http://waxandwane.org/dvtm.html

LOGNAME="${LOGNAME:-$(logname)}"
DVTM_TMPDIR="${TMPDIR:-/tmp}/dvtm-$LOGNAME"

if [ $# -ne 1 ] || [ -z $1 ]; then
    SCRIPT=${0##*/}
    BASIC="  $SCRIPT  \n"
    SESSIONS="$(ls -1 $DVTM_TMPDIR/*-session $DVTM_TMPDIR/*/*-session 2>/dev/null)"

    if [ -z "$SESSIONS" ]; then
        printf "Usage:$BASIC" 1>&2
        exit 1
    fi

    printf "Usage:\n    reconnect to a running session:\n" 1>&2
    for s in $SESSIONS; do
        s=${s#$DVTM_TMPDIR/}
        echo "        $SCRIPT  ${s%-session}" 1>&2
    done
    printf "\n    or begin a new session:\n      $BASIC" 1>&2
    exit 1
fi

if [ -n "$DVTM_ID" ]; then
    echo >&2 "Already in a dvtm session, exiting"
    exit 3
fi

DVTM_ID="$(printf "%s\n" "$1" | tr [A-Z] [a-z])"
if [ ! -e "$DVTM_TMPDIR" ]; then
    mkdir -p $DVTM_TMPDIR
    chmod 0700 $DVTM_TMPDIR
fi
mkdir -p "$DVTM_TMPDIR/${DVTM_ID%/*}"
SOCKET="$DVTM_TMPDIR/$DVTM_ID-session"

dtach -A $SOCKET -r winch -z dvtm-status "$@"

exit 0
