#!/bin/sh

tmux showenv "$@" | while IFS== read var value; do
    case "$var" in
        -*)
            printf 'unset %s;\n' ${var#-}
            ;;
        *)
            printf 'export %s="%s";\n' "$var" "$value"
            ;;
    esac
done
