#!/usr/bin/env python

import itertools
import sys
import toml


def lookup(obj, key):
    return reduce(lambda x, y: x[y], key, obj)


def pairs(iterable):
    a, b = itertools.tee(iterable)
    a = itertools.islice(a, 0, None, 2)
    b = itertools.islice(b, 1, None, 2)
    return itertools.izip(a, b)


if not sys.stdin.isatty():
    o = toml.load(sys.stdin)
else:
    o = {}

try:
    for key in sys.argv[1:]:
        key = key.split(".")
        prefix, final_key = key[:-1], key[len(key)-1]
        del lookup(o, prefix)[final_key]
finally:
    toml.dump(o, sys.stdout)
