#!/usr/bin/env python

import argparse
import itertools
import sys
import toml


def lookup(obj, key):
    return reduce(lambda x, y: x[y], key, obj)


def pairs(iterable):
    a, b = itertools.tee(iterable)
    a = itertools.islice(a, 0, None, 2)
    b = itertools.islice(b, 1, None, 2)
    return itertools.izip(a, b)

parser = argparse.ArgumentParser()
parser.add_argument('-f', '--file', help='Input path rather than stdin')
parser.add_argument('-o', '--output', help='Output path. If --file is specified, defaults to that, otherwise stdout')
parser.add_argument('-n', '--new', help='Create a new file from the arguments, do not read input', action='store_true')
parser.add_argument('values', metavar='VALUE', nargs='+')

args = parser.parse_args()

if len(args.values) % 2 != 0:
    sys.exit("Error: odd number of arguments. Arguments must be in key/value pairs")

if args.new:
    o = {}
else:
    infile = args.file or sys.stdin
    o = toml.load(infile)

try:
    for key, value in pairs(args.values):
        key = key.split(".")
        prefix, final_key = key[:-1], key[len(key)-1]
        lookup(o, prefix)[final_key] = toml._load_value(value)[0]
finally:
    if not args.file or args.file == '-':
        f = sys.stdout
    else:
        f = open(args.file, 'w')

    try:
        toml.dump(o, f)
    finally:
        if f is not sys.stdout:
            f.close()
