#!/usr/bin/env python

import sys
import toml


def lookup(obj, key):
    return reduce(lambda x, y: x[y], key, obj)

o = toml.load(sys.stdin)
try:
    k = sys.argv[1].split(".")
    i, v = k[:-1], k[len(k)-1]
    lookup(o, i)[v] = toml.load_value(sys.argv[2])[0]
finally:
    toml.dump(o, sys.stdout)
