#!/usr/bin/env python3

import argparse
import itertools
import subprocess
import sys
import toml


def pairs(iterable):
    a, b = itertools.tee(iterable)
    a = itertools.islice(a, 0, None, 2)
    b = itertools.islice(b, 1, None, 2)
    return zip(a, b)


parser = argparse.ArgumentParser()
parser.add_argument('-f', '--file', help='Input path rather than stdin')
parser.add_argument('-o', '--output', help='Output path. If --file is specified, defaults to that, otherwise stdout')
parser.add_argument('-n', '--new', help='Create a new file from the arguments, do not read input', action='store_true')
parser.add_argument('key')
parser.add_argument('elements', metavar='ELEMENT', nargs='+')

args = parser.parse_args()

cmd = ["toml-set"]
if args.new:
    cmd.append('-n')

if args.file:
    cmd.append('-f')
    cmd.append(args.file)

if args.output:
    cmd.append('-o')
    cmd.append(args.output)

cmd.append(args.key)

d = {}
elements = [toml._load_value(v, d)[0] for v in args.elements]
cmd.append(toml._dump_value(elements))

try:
    subprocess.check_call(cmd)
except subprocess.CalledProcessError:
    sys.exit(1)
