#!/bin/sh

tmpfile="$(mktemp -t ${0##*/}.XXXXXX)"
trap "rm -f \"$tmpfile\"" EXIT INT TERM

PATH="$(dirname "$0"):$PATH" find-all-games-identified >>"$tmpfile" || exit 1

curl -s https://gist.githubusercontent.com/kergoth/f553f205704adfb6f98f/raw/games-on-mac.txt | diff -urNd - "$tmpfile"
if [ $? -ne 0 ] && [ "$1" != "-n" ]; then
    gist -s -f games-on-mac.txt -u f553f205704adfb6f98f "$tmpfile"
fi
