#!/bin/bash
# Read stdin as vim errors/grep lines into the quickfix window and edit the
# first result.

set -euo pipefail

tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM
cat >>"$tmpfile"
vim </dev/tty -c "cf $tmpfile" "$@"
