#!/usr/bin/env bash
# Read stdin as vim errors/grep lines into the quickfix window and edit the
# first result.
#
# Examples:
#
#   $ rg --vimgrep "$@" | vimerrors
#   $ rg --vimgrep --color always "$@" | eval fzf --ansi $FZF_RG_OPTS | vimerrors

set -euo pipefail

tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM
cat >>"$tmpfile"
if [ -s "$tmpfile" ]; then
    vim </dev/tty -c "cf $tmpfile" "$@"
fi
