#!/bin/sh

walk_up () {
    local walk_path="$(abspath "${1:-$PWD}")"
    while [ -n "$walk_path" ]; do
        echo "$walk_path"
        walk_path="${walk_path%/*}"
    done
}

find_up () {
    walk_up "${2:-$PWD}" | while read p; do
        if [ -e "$p/$1" ]; then
            echo "$p"
            return 0
        fi
    done
    return 1
}

cmd="vim"
if [ "$VISUAL" = nvim ] || [ "$EDITOR" = nvim ]; then
    cmd=nvim
fi

session_dir="$(find_up Session.vim)"
if [ -n "$session_dir" ]; then
    exec "$cmd" -S "$session_dir/Session.vim" "$@"
else
    touch Session.vim
    "$cmd" -c silent\ Obsession "$@"
    if ! [ -s Session.vim ]; then
        rm -f Session.vim
    fi
fi
