#!/bin/sh

export TERMINAL=st
export DISPLAY="${DISPLAY:-:0.0}"
PATH="$(dirname "$0"):$HOME/.local/bin:$PATH"
xrdb -merge ${XDG_CONFIG_HOME:-~/.config}/X11/Xresources
pkill -f i3-urgent-notify-wsl
(
    # Python script, ensure we can use pyenv python
    export PYENV_ROOT="${PYENV_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/pyenv}"
    PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    i3-urgent-notify-wsl >/dev/null 2>&1 <&1 &
)
exec ssh-agent i3
