#!/bin/sh

cred="$(PATH="/mnt/c/Program\ Files/Git/mingw64/libexec/git-core:$USERPROFILE/scoop/apps/git/current/mingw64/libexec/git-core" command -v git-credential-manager-core.exe)"
if [ -z "$cred" ]; then
    echo >&2 "Error locating git-credential-manager.exe"
    exit 1
fi
exec "$cred" "$@"
