#!/bin/sh

if command -v pwsh.exe >/dev/null 2>&1; then
    cmd=pwsh.exe
else
    cmd=powershell.exe
fi

script="Import-Module Recycle; Remove-ItemSafely "
for arg; do
    script="$script '$(wslpath -wa "$arg")'"
done
exec "$cmd" -c "$script"
