#!/bin/sh

set -e

USERPROFILE="$(wslpath "$(cmd.exe /D /C 'SET /P <NUL=%USERPROFILE%' 2>/dev/null)")"
TMPDIR="$USERPROFILE/AppData/Local/Temp"
tempdir="$(mktemp -d "$TMPDIR/${0##*/}.XXXXXX")"
trap 'rm -rf "$tempdir"' EXIT INT TERM

if [ -z "$(docker images -q local/nativefier)" ]; then
    git clone https://github.com/jiahaog/Nativefier "$tempdir/Nativefier"
    docker build -t local/nativefier "$tempdir/Nativefier"
fi

docker run -v "$(wslpath -am "$PWD"):$PWD" -v "$(wslpath -am "$tempdir")":/target local/nativefier -p windows "$@" /target/
mv -v "$tempdir/"* .
