#!/bin/sh

# These always seem to think they're outdated
excluded_casks="whatsyoursign|oversight"

# I prefer to install this via brew, but using rustup rather than brew's rust
excluded_casks="$excluded_casks|geckodriver"

ignored_depends="geckodriver"
excluded_ignored="$(echo "$ignored_depends" | tr " " "|")"
excluded="$excluded_ignored"

set -eu
trap 'brew clean; brew clean-cask-pkgs' EXIT INT TERM

unset HOMEBREW_AUTO_UPDATE

# We clear out any old packages/apps here, since we only want to run installers
# that we just installed, not old ones. If the installer reboots the system
# before it exits, the clean up won't happen after it installs, so we need it
# to run up front for that as well.
brew clean || :

brew update || :

brew outdated --fetch-HEAD |
	if [ -n "$excluded" ]; then grep -Ev "$excluded"; else cat; fi |
	xargs brew upgrade --fetch-HEAD
if [ -n "$ignored_depends" ]; then
	brew outdated --fetch-HEAD | grep -E "$excluded_ignored" |
		xargs brew install --ignore-dependencies --force-bottle -v --env=std
fi

brew clean-cask-pkgs || :
brew cask outdated |
	if [ -n "$excluded_casks" ]; then grep -Ev "$excluded_casks"; else cat; fi |
	xargs brew cask upgrade
brew cask cleanup
find "$(brew --prefix)/Caskroom" -iname \*.pkg -o -iname \*.app -prune | grep -iv uninstall | nlxargs -t -n 1 open -W
