#!/usr/bin/zsh
#
# have COMMAND
# Return 0 if COMMAND exists in the path, otherwise 1

setopt localoptions
setopt no_nomatch

typeset _filepath==$1
if [[ -n $_filepath ]]; then
    return 0
else
    return 1
fi
