#!/usr/bin/zsh
typeset -a pids sids
pids=($(/usr/bin/pgrep -f "$@"))

if [[ $#pids -eq 0 ]]; then
    return 0
fi

typeset procpid ppid pgid sess name state
for pid in $pids; do
    read procpid name state ppid pgid sess rest < /proc/$pid/stat
    sids+=$sess
done

typeset pidstr=${(j:,:)pids}
ps --pid $pidstr --ppid $pidstr --sid ${(j:,:)sids}
