export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}

if [[ -h $ZDOTDIR/.zshrc ]]; then
    DOTFILESDIR=$(dirname $(readlink $ZDOTDIR/.zshrc))/..
    if [[ ${DOTFILESDIR#/} = $DOTFILESDIR ]]; then
        DOTFILESDIR=$ZDOTDIR/$DOTFILESDIR
    fi
else
    DOTFILESDIR=$ZDOTDIR/..
fi

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export PAGER='less'
if [[ -n $commands[vim] ]]; then
    export EDITOR=vim
else
    export EDITOR=vi
fi
export VISUAL=$EDITOR
export VIMINIT='let $MYVIMRC = "$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
# Reduce the ncurses escape wait time (ms)
export ESCDELAY=25
export NCURSES_NO_UTF8_ACS=1

export CVS_RSH=ssh
export CVSREAD=yes

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

export INPUTRC=$XDG_CONFIG_HOME/readline/inputrc
export TERMINFO=$XDG_CONFIG_HOME/ncurses/terminfo
export CURL_HOME=$XDG_CONFIG_HOME/curl
export _FASD_VIMINFO=$XDG_DATA_HOME/vim/viminfo
export LESSHISTFILE=$XDG_DATA_HOME/less/lesshist
export _FASD_DATA=$XDG_DATA_HOME/fasd/data
export WORKON_HOME=$XDG_DATA_HOME/virtualenvs
export ACKRC=.ackrc

export EMAIL='kergoth@gmail.com'
export FULLNAME='Christopher Larson'
export DEBEMAIL=$EMAIL
export DEBFULLNAME=$FULLNAME

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

if [[ -e $DOTFILESDIR/zsh/zshenv.local ]]; then
    . "$DOTFILESDIR/zsh/zshenv.local"
fi
