export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
if [[ "$OSTYPE" == darwin* ]]; then
    export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/Library/Caches}
else
    export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
fi

if [[ "${PROFILE_STARTUP_LINES:-false}" == true ]]; then
    # http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
    PS4='+$EPOCHREALTIME %N:%i> '
    mkdir -p $XDG_DATA_HOME/zsh
    exec 3>&2 2>$XDG_DATA_HOME/zsh/start-$$.log
    setopt xtrace prompt_subst
elif [[ "${PROFILE_STARTUP:-false}" == true ]]; then
    zmodload zsh/zprof
fi

DOTFILESDIR="${0:A:h:h}"
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Reduce the ncurses escape wait time (ms)
export ESCDELAY=25
export NCURSES_NO_UTF8_ACS=1

if [[ -z "$LANG" ]] || [[ -z "$LC_ALL" ]]; then
  export LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  if [[ -n $commands[locale] ]]; then
    eval "$(locale)"
  fi
fi

export ACKRC=.ackrc
export GREP_COLORS='ms=30;43:mc=30;43:sl=:cx=:fn=1;34:ln=1;33:bn=32:se=36'

export EMAIL='kergoth@gmail.com'
export FULLNAME='Christopher Larson'
export DEBEMAIL=$EMAIL
export DEBFULLNAME=$FULLNAME

if [[ -e $DOTFILESDIR/zsh/zshenv.local ]]; then
    . "$DOTFILESDIR/zsh/zshenv.local"
fi

export PERU_CACHE_DIR=$XDG_CACHE_HOME/peru
export HTTPIE_CONFIG_DIR=$XDG_CONFIG_HOME/httpie
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass
export RLWRAP_HOME=$XDG_DATA_HOME/rlwrap
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine
export RANDFILE=$XDG_DATA_HOME/rng
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export CFLAGS=-O2
export XZ_DEFAULTS=--threads=0
export PAGER=more
export YSU_IGNORED_ALIASES=("vi")
export SHELLCHECK_OPTS="-e SC2002 -e SC2039 -e SC2209"

for env in $DOTFILESDIR/*/env.zsh(N); do
    . "$env"
done

for dir in $HOME/.terminfo $XDG_CONFIG_HOME/ncurses/terminfo $HOMEBREW_PREFIX/share/terminfo /Users/Shared/homebrew/share/terminfo /opt/homebrew/share/terminfo /usr/local/share/terminfo /usr/share/terminfo; do
    if [[ -d $dir ]]; then
        TERMINFO_DIRS="$TERMINFO_DIRS:$dir"
    fi
done
if [[ -n "$TERMINFO_DIRS" ]]; then
    TERMINFO_DIRS="${TERMINFO_DIRS#:}"
fi
export TERMINFO_DIRS

