export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
if [[ "$OSTYPE" == darwin* ]]; then
    export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/Library/Caches}
else
    export XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
fi

if [[ "${PROFILE_STARTUP:-false}" == true ]]; then
    # http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
    PS4=$'%D{%M%S%.} %N:%i> '
    mkdir -p $XDG_DATA_HOME/zsh
    exec 3>&2 2>$XDG_DATA_HOME/zsh/start-$$.log
    setopt xtrace prompt_subst
fi

if [[ -h $ZDOTDIR/.zshrc ]]; then
    DOTFILESDIR=$(dirname $(readlink $ZDOTDIR/.zshrc))/..
    if [[ ${DOTFILESDIR#/} = $DOTFILESDIR ]]; then
        DOTFILESDIR=$ZDOTDIR/$DOTFILESDIR
    fi
else
    DOTFILESDIR=$ZDOTDIR/..
fi
DOTFILESDIR=${DOTFILESDIR:A}

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

export PAGER='less'
if [[ -n $commands[vim] ]]; then
    export EDITOR=vim
else
    export EDITOR=vi
fi
export VISUAL=$EDITOR
export VIMINIT='let $MYVIMRC = "$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
# Reduce the ncurses escape wait time (ms)
export ESCDELAY=25
export NCURSES_NO_UTF8_ACS=1

export CVS_RSH=ssh
export CVSREAD=yes

if [[ -z "$LANG" ]]; then
  if [[ -n $commands[locale] ]]; then
    eval "$(locale)"
  else
    export LANG=en_US.UTF-8
  fi
fi

export ACKRC=.ackrc

export EMAIL='kergoth@gmail.com'
export FULLNAME='Christopher Larson'
export DEBEMAIL=$EMAIL
export DEBFULLNAME=$FULLNAME

if [[ -e $DOTFILESDIR/zsh/zshenv.local ]]; then
    . "$DOTFILESDIR/zsh/zshenv.local"
fi

for dir in $HOME/.terminfo $XDG_CONFIG_HOME/ncurses/terminfo /Users/Shared/homebrew/share/terminfo /usr/local/share/terminfo /usr/share/terminfo; do
    if [[ -d $dir ]]; then
        TERMINFO_DIRS="$TERMINFO_DIRS:$dir"
    fi
done
if [[ -n "$TERMINFO_DIRS" ]]; then
    TERMINFO_DIRS="${TERMINFO_DIRS#:}"
fi
export TERMINFO_DIRS

export INPUTRC=$XDG_CONFIG_HOME/readline/inputrc
export CURL_HOME=$XDG_CONFIG_HOME/curl
export _FASD_VIMINFO=$XDG_DATA_HOME/vim/viminfo
export LESSHISTFILE=$XDG_DATA_HOME/less/lesshist
export _FASD_DATA=$XDG_DATA_HOME/fasd/data
export WORKON_HOME=$XDG_DATA_HOME/virtualenvs
export PERU_CACHE_DIR=$XDG_CACHE_HOME/peru
export HTTPIE_CONFIG_DIR=$XDG_CONFIG_HOME/httpie
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/pass
export RLWRAP_HOME=$XDG_DATA_HOME/rlwrap
export TMUX_TMPDIR=$XDG_RUNTIME_DIR
export XAUTHORITY=$XDG_RUNTIME_DIR/Xauthority
export RANDFILE=$XDG_DATA_HOME/rng

for env in $DOTFILESDIR/*/env.zsh(N); do
    . "$env"
done
