ZSH=$DOTFILESDIR/zsh

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# all of our zsh files
typeset -U config_files
config_files=($DOTFILESDIR/*/*.zsh)

# load the path files
for file in ${(M)config_files:#*/path.zsh}
do
  source $file
done

# load "plugins"
for file in $ZSH/plugins/*/*.plugin.zsh $ZSH/plugins/*/activate.sh; do
  source $file
done

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
do
  source $file
done

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
if [[ $PSEUDO_DISABLED = 0 ]]; then
    # When running under pseudo, we're actually still ourselves, so silently
    # ignore the compaudit.
    compinit -u -d $XDG_CACHE_HOME/zsh/zcompdump
else
    compinit -d $XDG_CACHE_HOME/zsh/zcompdump
fi

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}
do
  source $file
done

unset config_files
