pref("extensions.infolister.XML.extensionbool", true);
pref("extensions.infolister.XML.themebool", true);
pref("extensions.infolister.XML.lastupdbool", true);
pref("extensions.infolister.XML.uabool", true);
pref("extensions.infolister.XML.pluginbool", true);
pref("extensions.infolister.XSLT.mode", 0);
pref("extensions.infolister.XSLT.file", "");//XXX
pref("extensions.infolister.ftp.host", "");
pref("extensions.infolister.ftp.username", "");
pref("extensions.infolister.ftp.path", "");
pref("extensions.infolister.ftp.protocol", "ftp");
pref("extensions.infolister.ftp.autoupload", false);
pref("extensions.infolister.charset", "chrome://infolister/locale/infolister.properties");
pref("extensions.infolister.sort", true);
pref("extensions.infolister.template.uri", "chrome://infolister/locale/templates/html.template");
pref("extensions.infolister.template.custom", "");//XXX
pref("extensions.infolister.hide_menu_item", false);
pref("extensions.infolister.autosave", false);
