#!/bin/sh
# Ensure that our user exists and can use sudo

set -eu

is_container() {
    [ -f /.dockerenv ] ||
    [ -f /run/.containerenv ] ||
    [ -n "${container:-}" ] ||
    grep -qE 'docker|lxc|containerd' /proc/1/cgroup 2>/dev/null
}

# shellcheck disable=SC2032
pacman() {
    command pacman --noconfirm --needed "$@"
}

pacman_install() {
    # shellcheck disable=SC2086,SC2033
    for arg; do
        if ! pacman -Q "$arg" >/dev/null 2>&1; then
            echo "$arg"
        fi
    done | xargs pacman --noconfirm --needed -S
}

user=$1

if ! getent passwd "$user" >/dev/null 2>&1; then
    echo >&2 "Adding user '$user'"
    useradd -m -g users -G wheel,uucp,storage "$user"
    if [ -e /bin/zsh ]; then
        chsh -s /bin/zsh "$user"
    fi

    if [ -n "${USER_PASSWORD:-}" ]; then
        echo "$user:$USER_PASSWORD" | chpasswd
    elif [ -t 0 ]; then
        echo >&2 "Input password for $user"
        passwd "$user"
    fi
else
    echo >&2 "Adding user '$user' to the wheel group"
    usermod -a -G wheel "$user"
fi

# Required for fresh ArchWSL where keyring isn't initialized
if [ ! -d /etc/pacman.d/gnupg ] || [ -z "$(ls -A /etc/pacman.d/gnupg 2>/dev/null)" ]; then
    echo >&2 "Initializing pacman keyring..."
    pacman-key --init
    pacman-key --populate
fi

pacman -Syu --noconfirm
pacman_install sudo

# Enable sudo for the wheel group
if is_container; then
    echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >/etc/sudoers.d/wheel
    chmod 0440 /etc/sudoers.d/wheel
else
    sed -i -e '/# %wheel.*) ALL$/s/^# *//' /etc/sudoers
fi
