#!/bin/sh

set -e

get_cd_device() {
    diskutil list | sed -n '/^\/dev\/disk/s/ .*, physical)://p' \
        | grep -v '/dev/disk0$' | while read -r disk; do
            if diskutil info "$disk" | grep -Eq ' *Optical Media Type: *CD-ROM$'; then
                echo "$disk"
                return 0
            fi
        done
    return 1
}

tocfile="$(mktemp -t "$(basename "$0").XXXXXX")"
trap 'rm -f "$tocfile"' EXIT

rm -f "$tocfile"
device="$(get_cd_device)" || :
if [ -n "$device" ]; then
    diskutil unmountDisk "$device"
    if [ $# -eq 0 ]; then
        name="$(diskutil info "${device}s0" | sed -n 's# *Volume Name: *##p')" || :
        if [ -n "$name" ]; then
            echo >&2 "No title specified: using volume name '$name'"
            title="$name"
        fi
    fi
fi

usage() {
    echo >&2 "${0##*/} [-s STARTING_SESSION] [TITLE]"
    exit 2
}

starting_session=1
while getopts s:h opt; do
    case "$opt" in
        s)
            starting_session="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ge 1 ]; then
    title="$1"
    shift
elif [ -z "$title" ]; then
    usage
fi
title="$(echo "$title" | tr ':/' '∶／' | sed -e 's/^\.//')"

sessions="$(cdrdao disk-info --driver generic-mmc:0x20000 | sed -n -e 's/^Sessions.*: //p')"
if [ -z "$sessions" ]; then
    sessions="$starting_session"
fi
for session in $(seq "$starting_session" "$sessions"); do
    name="$title"
    if [ "$session" != 1 ]; then
        name="${name} Session $session"
    fi
    cdrdao read-cd --session "$session" --driver generic-mmc:0x20000 --read-raw "$@" --datafile "$name.bin" "$name.toc"
    toc2cue "$name.toc" "$name".cue
    rm -f "$name.toc"
done
