#!/bin/sh

filename="$1"
shift
dirname="$(dirname "$filename")"

# isoinfo lists directories, not just files, even when passing -find -type d
if [ -f "$dirname" ] && ! [ -s "$dirname" ]; then
    rm -f "$dirname"
elif [ -d "$filename" ]; then
    exit 0
fi
mkdir -p "$dirname"

isoinfo "$@" -x "$filename" > "filename"
