#!/bin/sh

usage () {
    echo >&2 "${0##*/} [OPTIONS] [-a|-u|TAG [TAG..]]"
    echo >&2
    echo >&2 "Use spotlight to find files with (optionally specifed) tags."
    echo >&2 "Uses mavericks tags, not OpenMeta tags, at this time."
    echo >&2
    echo >&2 "If a specified tag starts with -, it searches for files without"
    echo >&2 "that tag. For example, -Game shows files without the Game tag."
    echo >&2
    echo >&2 "When multiple tags are specified, files are shown which have"
    echo >&2 "all the specified tags."
    echo >&2
    echo >&2 "Options:"
    echo >&2 "  -q USER_QUERY   Append a query directly to the mdfind cmd"
    echo >&2 "  -p PATH         Only search under the specified PATH"
    echo >&2 "  -0      Use NULL string as a separator, not a newline"
    echo >&2 "  -u      Show untagged files, incompatible with -a and tags"
    echo >&2 "  -a      Show all tagged files, incompatible with -u and tags"
    echo >&2 "  -l      List all currently used tags (runs mdls on -a output)"
    exit 2
}

mdfind () {
    command mdfind 2>/dev/null "$@"
}

query_string () {
    for tag; do
        case "$tag" in
            -*)
                printf " && kMDItemUserTags != '%s'" "${tag#-}"
                ;;
            *)
                printf " && kMDItemUserTags == '%s'" "$tag"
                ;;
        esac
    done | sed 's,^ && ,,'
}


user_query=
mdfind_args=
show_untagged=0
show_all_tagged=0
list_all_tags=0
while getopts q:p:0ualh opt; do
    case "$opt" in
        q)
            user_query="$OPTARG && "
            ;;
        p)
            mdfind_args="-onlyin \"$OPTARG\""
            ;;
        0)
            mdfind_args="-0"
            ;;
        u)
            show_untagged=1
            ;;
        a)
            show_all_tagged=1
            ;;
        l)
            list_all_tags=1
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

tag_opt_total="$((show_untagged + show_all_tagged + list_all_tags))"
if [ $tag_opt_total -gt 0 ]; then
    if [ $tag_opt_total -gt 1 ] || [ $# -gt 0 ]; then
        echo >&2 "Error: -a, -u, -l, and tag list are mutually exclusive"
        exit 3
    fi
fi

if [ $show_untagged -eq 1 ]; then
    eval mdfind "$mdfind_args" "kMDItemUserTags != \*"
elif [ $show_all_tagged -eq 1 ]; then
    eval mdfind "$mdfind_args" "kMDItemUserTags == \*"
elif [ $list_all_tags -eq 1 ]; then
    sedscript="$(mktemp tag-find.XXXX)"
    trap 'rm -f "$sedscript"' EXIT INT TERM
    cat >"$sedscript" <<END
/^kMDItemUserTags /{
:start
n
s/^[	 ]*//
s/,$//
s/^"//
s/"$//
/^)/b out
p
b start
}
:out
END
    eval mdfind -0 "$mdfind_args" "'tag:\"\"'" | xargs -0 mdls | \
        sed -n -f "$sedscript" | sort -u
elif [ $# -eq 0 ]; then
    usage
else
    eval "mdfind $mdfind_args \"\$user_query\$(query_string \"\$@\")\""
fi
