#!/bin/sh

set -eu

cd "$(git-get https://github.com/sherlock-project/sherlock 2>/dev/null)"
if ! [ -e venv ]; then
    python3 -m venv venv
fi
. ./venv/bin/activate
python3 -m pip install -r requirements.txt
python3 sherlock "$@"
