#!/bin/sh

case "$1" in
    --about)
        echo "Remove .pyc and .pyo files"
        ;;
    *)
        if [ "$3" -eq 1 -a "$1" != "$2" ]; then
            find . \( -name '*.pyc' -o -name '*.pyo' \) -print -delete | \
                sed 's|^|[post-checkout] Deleting |'
        fi
        ;;
esac
