#!/bin/sh

if [ $# -eq 0 ]; then
    set -- *Register.csv
fi

ynab-cleanup "$@" \
    | ynab-combine-flows \
    | ynab-adjust-categories \
    | csvgrep -c Cleared -r 'Cleared|Reconciled' \
    | csvgrep -i -c Category -r '^$'
