#!/bin/sh

csvpyrow "import re; _['Total'] = re.sub(r'[0-9]', '*', _['Total'])" \
    | if [ -t 1 ]; then
        if command -v csview >/dev/null 2>&1; then
            csview
        else
            csvlook -I
        fi
    else
        cat
    fi
