#!/bin/sh

set_by_payee () {
    csvpycol -c Category 'next((category for pattern, category in zip(itertools.islice(args, 0, None, 2), itertools.islice(args, 1, None, 2)) if re.search(pattern, Payee)), Category)' "$@"
}

set_by_payee_and_category () {
    csvpycol -c Category 'next((category for pattern, catpattern, category in zip(itertools.islice(args, 0, None, 3), itertools.islice(args, 1, None, 3), itertools.islice(args, 2, None, 3)) if re.search(pattern, Payee) and re.search(catpattern, Category)), Category)' "$@"
}

rename_category () {
    csvpycol -c Category 'next((category for pattern, category in zip(itertools.islice(args, 0, None, 2), itertools.islice(args, 1, None, 2)) if re.search(pattern, Category)), Category)' "$@"
}

# Specify rules to split up my current Spending Money category for further
# analysis.
filter_dining="Chipotle|Khazana|Sweet Tomatoes|Schlotzsky|Popeye|Cheese Love|Dairy Queen|Wendy|Arby|Jack in the Box|Taco Bell|Blazin Barbeque|Sprinkles|Queso Good|Village Coffee|Culver|Chick-fil-A|Famous 48|Cracker Barrel|Snack Bar|Johnny Rockets|Krispy Kreme|Sweet Tomatoes|Starbucks|Applebee|Red Robin|Chili's|Butters|Gonutz|Barrio Queen|Khazana|Red Fire Cookery|Chipotle|Papa Murphy|Chick-Fil-A|Spoonz|Reef's Kitchen|Outback|Papa John|Buffalo Wild Wings|Caribou Coffee|Auntie Anne|Burger King|Hot Dogs|Raising Cane|KFC|TGI Friday|IHOP|Daily Dose Cafe|McDonald|Spaghetti Factory"
filter_entertainment="Fair|Ticketmaster|Fantasy Photo Booth|Museum|Party Jungle|Comerica|Krazy Air|Mccormick Stillman|Macdonald's Ranch|Chuck.*Cheese|Ready Set Play"
filter_furniture='Ikea|Tuft|Sleep Number|Whimsie'
filter_gas="Holiday|Circle K|Costco.*Gas|Fry's Fuel|QuikTrip|Motley BP"
filter_pets='Petco|PetSmart|Petsmart'

cat "$@" \
    | rename_category \
        "Hidden Categories: Bras$" "Spending: Spending Money" \
        "Spending: Bills" "Immediate Obligations: Bills" \
        "Hidden Categories: Veterinary" "Contingencies: Veterinary" \
        "Hidden Categories: Medical & Dental" "Contingencies: Medical & Dental" \
        "Spending: Allowance" "Immediate Obligations: Allowance" \
        "Spending: Savings Allowance Investments" "Immediate Obligations: Savings Allowance Investments" \
    | set_by_payee \
        "$filter_dining" "Spending: Dining" \
        "$filter_entertainment" "Spending: Entertainment" \
        "$filter_furniture" "Spending: Furnishings" \
        "$filter_gas" "Spending: Gas" \
        "$filter_pets" "Spending: Pets" \
        "Great Wolf" "Future: Gifts" \
        \
        "iTunes" "Immediate Obligations: Allowance" \
        "Parallels" "Future: Future Bills" \
        \
        "M&T Mortgage" "Rental Property: Townhouse: Rental Bills" \
        "Maplebrook Estates" "Rental Property: Townhouse: Rental Bills" \
        "Legalzoom" "Rental Property: Townhouse: Rental Future Bills" \
        "Tom’s Custom Window" "Rental Property: Townhouse: Rental Maintenance" \
        "Sunrise" "Rental Property: Trailer: Rental Bills" \
        "Berkeley Electric" "Rental Property: Trailer: Rental Bills" \
        "Berkeley County" "Rental Property: Trailer: Rental Future Bills" \
        "Picture People" "Future: Future Bills" \
    \
    | set_by_payee_and_category \
        "Anthony Meyers" "To be Budgeted|Bills" "Rental Property: Townhouse: Rental Income" \
        "Anthony Meyers" "Rental Property Expenses" "Rental Property: Townhouse: Rental Maintenance" \
        "Shutterfly" "Future: Christmas Gifts" "Future: Future Bills" \
    | cat
