#!/bin/sh

#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] "

Options:
  -r   Reverse sort
  -h   Show usage
END
    exit 2
}

reverse=
while getopts rh opt; do
    case "$opt" in
        r)
            reverse=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

csvsql --query "SELECT Payee, Category, AVG(Amount) as Median FROM ( SELECT *, ( SELECT COUNT() FROM stdin AS _ WHERE Payee=stdin.Payee AND Category=stdin.Category AND (Amount>stdin.Amount OR Amount=stdin.Amount AND ROWID>stdin.ROWID))-( SELECT COUNT() FROM stdin AS _ WHERE Payee=stdin.Payee AND Category=stdin.Category AND (Amount<stdin.Amount OR Amount=stdin.Amount AND ROWID<stdin.ROWID)) AS m FROM stdin WHERE m BETWEEN -1 AND 1) GROUP BY Payee, Category" \
    | csvsort -c Median ${reverse:+-r} \
    | csvcurrencyformat Median \
    | if [ -t 1 ]; then
        if command -v csview >/dev/null 2>&1; then
            csview
        else
            csvlook -I
        fi
    else
        cat
    fi
