#!/bin/sh

if [ $# -eq 0 ] || [ "$1" = "-" ]; then
    tmpfile="$(mktemp -t "${0##*/}.XXXX")"
    trap 'rm -f "$tmpfile"' EXIT INT TERM
    cat >"$tmpfile"
    set -- "$tmpfile"
fi

sed '1s/^\xEF\xBB\xBF//; 1s/^[^,]*,/Account,/' "$@" \
    | csvcut -C 'Category Group,Category' \
    | sed '1s#Category Group/Category#Category#' \
    | strip-emoji \
    | sed -e 's/[▪️]//g; s/, */,/g; s/  */ /g;'
