#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] "

Options:
  -r   Reverse sort
  -h   Show usage
END
    exit 2
}
reverse=
while getopts rh opt; do
    case "$opt" in
        r)
            reverse=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

csvsql --query 'select payee,category,sum(amount)/count(amount) as Average from stdin group by payee,category' \
    | csvsort -c Average ${reverse:+-r} \
    | csvcurrencyformat Average \
    | if [ -t 1 ]; then
        if command -v csview >/dev/null 2>&1; then
            csview
        else
            csvlook -I
        fi
    else
        cat
    fi
