#!/bin/sh

if [ $# -eq 0 ]; then
    tmpfile="$(mktemp -t "${0##*/}.XXXX")"
    trap 'rm -f "$tmpfile"' EXIT INT TERM
    cat >"$tmpfile"
    set -- "$tmpfile"
fi

sed '1s/^\xEF\xBB\xBF//' "$@" \
    | csvcut -C 'Category Group,Category Group/Category' \
    | strip-emoji \
    | sed -e 's/[▪️]//g'
