#!/bin/sh

set_by_payee () {
    csvpycol -c Category 'next((category for pattern, category in zip(args[:-1], args[1:]) if re.search(pattern, Payee)), Category)' "$@"
}

set_by_payee_and_category () {
    csvpycol -c Category 'next((category for pattern, catpattern, category in zip(args[:-2], args[1:-1], args[2:]) if re.search(pattern, Payee) and re.search(catpattern, Category)), Category)' "$@"
}

# Specify rules to split up my current Spending Money category for further
# analysis.
filter_dining="Chipotle|Khazana|Sweet Tomatoes|Schlotzsky|Popeye|Cheese Love|Dairy Queen|Wendy|Arby|Jack in the Box|Taco Bell|Blazin Barbeque|Sprinkles|Queso Good|Village Coffee|Culver|Chick-fil-A|Famous 48|Cracker Barrel|Snack Bar|Johnny Rockets|Krispy Kreme|Sweet Tomatoes|Starbucks|Applebee|Red Robin|Chili's|Butters|Gonutz|Barrio Queen|Khazana|Red Fire Cookery|Chipotle|Papa Murphy|Chick-Fil-A|Spoonz|Reef's Kitchen|Outback|Papa John|Buffalo Wild Wings|Caribou Coffee|Auntie Anne|Burger King|Hot Dogs|Raising Cane|KFC|TGI Friday|IHOP|Daily Dose Cafe|McDonald|Spaghetti Factory"
filter_entertainment="Fair|Ticketmaster|Fantasy Photo Booth|Museum|Party Jungle|Comerica|Krazy Air|Mccormick Stillman|Macdonald's Ranch|Chuck.*Cheese|Ready Set Play"
filter_furniture='Ikea|Tuft|Sleep Number|Whimsie'
filter_gas="Holiday|Circle K|Costco.*Gas|Fry's Fuel|QuikTrip|Motley BP"
filter_pets='Petco|PetSmart|Petsmart'

cat "$@" \
    | set_by_payee \
        "$filter_dining" Dining \
        "$filter_entertainment" Entertainment \
        "$filter_furniture" Furnishings \
        "$filter_gas" Gas \
        "$filter_pets" Pets \
        "Great Wolf" Gifts \
        \
        "iTunes" Allowance \
        "Parallels" "Future Bills" \
        \
        "M&T Mortgage" "Rental Property: Townhouse Bills" \
        "Maplebrook Estates" "Rental Property: Townhouse Bills" \
        "Legalzoom" "Rental Property: Townhouse Future Bills" \
        "Tom’s Custom Window" "Rental Property: Townhouse Maintenance" \
        "Sunrise" "Rental Property: Trailer Bills" \
        "Berkeley Electric" "Rental Property: Trailer Bills" \
        "Berkeley County" "Rental Property: Trailer Future Bills" \
    \
    | set_by_payee_and_category \
        "Anthony Meyers" "To be Budgeted|Bills" "Rental Property: Townhouse Income" \
        "Anthony Meyers" "Rental Property Expenses" "Rental Property: Townhouse Maintenance" \
    | cat
