#!/bin/sh
# Run the specified command, sending the command being run and its output to
# a new private gist at https://gist.github.com/

tempfile="$(mktemp -t "${0##*/}.XXXXXX")"
trap 'rm -f $tempfile' EXIT INT TERM
{
    printf '$ %s\n' "$*"
    eval "$@" 2>&1
} | tee "$tempfile"
gh gist create <"$tempfile"
