#!/bin/sh
#
# Integrates a branch into the current branch.
#
# This will first rebase that branch onto the current branch, to create
# a clean history without merge lines. Then it will merge that into the
# current branch.

CUR_BRANCH=`git symbolic-ref HEAD | sed "s/refs\/heads\///"`
BRANCH=$1

git rebase $CUR_BRANCH $BRANCH || exit 1
git checkout $CUR_BRANCH
git merge $BRANCH || exit 1

if test "$2" = "-e"; then
	git commit --amend
fi

git branch -D $BRANCH
