#!/bin/sh

set -e

for file; do
    case "$file" in
        *:*)
            git checkout "${file%%:*}" -- "${file#*:}"
            ;;
        *)
            git attic -- "$file" \
                | awk -F: '!visited[$2]++' \
                | cut -d" " -f2- \
                | tr '\n' '\0' \
                | xargs -0 "$0"
            ;;
    esac
done
