#!/bin/bash
#
# Squashes a branch and stages it on a new branch off of master.
#
# This will take the current branch and squash its contents into a new commit
# in a new branch called "<current_branch_name>-stage". That branch will be
# based off master.

CUR_BRANCH=`git symbolic-ref HEAD | sed "s/refs\/heads\///"`
git checkout -b $CUR_BRANCH-stage master
git merge --squash $CUR_BRANCH
