#!/bin/sh

if [ $# -eq 0 ]; then
    set -- refs/heads/
fi

if [ -t 1 ]; then
    set -- --color=always "$@"
fi

git for-each-ref --sort=committerdate --format='%(color:yellow)%(HEAD) %(refname:short)|%(color:bold green)%(committerdate:relative)|%(color:reset)%(objectname:short) %(upstream:track) %(subject) <%(color:blue)%(authorname)>%(color:reset)' "$@" | column -ts'|'
