#!/bin/sh

set -eu

directory=
for arg; do
    case "$arg" in
        -*)
            continue
            ;;
        *)
            directory="$arg"
            break
            ;;
    esac
done

git init "$@"
if [ -n "$directory" ]; then
    cd "$directory"
fi
if ! git rev-parse HEAD >/dev/null 2>&1; then
    git commit --allow-empty -m "Root commit"
    git add .
    git commit --allow-empty -m "Initial commit"
fi
