#!/bin/sh
# "must" stash -- attempt to save a stash, but if nothing existed to be
# stashed, then exit with 100. If this exits with zero, we know that both
# something existed to be stashed, and it was stashed.

current="$(git rev-parse --verify refs/stash 2>/dev/null)"
git stash save "$@" || exit $?
new="$(git rev-parse --verify refs/stash 2>/dev/null)"
if [ -z "$new" ] || [ "$new" = "$current" ]; then
    # Nothing was stashed
    exit 100
fi
