#!/bin/sh

tmpfile=$(mktemp -t "${0##*/}.XXXX")
trap 'rm -f "$tmpfile"' EXIT INT TERM

export GIT_TERMINAL_PROMPT=0

git config gc.auto 0

canonical_url () {
    sed \
        -e 's#meta-oe#meta-openembedded#' \
        -e 's#.*/meta-micro.*#git://git.openembedded.org/meta-micro#' \
        -e 's#git://git.angstrom-distribution.org/#https://github.com/Angstrom-distribution/#' \
        -e 's#^git://git.openembedded.org/bitbake.*#https://github.com/openembedded/bitbake#' \
        -e 's#^git://git.openembedded.org/meta-openembedded.*#https://github.com/openembedded/meta-openembedded#' \
        -e 's#^git://git.openembedded.org/openembedded-core.*#https://github.com/openembedded/openembedded-core#' \
        -e 's#^git://git.yoctoproject.org/meta-mentor#https://github.com/MentorEmbedded/meta-mentor#' \
        -e 's#^git://github#https://github#' \
        -e 's#^http://github#https://github#' \
        -e '/github/s#\.git$##'
}

git submodule init
git config --get-regexp 'submodule\..*\.url' \
    | awk '{print $2}' \
    | canonical_url \
    | sort >"$tmpfile"
git for-each-ref --format='%(refname)' refs/heads/\* refs/remotes/origin/\* \
    | grep -Ev '\.trac|/HEAD$' \
    | xargs sh -c 'git rev-list "$@" -- .gitmodules' - \
    | xargs -I"{}" git show "{}:.gitmodules" \
    | git config -f - --get-regexp 'submodule\..*\.url' \
    | awk '{print $2}' \
    | canonical_url \
    | awk '!visited[$1]++' \
    | sort \
    | comm -13 "$tmpfile" - \
    | xargs -t -I"{}" git fetch -n "{}" "+refs/*:refs/subtrac/*"
git for-each-ref --format='%(refname)' refs/subtrac \
    | sed -e 's/^/delete /' \
    | git update-ref --stdin

git config --unset gc.auto
