#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] args

Options:
  -m   Show merged, not unmerged branches
  -h   Show usage
END
    exit 2
}

merged=0
while getopts mh opt; do
    case "$opt" in
        m)
            merged=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM

git for-each-ref --format="%(refname)" "$@" \
    | grep -v "$(git symbolic-ref HEAD)" \
    | grep -v /HEAD \
    | while read -r ref; do
        git cherry-tree "$ref" >"$tmpfile"
        if [ $merged -eq 1 ]; then
            if ! [ -s "$tmpfile" ]; then
                echo "$(git rev-parse --abbrev-ref "$ref")"
            fi
        else
            if [ -s "$tmpfile" ]; then
                echo "$(git rev-parse --abbrev-ref "$ref"):"
                cat "$tmpfile"
            fi
        fi
    done
