#!/bin/sh

# shellcheck disable=SC3028
case "${OSTYPE:-}" in
    darwin*)
        ncpus=$(sysctl -n hw.ncpu)
        ;;
    *)
        ncpus=$(grep -c processor /proc/cpuinfo)
        ;;
esac

if [ $# -eq 0 ]; then
    set -- --all
fi

git fetch --jobs="$ncpus" --multiple "$@"
