#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] [TOPIC_BRANCH [UPSTREAM_BRANCH]]"

Show a history of topic branch changes by comparing entries in the topic
branch's reflog. TOPIC_BRANCH defaults to HEAD if a commit is checked out, or
the branch HEAD points to otherwise.

Options:
  -a ARGS  Pass additional arguments to underlying range-diff or tbdiff
  -h       Show usage
END
    exit 2
}

pager() {
    if [ -t 1 ]; then
        PAGER="${PAGER:-less}"
        export LESS="${LESS:-FRX}"
    else
        PAGER=cat
    fi
    eval "$PAGER" '"$@"'
}

pairwise() {
    # See https://docs.python.org/3/library/itertools.html#itertools-recipes
    python3 -c 'import itertools,sys; i=(l.rstrip("\n\r") for l in sys.stdin.readlines()); a, b = itertools.tee(i); next(b, None); sys.stdout.writelines("{} {}\n".format(*j) for j in zip(a, b))'
}

extra_diff_args=
while getopts a:h opt; do
    case "$opt" in
        a)
            extra_diff_args="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    branch="$(git rev-parse --verify --quiet --symbolic-full-name HEAD)" || die "fatal: Not a valid ref: HEAD"
else
    branch="${1:-HEAD}"
fi

if [ $# -gt 1 ]; then
    shift
    upstream="${1:-}"
    if [ $# -gt 1 ]; then
        shift
    fi
fi

if [ "$upstream" = "--" ]; then
    upstream=
fi

GIT_EXEC_PATH="$(git --exec-path)"

# shellcheck source=/usr/lib/git-core/git-sh-setup
. "$GIT_EXEC_PATH/git-sh-setup"

test -n "$branch" || usage
git rev-parse --verify --quiet "$branch" || die "fatal: Not a valid ref: $branch"

if [ -e "$GIT_EXEC_PATH/git-range-diff" ]; then
    tbdiff=0
    diff_cmd=range-diff
else
    tbdiff=1
    diff_cmd=tbdiff
fi

revs="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
if ! git reflog --pretty=format:%h "$branch" "$@" >>"$revs"; then
    die "fatal: reflog of $branch failed"
fi
if ! [ -s "$revs" ]; then
    die "fatal: empty reflog for $branch"
fi
# shellcheck disable=SC2046
if [ $(wc -l <"$revs") -lt 2 ]; then
    die "fatal: reflog for $branch has fewer than 2 entries"
fi

if ! [ -t 1 ]; then
    diff_args="--no-color"
else
    if [ $tbdiff -eq 1 ]; then
        diff_args="--dual-color"
    else
        diff_args="--color=always"
    fi
fi
diff_args="$diff_args $extra_diff_args"
if [ -n "$upstream" ]; then
    diff_args="$diff_args $upstream..\$2 $upstream..\$1"
else
    diff_args="$diff_args \$2...\$1"
fi

cat "$revs" \
    | pairwise \
    | xargs -n 2 sh -c "if [ \$1 != \$2 ]; then echo \"\$1...\$2:\"; git $diff_cmd $diff_args; fi" - \
    | pager
