#!/bin/sh

usage() {
    echo >&2 "${0##*/} [options] [REMOTE..]"
    echo >&2
    echo >&2 "Prune branches of the specified remote(s), relative to the origin."
    echo >&2 "Defaults to all remotes but ORIGIN_REMOTE if no remotes are specified."
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  REMOTE                Prune refs of the specified remote, defaults to $USER."
    echo >&2 "  -o ORIGIN_REMOTE      Prune branches relative to the specified remote, not origin."
    echo >&2 "  -u UPSTREAM_BRANCHES  Specify the base upstream branches where the changes are merged,"
    echo >&2 "                        defaults to master. Comma-separated."
    echo >&2 "  -R                    Remote. Remove upstream branches, not just tracking branches."
    echo >&2 "  -L                    Local only. Remove tracking branches, not upstream branches. (Default)"
    echo >&2 "  -n                    Dry-run"
    exit 2
}

process_arguments() {
    origin=origin
    dry_run=0
    local_only=1
    upstream_branches=master
    while getopts o:u:LRnh opt; do
        case "$opt" in
            o)
                origin="$OPTARG"
                ;;
            u)
                upstream_branches="$OPTARG"
                ;;
            L)
                local_only=1
                ;;
            R)
                local_only=0
                ;;
            n)
                dry_run=1
                ;;
            \? | h)
                usage
                ;;
        esac
    done
    shift $((OPTIND - 1))

    upstreams="$(echo "$upstream_branches" | tr ',' '\n' | sed -e "s#^#$origin/#g")"

    if [ $dry_run -eq 1 ]; then
        prune_args=-n
    else
        prune_args=
    fi

    if [ $local_only -eq 0 ]; then
        prune_args="$prune_args -R"
    fi
}

set -u

process_arguments "$@"
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    set -- $(git remote | grep -vx "$origin")
fi

ret=0

{
    echo "$@" | tr ' ' '\n' | xargs -t -I"{}" -n 1 git prune-merged -l -r "{}" $prune_args -c "$origin"
    echo "$@" | tr ' ' '\n' | xargs -t -I"{}" -n 1 git prune-merged -l -r "{}" $prune_args $upstreams
} \
    | sort -u \
    | xargs git branch -r -d
exit "$ret"
