#!/usr/bin/env bash

set -ueo pipefail

usage () {
    echo >&2 "Usage: ${0##*/} [-n] GIST_URL [FILENAME]"
    echo >&2
    echo >&2 "If FILENAME is unspecified, '-' will be used."
    echo >&2
    echo >&2 "-n    Dry run, show what would be updated."
    exit 1
}

dry_run=0
while getopts nh opt; do
    case "$opt" in
        n)
            dry_run=1
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ] || [ $# -gt 2 ]; then
    usage
fi

gist_url="$1"
filename="${2:--}"
raw_url="$(echo "$gist_url" | sed "s,github\.com,githubusercontent.com,")/raw/$filename"

tmpfile="$(mktemp -t "$filename.XXXXXX")"
tmpfile2="$(mktemp -t "$filename.XXXXXX")"
trap 'rm -f "$tmpfile" "$tmpfile2"' EXIT INT TERM

if [ -e "$filename" ]; then
    cp "$filename" "$tmpfile"
else
    cat >>"$tmpfile"
fi

diff_pipeline="cat"
if [ -t 1 ]; then
    if [ -n "${LESSCOLORIZER:-}" ]; then
        diff_pipeline="$diff_pipeline | $LESSCOLORIZER -l diff"
    elif which bat &>/dev/null; then
        diff_pipeline="$diff_pipeline | bat -l Diff --color always"
    fi
    if which diff-so-fancy &>/dev/null; then
        diff_pipeline="$diff_pipeline | diff-so-fancy"
    elif which diff-highlight &>/dev/null; then
        diff_pipeline="$diff_pipeline | diff-highlight"
    fi
    if [ -n "${PAGER:-}" ]; then
        diff_pipeline="$diff_pipeline | $PAGER"
    elif which less &>/dev/null; then
        diff_pipeline="$diff_pipeline | less"
    elif which more &>/dev/null; then
        diff_pipeline="$diff_pipeline | more"
    fi
fi
export LESS="${LESS--R}"

ret=0
if curl -fsSL "$raw_url" >"$tmpfile2"; then
    if [ -s "$tmpfile" ]; then
        cat "$tmpfile2"
    else
        echo >&2 "Error: curl fetched nothing"
        exit 1
    fi
else
    exit 1
fi | diff -urNd - "$tmpfile" | eval "$diff_pipeline" || ret=$?

if [ $ret -ne 0 ] && [ $dry_run -ne 1 ]; then
    if [ -t 1 ]; then
        while true; do
            read -r -n 1 -p 'Continue [Y/n]? ' i </dev/tty
            printf '\n'
            case "$i" in
                [Yy]|"")
                    break
                    ;;
                [Nn])
                    exit 0
                    ;;
            esac
        done
    fi
    gist -s -f "$filename" -u "$gist_url" "$tmpfile"
fi
