#!/bin/sh

default_exclude_pattern="rm_work|-native"

set -eu

usage() {
    cat <<END >&2
${0##*/} [options..] [BITBAKE_ARGS..]

Options:
  -x EXCLUDE_PATTERN  Default: $default_exclude_pattern
  -h   Show usage
END
    exit 2
}

exclude_pattern="$default_exclude_pattern"
while getopts x:h opt; do
    case "$opt" in
        x)
            exclude_pattern="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi


tmpdir="$(mktemp -d "$PWD/${0##*/}.XXXXXX")" || exit 1
trap 'rm -rf "$tmpdir"' EXIT INT TERM

cd "$tmpdir"
bitbake -g "$@" >/dev/null
cat task-depends.dot \
    | sed -e 's/\[label.*//; s/"\([^"]*\)\.[^"]*"/"\1"/g;' \
    | grep -vE "$(echo "${exclude_pattern}" | sed -e 's/^-/\\-/')${exclude_pattern:+|}"'"([^"]*)" -> "\1"' \
    | awk '!visited[$0]++' \
    | graph-easy -
