#!/bin/sh

usage() {
    cat <<END >&2
${0##*/} [options..] VAR [RECIPE]

Options:
  -h   Show usage
END
    exit 2
}

evalf () {
    fmt="$1"
    shift
    # shellcheck disable=SC2059
    # printf >&2 "evalf: $fmt\n" "$@"
    # eval echo >&2 "evalf: $(printf "$fmt" "$@")"
    eval "$(printf "$fmt" "$@")"
}

while getopts h opt; do
    case "$opt" in
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
    usage
fi

var="$1"
recipe="${2:-}"

tmpfile="$(mktemp -t "${0##*/}.XXXXXX")" || exit 1
trap 'rm -f "$tmpfile"' EXIT INT TERM

if [ -n "$recipe" ]; then
    bitbake -e "$recipe"
else
    bitbake -e
fi >"$tmpfile" || {
    cat "$tmpfile" >&2
    exit 1
}

eval "$(cat "$tmpfile" | grep -E "^(export )?$var=")"
# shellcheck disable=SC2016
evalf 'echo "$%s"' "$var"
