#!/bin/sh

set -eu

usage() {
    cat <<END >&2
${0##*/} [options..] [LAYERPATH [PRIORITY]]

Options:
  -h   Show usage
END
    exit 2
}

while getopts h opt; do
    case "$opt" in
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

layerpath="${1:-meta-local}"
priority="${2:-1}"
if [ ! -e "$layerpath" ]; then
    bitbake-layers create-layer -p "$priority" "$layerpath"
fi
bitbake-layers add-layer "$layerpath"
