#!/bin/sh

time=+6 # older than 7 days ago

if [ "$1" = "-n" ]; then
    dry_run=1
else
    dry_run=
fi

cache_paths () {
    locate -ebr '^cached-binaries\|sstate-cache$'
    echo /cache/sstate
}

readlinks () {
    while read link; do
        readlink -f $link
    done
}

caches=`mktemp -t clean-sstate.XXXXXX`
if [ $# -eq 0 ]; then
    set -- $(cache_paths | grep -E '/clarson|kergoth/')
fi
for arg; do echo "$arg"; done | readlinks | sort -u >>$caches

cat $caches | while read path; do
    find "$path" -atime $time -type f -print0
done | xargs -0 ${dry_run:+-n 1 echo }rm -fv

cat $caches | while read path; do
    find "$path" -type l | while read link; do
        if [ ! -e "$link" ]; then
            ${dry_run:+echo }rm -fv "$link"
        fi
    done
done

rm -f $caches
exit 0
