#!/usr/bin/env bash
# Clone an oe/yocto layer repo using the layer index.

set -euo pipefail

query="$1"
shift
case "$query" in
    bitbake)
	git clone https://github.com/openembedded/bitbake "$@"
	exit $?
	;;
    oe-core)
        query=openembedded-core
        ;;
    meta-oe)
        query=meta-openembedded
        ;;
esac

http 'http://layers.openembedded.org/layerindex/branch/master/layers/' \
    | pup .showRollie 'text{}' \
    | grep :// \
    | sed -e 's/ *//; s#/$##g; s/\.git$//g;' \
    | sort -u \
    | fzf-tmux --select-1 --multi --query="$query" --exit-0 \
    | while read -r url; do
        git clone "$url" "$@" || exit $?
    done
