#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<END >&2
${0##*/} [options..] HOST BUILDDIR IMAGE_TARGET DESTDIR

Options:
  -t IMAGE_TYPES  Specify image types to wait for and copy. Default: wic.bz2
  -h              Show usage
END
    exit 2
}

image_types=wic.bz2
while getopts h opt; do
    case "$opt" in
        t)
            image_types="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 4 ]; then
    usage
fi

host="$1"
shift
builddir="$1"
shift
image_target="$1"
shift
destdir="$1"
shift

# shellcheck disable=SC2029
ssh "$host" .dotfiles/bitbake/scripts/wait-for-images -t "$image_types" "$builddir" "$image_target" \
    | sed -e "s#^#$host:#" \
    | tr '\n' '\0' \
    | ifne xargs -t0 sh -c "rsync -aLvpP \"\$@\" \"$destdir/\"" -
