#!/bin/sh

set -eu

usage() {
    cat <<END >&2
${0##*/} [options..] BUILD_DIR

Options:
  -h   Show usage
END
    exit 2
}

while getopts h opt; do
    case "$opt" in
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage
fi
builddir="$1"
shift
builddir="$(cd "$builddir" && pwd -P)"

# Wait for bitbake to complete
lsof +r -f -- "$builddir/bitbake.lock" >/dev/null 2>&1
